### ISSUE TITLE
BErtopic.representation open AI

### ISSUE THREAD

**Issue by nara-simba** [MaartenGr/BERTopic#1011]
I am experimenting with bertopic.representation OpenAI() . With a free license token.

I got below RatelimitError reached due to restriction per minute. There were 380K documents, each document is a couple of sentences. Can you introduce a feature to throttle while accessing such external apis? Or what could be the issue?

Narasimha

RateLimitError: Rate limit reached for default-global-with-image-limits in organization org-qN6pHiTtKaYkrCxD1QsRaDu4 on requests per min. Limit: 60.000000 / min. Current: 70.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

**Comment by brianferrell787** [comment]
@MaartenGr @nara-simba I think I have answer to this. If you go to this site: https://platform.openai.com/docs/guides/rate-limits/error-mitigation
 It mentions some code to help with rate limits per minute: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_handle_rate_limits.ipynb

So I managed to do something like this and the error went away
`
# Create your openai representation model
# Define a function that adds a delay to a Completion API call
def delayed_completion(delay_in_seconds: float = 1, **kwargs):
    """Delay a completion by a specified amount of time."""

    # Sleep for the delay
    time.sleep(delay_in_seconds)

    # Call the Completion API and return the result
    return openai.Completion.create(**kwargs)

# Calculate the delay based on your rate limit
delay = 60.0 / 20
openai.api_key = "API_KEY"
representation_model = delayed_completion(
    delay_in_seconds=delay,
    model="text-ada-001",
    prompt ="I have the following documents: [DOCUMENTS]. What topic do they contain?"
)

finbert = TransformerDocumentEmbeddings('ProsusAI/finbert')
topic_model = BERTopic(embedding_model=finbert,
                       nr_topics=30,
                       n_gram_range=(1, 5),
                       representation_model=representation_model)
`

I chose text-ada-001 because I saw it here https://github.com/MaartenGr/BERTopic/blob/master/bertopic/representation/_openai.py

**Comment by MaartenGr** [comment]
@brianferrell787 Unfortunately, the function `delayed_completion` that you passed to `representation_model` will not work. There is a specific way of creating custom models as described [here](https://maartengr.github.io/BERTopic/getting_started/representation/representation.html#custom-model). It mentions certain characteristics the class needs to have in order to be used as a `representation_model`. Since you are passing a custom function and not a custom class according to the guidelines, this will not work.
