### ISSUE TITLE
Loading the model to use on same data or subset

### ISSUE THREAD

**Issue by lila-97** [MaartenGr/BERTopic#1034]
Hi Maarten, thanks again for being so responsive. I looked through the existing issues but I could not find an answer to this question. 
I have done a very long training on my huge dataset (2+million tweets) with BERTopic. 
I know how to save the model and load it back into the environment. 
However, I don't understand if, after loading it, I should call `my_model.fit_transform(tweets)` (which I think would still take a long time, basically taking away any sense from loading the model?) or `my_model.fit(tweets)`, which however according to previous issues would generate new predictions, potentially different from the ones observed after training. 
Since I have generated many topics and will merge them manually, it is very important to me to keep the same predictions. I read that I can achieve this by setting the same `random_state` parameter within the UMAP model, since this should be the only submodel that has a stochastic nature. The questions then are:
- How do I set this parameter again after loading the model, so that UMAP does not change?
- If that's not the way to do this, is there another way? Or do I just need to re-train every time? 
Thank you in advance

**Comment by MaartenGr** [comment]
The general pipeline is as follows. First, you perform either `fit` or `fit_transform` on your dataset. Then, that model is saved using `topic_model.save("my_model")`. At this point, you have a saved topic model that is trained on those 2+ million tweets. Now, when you load in the model using `loaded_model = BERTopic.load("my_model")`, you still have information about the topics of those 2+ million tweets. That information can typically be found in its attributes, such as `loaded_model.topics_` or `loaded_model.probabilities_`. 

At this point, when you then run either `loaded_model.fit_transform(tweets)` or `loaded_model.fit(tweets)` you will re-train the model which is unnecessary since you already trained your model. Since you can already find the topics of the 2+ million tweets in `loaded_model.topics_`, there is no need to call either `.fit` or `.fit_transform` again. 

This also means that setting `random_state` now is not really necessary since you have a trained model that does not chance anymore. In other words, after you have loaded your model, you can start merging them manually without having to run `.fit` or `.fit_transform`.
