### ISSUE TITLE
Custom embeddings with custom parameters 

### ISSUE THREAD

**Issue by alessiogandelli** [MaartenGr/BERTopic#1091]
I was trying to create to create a topic model using custom embeddings (OpenAi ones) but I also wanted to add a representation model and other parameters while instantiating BERtopic, more specifically 

This works:

```
topic_model = BERTopic()
topic, probs = topic_model.fit_transform(tweets, embeddings)
```

and this does not

```
topic_model = BERTopic(representation_model=KeyBERTInspired())
topic, probs = topic_model.fit_transform(tweets, embeddings)
```

The error given while fitting is:

`AttributeError: 'NoneType' object has no attribute 'embed_documents'`

What can I put in embedding_model field to let this work? 
thanks in advance

**Comment by MaartenGr** [comment]
You will need to create a custom backend for OpenAI and pass that to `embedding_model` in order to use representation models like `KeyBERTInspired` and `MaximalMarginalRelevance`. You can find more about creating a custom backend [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-backend).
