### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

### ISSUE THREAD

**Issue by ibeppo993** [MaartenGr/BERTopic#1096]
Hi, I'm getting this error at this point in the code:
`topics, probs = topic_model.fit_transform(docs)
`
Error:
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

As a sentence model I am using this:
`sentence_model = SentenceTransformer('bigscience-data/sgpt-bloom-1b7-nli', device = 'cpu')
`
With other models (es. "efederici/sentence-IT5-base") I do not get the error back.

Thanks

**Comment by MaartenGr** [comment]
Most likely, it is due to the embedding model that you are using that might not be directly supported by SentenceTransformer. Instead, you would have to create the [embedding manually](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-embeddings) and pass them to BERTopic, use HuggingFace as mentioned [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#hugging-face-transformers), or create a [custom backend](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html#custom-backend) in BERTopic.
