### ISSUE TITLE
Negative value in c-tf-idf

### ISSUE THREAD

**Issue by dopc** [MaartenGr/BERTopic#116]
Hey Maarten,

I have encountered negative c-tf-idf value for a word with new c-tf-idf.
That means, 
`avg_nr_samples` is less than `df` for this word in [this line](https://github.com/MaartenGr/BERTopic/blob/master/bertopic/_ctfidf.py#L40).

Is this a problem?
There is a discussion about that, [here](https://stackoverflow.com/questions/16648599/tfidf-calculating-confusion)

**Comment by MaartenGr** [comment]
This should not be an issue. The discussion that you linked to is related to the traditional TF-IDF measurement. In c-TF-IDF, the IDF value does not necessarily mean the same thing as the IDF in TF-IDF since we are comparing aggregated frequencies. In practice, with sufficient data, negative values will most likely represent features/words that appear more often than the average number of samples. Thus, those are simply stopwords that will not be used when creating the topic representations.
