### ISSUE TITLE
Representations breaks get_topic(n)

### ISSUE THREAD

**Issue by NewsSoup** [MaartenGr/BERTopic#1170]
I am using a flan-alpaca-T5-large model from hugging face to generate amazing labels, but when I use get_topic(n) I only get the topic label with a frequency of 100%. This is not useful.

I need to still be able to get the list of words in a topic, since this is very useful. I suggest you use something like get_topic_label() for the topic label and leave get_topic(number) as it was: returning a list of tuples with words and frequencies.

Having tested out the representations module I must say that it would be easier from the developer side if you first run BERTopic normally and then generate the representation by calling a method. It would also be useful if you could allow the user to use [LIST] in the prompt and then generate the representations with something like topic_model.make_representations(lang_model, prompt, ["items", "for", "prompt"]). For example, knowing the topics from the text, I could pass the title or summaries through to get the topic representation.

On a side note, I thought you might find it interesting, but k-means produces cluster topics that are very easy to timeline, HDBSCAN chooses topics that are too granular (unless you want the chore of merging topics).

Another side note from the developer side is that BERTopic loads very slowly. Before pip freeze and venvs there was a convention to list libraries on top of the code for convenience. It would be more practical to move imports to within functions so that they are loaded to memory as needed (repeated use of the function will not have a speed decrease as the package will stay in memory). Clever placing of imports can significantly speed up your product's loading time. I've never tried importing using multiprocessing, but I imagine that can also help. On the internet, every second counts...

**Comment by MaartenGr** [comment]
Thanks for the suggestions! 

> I am using a flan-alpaca-T5-large model from hugging face to generate amazing labels, but when I use get_topic(n) I only get the topic label with a frequency of 100%. This is not useful.

> I need to still be able to get the list of words in a topic, since this is very useful. I suggest you use something like get_topic_label() for the topic label and leave get_topic(number) as it was: returning a list of tuples with words and frequencies.

The representation models are created to further fine-tune the topic representations. They are currently focused on updating the top n keywords that make up a topic and fine-tuning those. This works quite well for the KeyBERTInspired, PartOfSpeech, and MaximalMarginalRelevance modules but to a lesser extent for those that only give back a single label. Having said that, there might be representation models in the future that give back multiple labels, like the ZeroShotClassification representation model which would with the `get_topics` function. I am currently working on creating a multi-dimensional topic representation that can be described by a number of things, including automatically generated custom labels, keywords, manual custom labels, etc. 

> Having tested out the representations module I must say that it would be easier from the developer side if you first run BERTopic normally and then generate the representation by calling a method. 

This is already possible with the `.update_topics` method which allows you to update topic representations after having trained your model and allows for easy experimentation. Many users also want representations to be generated by specifying it when instantiating the class, it allows for an intuitive overview of the pipeline. So both scenarios are currently supported. 

> It would also be useful if you could allow the user to use [LIST] in the prompt and then generate the representations with something like topic_model.make_representations(lang_model, prompt, ["items", "for", "prompt"]). For example, knowing the topics from the text, I could pass the title or summaries through to get the topic representation.

I will have to look into this to see if I can extend the prompt tags to a number of different things, especially when the multi-dimensional topic representation is created. 

> On a side note, I thought you might find it interesting, but k-means produces cluster topics that are very easy to timeline, HDBSCAN chooses topics that are too granular (unless you want the chore of merging topics).

Thanks! I have not yet used k-Means for a dynamic topic modeling setting. Glad to hear it works well. 

> Another side note from the developer side is that BERTopic loads very slowly. Before pip freeze and venvs there was a convention to list libraries on top of the code for convenience. It would be more practical to move imports to within functions so that they are loaded to memory as needed (repeated use of the function will not have a speed decrease as the package will stay in memory). Clever placing of imports can significantly speed up your product's loading time. I've never tried importing using multiprocessing, but I imagine that can also help. On the internet, every second counts...

This is due to `pynndescent` which is an integral part of BERTopic and used for most users when instantiating BERTopic as many use UMAP. You can find more about the import speed in the [FAQ here](https://maartengr.github.io/BERTopic/faq.html#why-does-it-take-so-long-to-import-bertopic).

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
