### ISSUE TITLE
How to extract doc-topic correspondence after .transform

### ISSUE THREAD

**Issue by lila-97** [MaartenGr/BERTopic#1184]
Hi Marteen, I have a question about the `.transform` function. 
I have trained my topic model on 600k selected tweets, merged the topics and updated the model. 
After doing this, I want to extract topics for the remaining 1.3million tweets, without constructing another model since I believe this one could already do a decent job. What I do is the following; 

`# 1. loading the model trained on 600k tweets `

`my_model = BERTopic.load("Bertopic_whole_mar15_v8rec")`
`topics = pickle.load( open( "Bertopic_whole_mar15_v8rec.pickle", "rb" ) )`
`embeddings = pickle.load( open( "embeddings_mar15_all_v8rec.pickle", "rb" ) )` 

`# 2. loading the original dataset used for training, called new_df`

`# 3. merging the topics (i do this for various iterations, this is an example)`

`topics_to_merge = [[1, 10]]`
`my_model.merge_topics(new_df['text_bertopic'], topics_to_merge)`

`# 4. loading the dataset to transform, called new_df_2`

`# 5. transforming`

`topics, probs = my_model.transform(new_df_2['text_bertopic'])`

`6. Trying to extract topics per tweet information`

`df_topics_per_tweet = my_model.get_document_info(new_df_2['text_bertopic'])`
`df_topics_per_tweet.head()`

Point 6. is where I get an error, saying that the index of length 600k does not match the dimension of the dataset (1.3m) 

I had the feeling that point 3. should have already been executed on the new dataframe, but it gives me the same error as above, so I tried it this way. 

I have already tested on a subset the solution in which I also pass embeddings to `my_model.get_document_info`, but it keeps returning another error (to be specific: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices). 

What are these errors due to, in your opinion? And, more importantly, is there a way that I can extract this information for new_df_2, without having to train the model again? 

thanks in advance for your invaluable help.

**Comment by MaartenGr** [comment]
The `.get_document_info` is a method used for creating metadata for documents that the model was trained on. In other words, you would have to pass the initial documents to get the metadata.  

If you want to have the metadata for the documents the model was not trained on, then you would have to create a dataframe manually yourself since the metadata for transformed (not fitted) documents is not saved within the model. To get started, it might be worthwhile to check out some of the code in the [function](https://github.com/MaartenGr/BERTopic/blob/8fc11a2458d55adc5be4d4d9255baeeb485c35d5/bertopic/_bertopic.py#L1413).
