### ISSUE TITLE
How to include outliers (-1) into visualizations?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [MaartenGr/BERTopic#1186]
First of all thanks for great work!
In our case we have outliers which nearly exactly match some topic, so in some sense we are using BERTopic to "clean" anything that doesn't relate to main topic. In other words outliers consist 80% of data and this is expected behaviour.

How can we include outliers (aka -1 topic) into visualizations? Thx!

**Comment by MaartenGr** [comment]
Generally, the outlier topic is a collection of documents that have no semantic relationship with one another. In essence, they can be considered a random selection of documents. The visualizations do not include the outlier topic for those reasons, as we cannot consider these random documents a proper topic. 

Having said that, if your use case makes it so that these outliers are not really outliers but a proper topic, then I would advise mapping the -1 topic to `nr_topics + 1`. In other words, if you have 100 non-outlier topics, then you could map topic -1 to a new topic 101. You can do this with `.update_topics`. So something like this:

```python
topic_model.update_topics(docs, topics=my_updated_topics)
```

Where `my_updated_topics` are the topics you got after fitting where every `-1` value is replaced with `101`.

**Comment by ArtemBernatskyy** [comment]
Thx!!! ❤️❤️❤️
Works perfectly, hope it will also help others too.
