### ISSUE TITLE
AttributeError: 'BERTopic' object has no attribute 'representation_model'

### ISSUE THREAD

**Issue by jinhangjiang** [MaartenGr/BERTopic#1200]
Hi @MaartenGr , hope you are doing well. I want to bring up an issue I came across with bertopic==0.14.1 to your attention. Basically I trained and saved a model a couple of months ago. And today when I tried to load it back and do some analysis with topics_over_time function, the error poped up: "AttributeError: 'BERTopic' object has no attribute 'representation_model'"

I solved it by installing version 0.12.0. Not sure if other versions also work in this case. If someone can help look into it, it would be great. Thank you for your time!

**Comment by MaartenGr** [comment]
That is a function of how saving models in general work. When you save a model, it is important to do version control with it. For example, when you save a model, you will also need to make sure that you track the versions of BERTopic, its dependencies, python, etc. in order to reproduce the environment in which you worked. 

In other words, you will need to make sure that the environment in which you saved the model is the same as the environment where you load the model.

**Comment by jinhangjiang** [comment]
Okay, understood. Thank you for clarifying!
