### ISSUE TITLE
Less accurate results on human conversations

### ISSUE THREAD

**Issue by AbhiPawar5** [MaartenGr/BERTopic#122]
Hi Team, 
First of all, I really liked how intuitive and easy applying BERTopic is to variety of text data. Thanks for sharing this amazing package!

I was curious to apply BERTopic on normal conversations and see if it can get topics out of it. So, I referred a call sample dataset from Kaggle ([Switchboard corpus sample](https://www.kaggle.com/nltkdata/switchboard)). I used first call from A.1: Uh, do you have a pet Randy? to the text A.111: Bye. 
I cleaned, tokenized and lemmatized the text and I was able to pass this single call text to the model. But, the topic modeling results are not so satisfactory. 

The topics the model was able to get are:
Topic 1: take really  take three  talk  handle mean  call actually,  
Topic 2: okay fifty  thirty  thirty cable  cable  time six,  
Topic 3: night security  black stay  black intimidate  uncertain night  keep window,  
Topic 4: kid house  owner home  child home  grandpa shed  bathroom home,  
Topic 5: outdoor type  randy  type randy  newspapers area  randy size,  

Parameters used:
Installed BERTopic with pip install bertopic
BERTopic(top_n_words=5, n_gram_range=(1, 2), nr_topics=5)

In few others call texts, the results are far less accurate. Can you please provide any insights on how I can improve these results? Thanks! Take care.

**Comment by MaartenGr** [comment]
Thank you for the kind words!

From what you have shared, there are several things that are happening. First, by setting `nr_topics` so low many topics are forced to merge together. This results in less accurate topics that are being created. I would advise you not to set `nr_topics` and see how many topics are generated without. After that, you can further reduce topics if you feel they could be reduced. It is likely the results change significantly if you do not set that value. 

Second, it might be that you do not have enough data available to generate enough topics. You can play around with the `min_topic_size` to find a minimum topic size that will generate a sufficient amount of topics. Setting this too high will generate too few topics while setting this too low will generate too many topics. 

Let me know how it works out especially with the `nr_topics`!

**Comment by AbhiPawar5** [comment]
Hi @MaartenGr , thanks for your quick reply!
I experimented with your advice and the results were improved!

Experiments followed:
1) Passing processed text as word tokens and no `nr_topics `= produced 18 topics with good results
2) Passing processed text as word tokens WITH `nr_topics` = Average results 
3) Passing raw text as sentence tokens with and without `nr_topics `= produced only 2 topics with below average results

General observation : As soon as we pass `nr_topics`, it seems to lower the accuracy of the model by adding invalid words in a topic. For instance, these are the words for a topic:
```
[('she', 0.0428935998102865),
 ('her', 0.025960805414976938),
 ('shes', 0.024106462171050017),
 ('dog', 0.018646989131586213),
 ('she was', 0.015369388558753666)]
```

Please let me know your views/thoughts on this. Thanks! Take care.

**Comment by MaartenGr** [comment]
Thank you for trying some things out. Interesting results! From these results, I can see a few things happening. 

First, I am quite certain that not too many documents are used. In practice, when you have few documents available, fewer topics will be created. I typically get at least 50 topics when passing around 10,000 documents. Seeing as you get only 18 topics, I can imagine you do not have many documents available. Having said that, simply decreasing `min_topic_size` will most likely result in many more topics being created! 

Second, the `nr_topics` tries to iteratively combine topics based on the similarity between them. If only 18 topics are generated, then forcibly merging them would result in less coherent topics. You will not see this issue if you have >50 topics since it is more likely some can actually be merged. Thus, if you try to reduce 18 topics to 10, you will most likely reduce performance. However, if you reduce 200 topics to 100, it is likely to improve performance as you will merge many duplicates. 

Third, BERTopic takes in a list of documents. This means that if you pass in word tokens, a list of words, the model will try to create representations based on those words instead of the documents. In practice, it is best to pass a list of documents where the documents are raw text. 

I think it would be interesting to lower `min_topic_size` such that more topics will be generated.

**Comment by AbhiPawar5** [comment]
Thank you for your advice, @MaartenGr. I will definitely try these things out and see the results.
