### ISSUE TITLE
"ValueError: numpy.ndarray size changed" with numpy 1.19.2; need to use 1.20.2

### ISSUE THREAD

**Issue by mwunderlich** [MaartenGr/BERTopic#124]
When trying to use a freshly cloned copy of BERTopic with numpy 1.19.2, I got the following error: 

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject` 

I was able to fix this by updating numpy to 1.20.2. (all on Python 3.8 with Anaconda 2.0.3). 
Suggestion: add a requirements.txt with all the required packages and specific versions.

**Comment by MaartenGr** [comment]
You are most likely using an older version of BERTopic since the v0.7 version already has the correct numpy version both in the master branch as well as in the PyPi version:

https://github.com/MaartenGr/BERTopic/blob/9788f3f2994ffc1923ea449b8d69fe257ccdde89/setup.py#L15

You can find these requirements in the setup.py file mentioned above.

**Comment by mwunderlich** [comment]
Thanks a lot for the hint, Maarten. I missed the setup.py. The current version has the right Numpy version. Issue closed.
