### ISSUE TITLE
 Analyzing Chinese and Russian Newspaper Articles

### ISSUE THREAD

**Issue by mamingsuper** [MaartenGr/BERTopic#1257]
Greetings, I have a question to ask. Suppose I want to analyze Chinese and Russian newspaper articles regarding certain countries to extract topics. Should I combine the two languages' documents and generate a "language" covariate in the first? When processing, besides choosing a multilingual word embedding model, how should I deal with the CountVectorizer issue as attached? Are there any other things to pay attention to? Thank you very much!

from sklearn.feature_extraction.text import CountVectorizer
import jieba

def tokenize_zh(text):
    words = jieba.lcut(text)
    return words

vectorizer = CountVectorizer(tokenizer=tokenize_zh)

**Comment by MaartenGr** [comment]
I think it would be best to create a tokenizer that recognizes the languages and then uses `jieba` or the default tokenizer depending on the language since, and I could be mistaken here, `jieba`  does not work for Russian text. 

Having said that, if `jieba` works for Russian text, then the example you showed above should work.

**Comment by mamingsuper** [comment]
Thanks for the prompt and insightful reply.
