### ISSUE TITLE
Embedding takes a long time with a pre-trained model

### ISSUE THREAD

**Issue by sokol11** [MaartenGr/BERTopic#127]
Hi. I am trying to use pre-trained embeddings from HuggingFace to model topics on about 50K PubMed abstracts. It takes longer than I would expect (given that the embeddings are pre-trained).

I first instantiate the embeddings like so:

`embeddings = TransformerDocumentEmbeddings('microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext')`

Then I instantiate the BERTopic model:
```
topic_model = BERTopic(
    embedding_model=embeddings,
    min_topic_size=10,
    calculate_probabilities=True,
    verbose=True
)
```
I get this warning:
```
Some weights of the model checkpoint at microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
```
Then I run fit_transform, which takes about 4 hours on my old 16-core server:
```
49287it [3:46:34,  3.63it/s]
2021-05-25 03:37:57,692 - BERTopic - Transformed documents to Embeddings
2021-05-25 03:38:34,930 - BERTopic - Reduced dimensionality with UMAP
2021-05-25 03:48:41,512 - BERTopic - Clustered UMAP embeddings with HDBSCAN
```
I am a little perplexed by the long wall time during the first step. Since the embeddings are pre-trained, I would expect the transofmation to be fast. Am I doing everything correctly?

Thanks, and thank you for developing such an amazing library!

**Comment by MaartenGr** [comment]
Thank you for the kind words!

There are actually quite a few reasons why that step might be slow for you. 

First, most embedding/transformer models need a GPU in order to be performant. Using only a CPU will significantly slow down the inference even if it is a pre-trained model. 

Second, extracting embeddings for large documents can be quite difficult for specific models as some have token limits. I am not familiar with the model you are using but that might be something to look out for. 

Third, setting `calculate_probabilities=True` can significantly slow down the application. It is a bug in HDBSCAN where large data can slow down the inference as huge matrices might be calculated/created when constructing the probabilities. 

If you are not using a GPU, I would highly advise using one since they are almost necessary for most transformer-based models.

**Comment by sokol11** [comment]
Hey. Thanks so much for your reply. That makes total sense. Unfortunately, GPUs are really hard to get now but I will try something like Google Colab, I'm sure it will make a difference.
