### ISSUE TITLE
Fine Tune Representation Models: not returning representations

### ISSUE THREAD

**Issue by junebug-junie** [MaartenGr/BERTopic#1314]
Awesome new features! 

Running on the latest 0.14.1... two issues:
1) I only get the following columns in the output from `topic_model.get_topic_info()`: [Topic, Count, Name]
2) why can't I use fit_transform(docs, embeddings)?

```
# issue 1:
from bertopic.representation import KeyBERTInspired
from bertopic import BERTopic

# Create your representation model
representation_model = KeyBERTInspired()

# Use the representation model in BERTopic on top of the default pipeline
topic_model = BERTopic(representation_model=representation_model)
topic_model.fit(docs)

topic_model.get_topic_info()

# issue 2:
# Create your representation model
representation_model = KeyBERTInspired()

# Use the representation model in BERTopic on top of the default pipeline
topic_model = BERTopic(representation_model=representation_model)
topic_model.fit_transform(docs, embeddings)
```

Output issue 2:
`AttributeError: 'NoneType' object has no attribute 'embed_documents'
`

**Comment by MaartenGr** [comment]
Thanks for the kind words!

To start with the new features, you will need v0.15 instead of v0.14.1. Also, if you are using the following:

```python
representation_model = KeyBERTInspired()
```

then the main representation will be overwritten. If you want to use multi-aspect BERTopic, then you will have to use it as follows:

```python
representation_model = {
   "KeyBERT_Aspect": KeyBERTInspired()
}
```

Lastly, if you pass it custom embeddings with KeyBERTInspired without specifying the embedding model, then it will not work since it also needs to embed the words. So additionally setting `embedding_model` should fix your issue.
