### ISSUE TITLE
High number of documents gets the -1 label from HDBSCAN

### ISSUE THREAD

**Issue by sokol11** [MaartenGr/BERTopic#132]
Hi. I noticed that about 45% of my documents (~50'000 docs total) are marked as noise `-1` by HDBSCAN.

I tried reducing the `min_topic_size` and `min_samples`, which marginally improved things, while also increasing the number of extracted topics from about 450 to the 750 - 850 range. Unfortunately, the improvement was only marginal going from ~23-24k of `-1`-labeled docs to ~19-20k.

Anything else I can try to improve clustering with HDBSCAN? Should I try other embedding models, or stacking embeddings? Should I fiddle with UMAP settings, or try another clustering algorithm? Any advice would be highly appreciated.

Thanks you!

**Comment by sokol11** [comment]
As a follow-up to this, I have several kinds of text features for my docs. For each doc, I have the article title, abstract, and a set of keywords. Currently, I embed them separately and then average the resulting embeddings, before feeding the average to UMAP and HDBSCAN. Is there another way, I could be utilizing these features better? For example, does concatenating the three feature types and embedding once make more sense? Thank you.

**Comment by MaartenGr** [comment]
> Hi. I noticed that about 45% of my documents (~50'000 docs total) are marked as noise `-1` by HDBSCAN.
> 
> I tried reducing the `min_topic_size` and `min_samples`, which marginally improved things, while also increasing the number of extracted topics from about 450 to the 750 - 850 range. Unfortunately, the improvement was only marginal going from ~23-24k of `-1`-labeled docs to ~19-20k.
> 
> Anything else I can try to improve clustering with HDBSCAN? Should I try other embedding models, or stacking embeddings? Should I fiddle with UMAP settings, or try another clustering algorithm? Any advice would be highly appreciated.
> 
> Thanks you!

The HDBSCAN documentation has something about generating too many outliers [here](https://hdbscan.readthedocs.io/en/latest/faq.html#q-most-of-data-is-classified-as-noise-why). However, that already states fiddling around with `min_samples` to reduce the number of outliers you get. In practice, your documents may simply contain many outliers and HDBSCAN is merely detecting them. Therefore, reducing the number may actually not be possible as that incorrectly put them into clusters they do not belong. 

> As a follow-up to this, I have several kinds of text features for my docs. For each doc, I have the article title, abstract, and a set of keywords. Currently, I embed them separately and then average the resulting embeddings, before feeding the average to UMAP and HDBSCAN. Is there another way, I could be utilizing these features better? For example, does concatenating the three feature types and embedding once make more sense? Thank you.

This would highly depend on the use case. How important are the title, abstract, and keywords to the document? It seems you are now suggesting that they, including the document itself, are of equal importance since you are doing an equal-weighted averaging on the resulting embeddings. In practice, you might believe that the abstract is more important than the title and perhaps should be given more weight. 

Moreover, if the documents themselves are too large for the embedding model you are using, then it might make sense to use derivatives of the documents, such as the title, abstract, and keywords. However, if the documents fit within the token limit then the documents themselves should be enough. Similarly, using keywords can be troublesome if you are using a context-based model such as BERT which thrives when it has context to create embeddings. 

Thus, there is no single answer to your question as the context of your use case is so important in deciding what to use when.

**Comment by sokol11** [comment]
Thank you. This is helpful. I ended up reducing the number of outliers by switching to another embedding model.

**Comment by JoshuaE1** [comment]
Hi @sokol11 would you mind sharing which model you used? I'm applying BERTopic to a similar use-case (scientific abstracts) and facing a similar problem. Thanks in advance!
