### ISSUE TITLE
Please explain the difference in results in workflows decribed below.

### ISSUE THREAD

**Issue by piotrcelinski** [MaartenGr/BERTopic#1330]
Hi,
The first workflow:
```
self.topics, self.probs = self.topic_model.fit_transform(self.corpus)  # nr_topics='auto'
self.topic_model.reduce_topics(self.corpus, nr_topics=30)
```
The results of this worflow are in the worksheet:
[ria_ru_keybert_mmr_pos_orig_topics_reduced_30.xlsx](https://github.com/MaartenGr/BERTopic/files/11709313/ria_ru_keybert_mmr_pos_orig_topics_reduced_30.xlsx)

The second workflow:
`self.topics, self.probs = self.topic_model.fit_transform(self.corpus)  # nr_topics=30`
The results of this wokflow are in the worksheet:
[ria_ru_keybert_mmr_pos_orig_base.xlsx](https://github.com/MaartenGr/BERTopic/files/11709320/ria_ru_keybert_mmr_pos_orig_base.xlsx)

What is the reason of differences? Which workflow gives more trustworthy results?
Bests
Piotr

**Comment by MaartenGr** [comment]
Well, you are reducing the topics to 30 on two different sets of topics since you reduced the first set automatically by setting `nr_topics="auto"`. In other words, in the first workflow you are reducing twice whilst in the second you are reducing one. It might be worthwhile to check the documentation (and docstrings!) to see how they work. That will give you some understanding what suits your use case best. 

Personally, I would advise using `min_topic_size` instead to get the number of topics that you are interested in. That process adjusts the number of topics at the source.

**Comment by piotrcelinski** [comment]
Thank you
