### ISSUE TITLE
Adjusting temperature in OpenAI backend

### ISSUE THREAD

**Issue by siddu1998** [MaartenGr/BERTopic#1346]
First, Thank you so much for this library; it is amazing. 

I have been using the OpenAI backend as my representational model. I had a few questions:

- I understand the default algorithm calculates the representation documents based on the most representative words (vague explanation). In my case, I have a data frame with Reddit posts and upvotes for each post, I was curious if I could pick the posts with the most upvotes as my representative documents.
- Since I plan to publish my results, I was keen on the reproducibility of the representation model. Could I set the temperature of the OpenAI backend to 0.0, so people with the same code can get the same run? I sometimes do get different labels for the clusters on multiple runs. (I was referring to: https://github.com/MaartenGr/BERTopic/blob/fca5a4f9df149609c7e3458d6b2c421194cea62c/bertopic/backend/_openai.py#L9)

**Comment by MaartenGr** [comment]
> I understand the default algorithm calculates the representation documents based on the most representative words (vague explanation). In my case, I have a data frame with Reddit posts and upvotes for each post, I was curious if I could pick the posts with the most upvotes as my representative documents.

That is currently not possible since the topics are created based on semantic similarity of each document. If you pick the upvotes as the most representative documents, which can definitely be a reasonable assertion, then you do run the risk of the document actually not being that representative of the cluster. Having said that, you can manually extract them using `get_document_info` with your dataframe and sorting by upvotes. 

> I understand the default algorithm calculates the representation documents based on the most representative words (vague explanation). In my case, I have a data frame with Reddit posts and upvotes for each post, I was curious if I could pick the posts with the most upvotes as my representative documents.

> ince I plan to publish my results, I was keen on the reproducibility of the representation model. Could I set the temperature of the OpenAI backend to 0.0, so people with the same code can get the same run? I sometimes do get different labels for the clusters on multiple runs. (I was referring to:

Are you sure that the stochastic results are not part of UMAP? I am referring to [this FAQ page](https://maartengr.github.io/BERTopic/faq.html#why-are-the-results-not-consistent-between-runs). Also, do you mean the backend or the representation model? I am actually not sure whether the embedding model of OpenAI has a temperature parameter since that is not common with embedding models but with generative models.

**Comment by siddu1998** [comment]
Thanks for the clarification. The get_document_info does the job for me.
