### ISSUE TITLE
BERTopic.load produces HuggingFace error

### ISSUE THREAD

**Issue by jburdo1** [MaartenGr/BERTopic#1374]
Hi Maarten, I am working in AWS Sagemaker Studio, PyTorch 2.0.0, Python 3.10 GPU, bertopic==0.15.0. After saving my topic model using 

`topic_model.save('RP_topic_modeling_pipeline/rp-datastore/topic_model_bin_files/rp_qrc_6_23_23_model_merged_topics.bin')`

 I tried to load it using 

`qrc_model = BERTopic.load('RP_topic_modeling_pipeline/rp-datastore/topic_model_bin_files/rp_qrc_6_23_23_model_merged_topics.bin')`

and am getting the following error: 

HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 
'RP_topic_modeling_pipeline/rp-datastore/topic_model_bin_files/rp_qrc_6_23_23_model_merged_topics.bin'. Use 
`repo_type` argument if needed.

It almost looks like it's asking for just the folder name and not the saved model file; I've also tried that (making sure that only one .bin file was in the folder), but I get the same error. 

Any help would be appreciated. I've managed to save and load models before in Sagemaker when using an older version of BERTopic, so I don't know if something has changed with 0.15.0.  

Cheers,

Joe

**Comment by MaartenGr** [comment]
When you do this:

```python
topic_model.save('RP_topic_modeling_pipeline/rp-datastore/topic_model_bin_files/rp_qrc_6_23_23_model_merged_topics.bin')
```

The model is saved as `.pickle` and not a pytorch bin. If you would like to use a pytorch bin file you would have to save it as follows:

```python
topic_model.save('RP_topic_modeling_pipeline/rp-datastore/topic_model_bin_files/rp_qrc_6_23_23_model_merged_topics', serialization="pytorch")
```

Note that `rp_qrc_6_23_23_model_merged_topics` is a folder and not a file since several configuration files are needed on top of the `.bin` file. For more information, I would advise reading through the documentation [here](https://maartengr.github.io/BERTopic/getting_started/serialization/serialization.html).
