### ISSUE TITLE
Error in the new environment.

### ISSUE THREAD

**Issue by GesiIvy128** [MaartenGr/BERTopic#1400]
<img width="699" alt="111" src="https://github.com/MaartenGr/BERTopic/assets/16591673/cd810f74-58fd-4026-91bb-56fd393ce097">

I have found that the issue is caused by a mismatch in the environments between the one in which the model was trained and the one in which it is currently being loaded. However, since the previous machine is no longer available, it is difficult to determine the exact environment that was used for training.

------
Is there any way to export the information of the previous training environment?

**Comment by MaartenGr** [comment]
That is unfortunately not possible unless your version controlled your environment. Since the model was pickled, you would need to load it in first before being able to see what BERTopic's version was. It might help to check the date of the saved file and see which version of BERTopic was most current during that time. 

In the future, it should be easier to track with the release of BERTopic v0.15 since safetensors also saves part of the environment and versions.
