### ISSUE TITLE
Look-ahead bias in topics_over_time?

### ISSUE THREAD

**Issue by sokol11** [MaartenGr/BERTopic#142]
Hi. When mousing over points on the topics_over_time graph to visualize topic evolution, I noticed that for the "covid 19 / influenza" topic "covid 19" appears in pre-pandemic years, e.g., 2016. Is this expected behavior? Intuitively, I would think that having such look-ahead bias defeats the main use case for visualizing topic evolution. Or am I misunderstanding the intended use case here? Thank you!

**Comment by sokol11** [comment]
I should also mention that used nr_topics='auto' in the model, so maybe it is an artifact of topic reduction?

**Comment by MaartenGr** [comment]
Yes, this is expected behaviour! There are two reasons for this happening, namely the parameters `global_tuning` and `evolution_tuning` in `model.topics_over_time()`. They both relate to additional processing of the c-TF-IDF representations and are turned on by default. 

Global tuning averages the global topic representation with the local representation to create better topics when little documents are available. Thus, it can contain words from other timesteps. 

Evolution tuning averages c-TF-IDF representations between *t* and *t-1*. Thus, *t* can contain words from *t-1*. 

You can find more about that [here](https://maartengr.github.io/BERTopic/tutorial/topicsovertime/topicsovertime.html).

**Comment by sokol11** [comment]
Understood, thank you so much!
