### ISSUE TITLE
Transform on pre-computed embedding

### ISSUE THREAD

**Issue by guymorlan** [MaartenGr/BERTopic#1456]
Hi,

Thanks for your great work on this awesome package!

In my use case I have a custom embedder (FastText with TF-IDF weighting), and therefore I'm pre-computing the embeddings. After training the model, I would like to transform/predict on new documents. I have generated the embeddings for them, but it seems that the `transform` method, unlike `fit_transform`, does not directly accept embeddings. How can this be achieved? Do I need to make an embedder class compatible with BERTopic and pass that on to the model, instead of pre-computing the embeddings? Any ideas or pointers will be appreciated.

Thanks!

**Comment by MaartenGr** [comment]
You can actually use `embeddings` in the `.transform` method: 

https://github.com/MaartenGr/BERTopic/blob/37064e231defceb998ef2a778cef46fc769dbf00/bertopic/_bertopic.py#L426-L429

**Comment by guymorlan** [comment]
That's great, I'm unsure how I missed that!

By the way, is it possible to reduce outliers on the new documents, too?

**Comment by MaartenGr** [comment]
Yes, since you can pass both the documents and topics that should be possible. Do note though that you will also have to pass the probabilities/embeddings of the documents if you choose to use one of those strategies. You can find more about it [here](https://maartengr.github.io/BERTopic/api/bertopic.html#bertopic._bertopic.BERTopic.reduce_outliers) and [here](https://maartengr.github.io/BERTopic/getting_started/outlier_reduction/outlier_reduction.html) in the documentation.

**Comment by guymorlan** [comment]
Awesome, thank you!
