### ISSUE TITLE
Strange Clustering

### ISSUE THREAD

**Issue by firmai** [MaartenGr/BERTopic#147]
Hi there, is it normal to see this type of clustering, I have run this mulitple times and keep seeing this behaviour:

![image](https://user-images.githubusercontent.com/26666267/122344405-ab12f380-cf3e-11eb-8d89-dd2125e18994.png)

**Comment by MaartenGr** [comment]
This can definitely happen! The width of the dots can make it seem a bit strange since it allows the points to overlap to a certain degree. If you were to imagine the dots being small, the visualization would suddenly seem a bit different. But just to be sure, what exactly makes this clustering strange to you? 

Second, you do not have many topics generated. Generating more topics will most likely lead to a better representation of the topics in the data. There are several ways to increase the number of topics. You can lower `min_topic_size` when instantiating BERTopic or you can simply increase the number of documents you pass to the model. I typically aim for at least 50 topics to be created.

**Comment by firmai** [comment]
That makes sense, thanks for the answer. :)
