### ISSUE TITLE
Synonyms

### ISSUE THREAD

**Issue by firmai** [MaartenGr/BERTopic#148]
Hi  -- thanks again for the package, and your quick replies, I am sure the community of users appreciate it alot. To the questions: how can we go about finding synonyms for phrases/words, is that a functionality you have, know how to implement, or plan on implementing in the near future?

**Comment by MaartenGr** [comment]
No problem! But you are a bit in luck since today is my day off 😄

Finding synonyms for phrases and words is something that does not fit directly in the use case of topic modeling. One of the reasons is that although words may be very similar to each other, they both do not have to equally represent a topic. With BERTopic, I think it is important only to show words that actually were in the topic's documents. 

Having said that, if you want to find similar phrases/words, I would advise you to use the embedding model in BERTopic on the vocabulary of all documents and compare them with each other using cosine similarity. Then, you can extract similar keywords/keyphrases. 

Coincidentally, I developed a package for finding synonyms named [PolyFuzz](https://github.com/MaartenGr/PolyFuzz). It allows you to find words that are similar to each other if you use the same embedder as you used in BERTopic.
