### ISSUE TITLE
Clarify max number of tokens for BERT model

### ISSUE THREAD

**Issue by zilch42** [MaartenGr/BERTopic#1486]
Hi Maarten,

I just wanted to double check the maximum number of WordPiece tokens that the standard sentence transformer model can handle? In a number of issues you have mentioned 512 which is what I understood it to be, but I've just noticed that the hugging face documentation for the model says "By default, input text longer than 256 word pieces is truncated."
[https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2)

and the following code also returns 256.

```
from sentence_transformers import SentenceTransformer

sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
sentence_model.get_max_seq_length()
```

Can you confirm?

**Comment by MaartenGr** [comment]
If the sentence model itself says 256 then that is the number of word pieces it was trained on. You could manually override the maximum sequence length to make it a bit longer but that is generally not recommended.

**Comment by zilch42** [comment]
Ok, so the 256 is just about training but embedding documents up too 512 tokens with the model is fine? Thank you

**Comment by MarkWClements** [comment]
@MaartenGr I just wanted to confirm this/follow up on @zilch42 's question. 

I want to recover document embeddings using BERT for the use case of document similarity. And in this case, my understanding is that I need to use the SBERT model, rather than the BERT model, since the embedded document vectors from the SBERT model allow for cosine similarity comparisons and the BERT model does not (is this correct?). 

However, the documents I am wanting to embed are much longer than the context window for the SBERT (and BERT) models so I am splitting them into chunks and then averaging all the sub-document vectors to recover one document vector. In order to do this I want to create chunks that are just smaller than the maximum context window for the model I am using to recover the embeddings. For example:

```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(my_text_list)
```

where `my_text_list` is a list of all the documents that have been appropriately chunked to take advantage of the maximum context window when recovering the embeddings. I have two questions:

1) I assume I should use the context window of 256 for the SBERT model rather than the 512 context window for BERT to recover the document embeddings by making sure than no document in `my_text_list` is longer than 256 word pieces (or 512 word pieces if I should be using the BERT model's context window for this).

2) How do I recover the number of word pieces according to the SBERT model for a given piece of text, for example `ex_text = my_text_list[0]`, because the number of word peices in `ex_text` will be longer than simply just counting the number of words in `ex_text`?

I know this is marked as closed but I would really appreciate some guidance here.

Thank You!

**Comment by MarkWClements** [comment]
@MaartenGr Thank you so much for your prompt response. I would like to take these document vectors (created by averaging the chunked SBERT embeddings up to the document level), then extract Topics from this vector space using BERTopic (or Top2Vec?). What is the proper way to do this?

**Comment by MarkWClements** [comment]
@MaartenGr Thank you for the quick response. In my use case, I was planning on chunking the documents, embedding these chunks according to a particular SBERT model, then passing those embeddings to BERTopic. The thought is that I could then figure out an appropriate scoring method to recover topics associated with each document. Each document would have a distribution of topics associated with it (e.g. just choose the topic vector with the highest similarity score to each chunk in the document). This seems to be the best way to go about this without losing information by passing the document vectors directly to BERTopic since, as you point out, averaging will lose a lot of information.

Thant being said, is it as simple as passing an ndarray of the chunked embedding vectors to the model? When I have used Top2Vec in the past it seems like I only passed it list-like objects of strings. Can it take a numeric vector embedding as a starting input?

**Comment by zilch42** [comment]
Yes, `fit_transform` takes an ndarray as the `embeddings` input. You just have to keep track of which chunks belong to which original documents (assuming that's still important to you). 

Just to chime in here, I'm taking the 'chunk, embed, then average the embeddings' approach, and I'm using a weighted average to weight the chunks based on how many sentences are in each chunk, so that for example, I don't give equal weight to the last sentence of a reasonably long document, which would dilute the good information in the first chunk.

**Comment by MaartenGr** [comment]
@MarkWClements There is also the possibility of calculating the topic distributions with [`.approximate_distribution`](https://maartengr.github.io/BERTopic/getting_started/distribution/distribution.html) that should give a nice distribution of the documents without needing to keep track of indices.
