### ISSUE TITLE
 Dynamic Topic Modeling，extract the probability of each word within each topic

### ISSUE THREAD

**Issue by genewlan** [MaartenGr/BERTopic#1491]
In Dynamic Topic Modeling, the code topics_over_time = topic_model.topics_over_time(docs, timestamps) yields the frequency distribution of each topic at different time points. In this case, if I want to further extract the probability of each word within each topic, how should I proceed?

**Comment by MaartenGr** [comment]
That is currently not possible since extracting the c-TF-IDF matrices for each split takes up quite a bit of memory. Having said that, you could adjust the procedure yourself to return the c-TF-IDF matrices or the probabilities for each split. I believe this was asked before, so a quick search in the issues might help you find specific code for doing this.

**Comment by genewlan** [comment]
Thanks a lot!
