### ISSUE TITLE
Question: what else is the embedding model used for?

### ISSUE THREAD

**Issue by zilch42** [MaartenGr/BERTopic#1523]
Hi Maarten,

I tried following this through in the code but I got a bit lost. 

I'm working towards a situation where the document embeddings will be precomputed and stored in a database so I'm wondering what else the embedding_model is used for? I know it's necessary for `find_topics` though I wonder if that could accept an embedding directly instead of a string if e.g. the embedding model was available as an API rather than available locally to BERTopic? 

It also looks like it is used to calculate topic embeddings, but I thought topic embeddings were just the average of the document embeddings in a topic...? 

Ultimately I'm wondering if the embedding model is still necessary once the document embeddings have been calculated and provided? Especially if the embedding model is quite large. 

Thanks, as always

**Comment by MaartenGr** [comment]
It depends. The embedding model can be used for a number of things:
* To embed words when using `KeyBERTInspried`
* Reducing outliers if no embeddings are given
* To embed token(sets) when using `.approximate_distribution`
* I believe it is also used to embed words to create topic embeddings when using `.partial_fit`
* During `.transform` if you do not pass embeddings
* `find_topics` indeed also
* During guided topic modeling to convert seed topics to embeddings

There might be more but I think those are the most important ones. 

So it depends on your use case. If you are not doing any of the above after training, then the embedding model might not be necessary anymore. When you save BERTopic with `safetensors`, you can skip loading the embedding model when you load the trained BERTopic model. So that might be an option for you.

**Comment by zilch42** [comment]
Thanks Maarten, that's a really helpful list. KeyBERTInspried is the one I'm currently doing that I didn't realize was using the embedding model. 

Thanks again
