### ISSUE TITLE
Bertopic on Arch Linux

### ISSUE THREAD

**Issue by maximyurevich** [MaartenGr/BERTopic#1549]
I'm downgraded my cuda version to 9 on Arch Linux, but I have the following errors.

![Screenshot from 2023-09-28 10-53-07](https://github.com/MaartenGr/BERTopic/assets/21293376/bf4a6c38-e354-4fcd-ad6b-f8e01d466782)

![Screenshot from 2023-09-28 10-59-05](https://github.com/MaartenGr/BERTopic/assets/21293376/13b453ca-d058-450d-b43a-4a5232e8f779)

**Comment by MaartenGr** [comment]
It does not seem to be related to BERTopic but to cuda itself. Could you share a bit more context? How did you get this error? How does it relate to BERTopic? What code are you trying to run? Which version of BERTopic do you have? etc.

**Comment by MaartenGr** [comment]
Yep, this seems to be unrelated to BERTopic and related to your cuda installation. It seems to be going wrong with sentence-transformers since that tries to load in torch-based code. I would advise starting from a fresh environment and doing a clean install of cuda-enabled torch/sentence-transformers. You could also do that after installing BERTopic since that might override your torch installation.

**Comment by MaartenGr** [comment]
If it makes no difference for your use case, I would use the cuda that is best supported by your system which is generally the latest version. Definitely follow along with the installation here: https://pytorch.org/
