### ISSUE TITLE
[QST] BERTopic as a general model?

### ISSUE THREAD

**Issue by bjpietrzak** [MaartenGr/BERTopic#1578]
## QUESTION:

I want to create a BERTopic model architecture that will be able to extract topics from any list of documents and still give reasonable results when fitted to said documents. Is it even possible? My modifications to the BERTopic pipeline didn't yield satisfying results.

## RATIONALE FOR THE QUESTION:

I'm planning to build a GUI for users to allow them to choose any application from the Google Play Store and display the main issues (topics extracted from app reviews) that users identify in a given app.

That's why I want to create a one-size-fits-all BERTopic model to enable seamless transitions between different apps. Naturally, the model will need to be trained on the app's reviews, and the training speed will depend solely on the hardware the model runs on.

**Comment by MaartenGr** [comment]
> I want to create a BERTopic model architecture that will be able to extract topics from any list of documents and still give reasonable results when fitted to said documents. Is it even possible? My modifications to the BERTopic pipeline didn't yield satisfying results.

Could you go a bit more in-depth into what the issue is? It is not clear from your description what the main problem is that you are facing. Are you not happy with the output? If so, why? Is it an issue with the keywords? Have you tried following the [best practices guide](https://maartengr.github.io/BERTopic/getting_started/best_practices/best_practices.html)? 

Make sure to be as complete as possible.

**Comment by MaartenGr** [comment]
The difficulty with the clustering algorithm is that it is not possible to have a one-size-fits-all solution since the quality of the clusters (for example the number of clusters), is quite subjective. To illustrate, the number of topics that were found on your Instagram might be too few for you but might be the perfect amount for someone else. The depth/broadness/specificness of topics is also something that, to a large extent, depends on the use case and the perspective of the user. 

This also relates to the input data. Just because the number of documents is the same between the two runs, the distribution of embeddings that were created as a result of them is unlikely to be similar. Therefore, additional tuning of the clustering algorithm with respect to the input data is necessary. 

If your problem is purely the number of topics created, then it is also possible to approach this a bit differently. By setting a very small `min_topic_size` you are likely to generate more micro-clusters. For many, this can be a disadvantage. However, it would allow you to start with a large number of topics that you can automatically aggregate to a specified number of topics afterward.

You can do this within BERTopic or you can create a custom technique yourself. For example, merge topics until you have fewer than 50 topics, after that only merge topics if they are very similar to one another. 

All in all, I think it is also a matter of diving into the clustering algorithm and what you can expect from these kinds of algorithms. For example, the number of clusters in the second example might increase if you lower `min_topic_size`. Just because you have the same number of documents does not mean they contain the same amount of topics and that is something for you to account for.

**Comment by bjpietrzak** [comment]
> All in all, I think it is also a matter of diving into the clustering algorithm and what you can expect from these kinds of algorithms.

Okay, I'll look into it. Thank you
