### ISSUE TITLE
Document map provided 

### ISSUE THREAD

**Issue by randomrdrand** [MaartenGr/BERTopic#159]
Dear community,

I really appreciate your help MaartenGr, I find the library very useful. I saw in the comments a really nice map that you wrote but I'm wondering if the dots are documents or topics? I think that the dots are documents and the colored zones represent a topic. Also the topics need some spacing in the figure could anyone please help me? here is the figure:

![image](https://user-images.githubusercontent.com/86354872/123426349-9a5c2080-d5c3-11eb-8616-f6965754f410.png)

the code:
       
      # Visualize outliers + inliers
      fig, ax = plt.subplots(figsize=(15, 15))
      scatter_outliers = ax.scatter(outliers['x'], outliers['y'], c="#E0E0E0", s=1, alpha=.3)
      scatter = ax.scatter(non_outliers['x'], non_outliers['y'], c=non_outliers['topic'], s=1, alpha=.3, cmap=cmap)

      # Add topic names to clusters
      centroids = to_plot.groupby("topic").mean().reset_index().iloc[1:]
      for row in centroids.iterrows():
              topic = int(row[1].topic)
              text = f"{topic}: " + "_".join([x[0] for x in topic_model.get_topic(topic)[:3]])
              ax.text(row[1].x, row[1].y*1.05, s=text, fontsize=10, horizontalalignment='center', verticalalignment='bottom')
    
       ax.text(0.9, 0.1, f"BERTopic - Top {top_n} topics", transform=ax.transAxes, horizontalalignment="right", color="black")
       plt.xticks([], [])
       plt.yticks([], [])
       plt.show()

**Comment by MaartenGr** [comment]
The dots are individual documents and the colored clusters indeed represent the topics. The centroids were extracted in order to give the titles of the topics a location on the 2D visualization. Some topics will have very similar centroids which result in overlapping titles. However, you can adjust this `ax.text(row[1].x, row[1].y*1.05` with different X and Y coordinates to make sure they are not overlapping. 

For example, in the variable `centroids` you can adjust the X and Y coordinates such that there is a minimal amount of space between them.
