### ISSUE TITLE
GPU utility issue

### ISSUE THREAD

**Issue by yana-xuyan** [MaartenGr/BERTopic#16]
Hello! When I tried to train the model using my local GPU, it shows that even though the code takes up some memory of the GPU, the GPU utility stays to be 0. Could you please give me some hints to solve this issue?

**Comment by MaartenGr** [comment]
BERTopic does not use the GPU at all times. There are essentially 4 steps of calculation:

1. Creating embeddings
2. Reducing embeddings with UMAP
3. Finding clusters with HDBSCAN
4. Extracting topic representations with c-TF-IDF

Only step 1 is actually using the GPU since the embeddings need to be created. Steps 2, 3, and 4 currently do not have a solid GPU-based implementation which is why they were not included. This might be why you are not seeing your local GPU being used, as there could be no need to use it. 

However, and this is from personal experience, GPU acceleration is less needed in steps 2, 3, and 4 and perhaps a bit of an overkill as these steps are already quite speedy. Typically, most of the computation/wall time seems to be in step 1.

**Comment by yana-xuyan** [comment]
Thank you for your reply. Regarding your reply to another issue, I updated the package to 0.3.2 version. When using 0.3.1 version, it takes around 3 hours to finish clustering my corpus, but when using the new version, it takes more than 15 hours and still not finished. Do you have any idea about it?

**Comment by yana-xuyan** [comment]
The log is as follows:
2020-11-16 20:06:58,104 - BERTopic - Loaded BERT model
INFO:BERTopic:Loaded BERT model
2020-11-16 20:16:34,675 - BERTopic - Transformed documents to Embeddings
INFO:BERTopic:Transformed documents to Embeddings
2020-11-16 20:20:16,818 - BERTopic - Reduced dimensionality with UMAP
INFO:BERTopic:Reduced dimensionality with UMAP
2020-11-16 20:38:05,494 - BERTopic - Clustered UMAP embeddings with HDBSCAN
INFO:BERTopic:Clustered UMAP embeddings with HDBSCAN

**Comment by MaartenGr** [comment]
It may be that the topic reduction is stuck in an infinite loop due to a possible edge case in the while loop. Although I am not sure what that case would be. Did you set `nr_topics`?

**Comment by yana-xuyan** [comment]
Yes, I did. My code is like: `model = BERTopic("bert-base-wikipedia-sections-mean-tokens", stop_words='english', verbose=True)`

**Comment by yana-xuyan** [comment]
Yes, I did. My code is like `model = BERTopic("bert-base-wikipedia-sections-mean-tokens", nr_topics=4, stop_words='english', verbose=True)`. The process got stucked when the number of the clusters is reduced to 223.

**Comment by MaartenGr** [comment]
It turned out you got stuck in an infinite loop since topics were trying to map to each other constantly. This is solved with additional checks and the option to automatically reduce topics instead of forcing them.

Below, we are forcing the reduction of topics by mapping them to each other: 

```python
model= BERTopic(verbose=True, nr_topics=31)
topics, probs = model.fit_transform(docs, embeddings)
```

However, this can result in poor quality topics as some topics are mapped to one another whilst not being similar. Instead, you can set nr_topics to auto and only map topics that have a similarity of at least .915:

```python
model = BERTopic(verbose=True, nr_topics="auto")
topics, probs = model.fit_transform(docs, embeddings)
```

**Comment by MaartenGr** [comment]
Hopefully, this should have fixed your issue. Make sure to update to the newest PyPi version (0.3.3).

**Comment by yana-xuyan** [comment]
Thank you soooo much for your quick reply!

**Comment by MaartenGr** [comment]
No problem, after having run something for 15 hours and getting stuck in an infinite loop you kinda deserved a fast response :sweat_smile:. Let me know if you run into any other issues or if the updated version did not work out!
