### ISSUE TITLE
How to include the outlier -1 in topic_model.visualize_topics()?

### ISSUE THREAD

**Issue by abhijithneilabraham** [MaartenGr/BERTopic#160]
I noticed that in certain docs, the outlier topic with index -1 seems to be useful. I would like to see this one visualised with every plot, so how to enable this(optionally)?

**Comment by MaartenGr** [comment]
The outlier topic contains many outlier documents that have little to no relation with each other. This also means that the topic representation will make no sense and visualizing them can be very misleading. Moreover, from a technical perspective, there is little reason to actually construct a topic that contains all those outliers. For those reasons, I would actually advise you not to include the outlier topic in the visualizations!

**Comment by abhijithneilabraham** [comment]
Alright. But how to prevent a legitimate topic going into the outlier instead? Because that's the issue I am facing.

**Comment by abhijithneilabraham** [comment]
I had a certain discussion thread from reddit comments scraped into csv.  This was my output.
```
Topic	Count	Name
0	-1	1024	-1_climate_change_we_you
1	0	388	0_nuclear_power_energy_solar
2	1	355	1_explanations_explanation_experimentsstudys_e...
3	2	136	2_we_will_years_earth
4	3	84	3_vegan_meat_eat_diet
5	4	67	4_consensus_science_scientific_scientists
6	5	60	5_co2_atmosphere_heat_we
7	6	60	6_china_emissions_india_countries
8	7	54	7_comment_discussion_post_argue
9	8	43	8_recycling_plastic_plastics_recycle
10	9	40	9_change_climate_human_changes
11	10	38	10_2013_climate_2012_change
12	11	36	11_carbon_tax_price_cost
13	12	34	12_temperature_temperatures_ice_medieval
14	13	34	13_thank_thanks_good_analogies
15	14	33	14_models_climate_model_data
16	15	30	15_children_kids_parents_raising
17	16	29	16_socialism_democrats_socialist_republicans
18	17	28	17_fucking_ok_kettle_whoa
19	18	26	18_sun_solar_earth_irradiance
20	19	26	19_politicians_protests_leaders_pressure
21	20	23	20_change_climate_american_vineyards
22	21	21	21_species_invasive_plant_trees
23	22	20	22_car_electric_hybrid_drive
24	23	17	23_warming_warmer_co2_dinosaurs
25	24	17	24_pregnancy_women_insurance_abortions
26	25	17	25_change_climate_our_poverty
27	26	15	26_ice_caps_melting_water
28	27	15	27_change_climate_conversation_conversations
29	28	14	28_mortalities_zero_accident_magnitude
30	29	13	29_ice_planet_earth_melting
31	30	13	30_market_markets_cost_solutions
32	31	11	31_transit_transportation_infrastructure_cities
33	32	10	32_carbon_methane_ch4_co2
```

As you can see, climate change was pushed into the outlier, where it actually is a useful topic. While visualising, this outlier is ignored. Is there some way I can bypass this?

**Comment by MaartenGr** [comment]
The topic representations are created by calculating the c-TF-IDF matrix from a collection of documents that are related to one another. It tries to extract which words are important to that collection of documents. If you have a set of documents that are similar to each other, the representations will make sense since the documents can nicely be represented with a limited set of words. 

Outliers, however, work a bit differently. If you have a collection of documents that are not very similar to each other, extracting the best-representing words is quite difficult. Imagine hundreds of random documents thrown together, which words would then best represent those random documents? In practice, the topic representation will simply be poor as it is near impossible to create a topic representation from a collection of random documents. 

This means that the outlier class's representation will also be poor and that you cannot use that topic representation as an actual representation of what you find in those documents. In other words, it is very likely that your outlier class actually does not represent climate change.

**Comment by abhijithneilabraham** [comment]
Makes sense. Thanks for clarifying
