### ISSUE TITLE
Inquiry regarding Bertopic DTM topic names

### ISSUE THREAD

**Issue by irae14** [MaartenGr/BERTopic#1623]
Hello~!  I have trained Bertopic DTM on Arabic news data, and when checking the topic_info, I found that the topics were named in a format like
 -1_18750_50_pacific_giss
0_19_12_10_15
1_24_20_12_10
2_2017_2020_15_coinbase
3_13_11_10_21
4_champ_11_18_35
5_19_40_2020_pony
6_2018_nomads_ebrd_[email protected]
7____
8_656_153_900_
9_24_18_26_73582
10_squid_game_broadband_vans
11_jcia_5050_4175_18301903
12_fifa_hd_bein_alnassrfc
13_hd_alkasschannel_qatar_fifaworldcup
14_bmw_suv_hyundai_motor
15_2100_1700_1900_1800

I have noticed that the topic names are not determined in Arabic and I'm curious whether it prioritizes English and numbers for extraction. Also I would like to know the criteria for how topic names are determined. Thank you.

**Comment by MaartenGr** [comment]
That might be due to the underlying tokenizer and embedding model. Make sure you use an embedding model that is either multi-lingual or specific for Arabic, the same applies to the tokenizer. 

> Also I would like to know the criteria for how topic names are determined. 

The documentation is quite extensive, if I say so myself, and should answer most of your questions. You can start [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) with the basic algorithm, and [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html) and [here](https://maartengr.github.io/BERTopic/getting_started/vectorizers/vectorizers.html) for more information about tokenizers/embedding models respectively.

**Comment by irae14** [comment]
Thank you. The issue was due to not setting the embedding to Arabic, and it has been resolved when I configured it to Arabic. I greatly appreciate your help

**Comment by MaartenGr** [comment]
No problem! Glad I could help.
