### ISSUE TITLE
I don't clearly grasp what it's meant by saying that BERT is a pretrained model

### ISSUE THREAD

**Issue by randomrdrand** [MaartenGr/BERTopic#167]
I want to understand what does it mean by saying that BERT is a pretrained model. I understood that it was pretrained on a large set of documents but what does that mean? Does it mean that the model starts from the pretrained state instead of a random one?

**Comment by MaartenGr** [comment]
Good question! BERT by itself is simply an architecture of a model. It does not do much without having being trained on any data. Typically, these models require a significant amount of data in order to reach their amazing performance. We are often talking about billions of documents.

It is unfeasable for many organizations to have to train BERT constantly on that data. Instead, we can train BERT once and use that pre-trained state to fine-tune the model. In BERTopic's case, we are using pre-trained models that have been trained, typically, on similarity measures where we indeed use a pre-trained state. As mentioned before, BERT by itself does not do much and so we have to use models that you can use without any training necessary.

**Comment by randomrdrand** [comment]
Can you tell me more about the pretrained vocabulary size? how many tokens BERT was pretrained on? Also can you tell me the dimensions of the embeddings that BERT produces? which gets then reduced by UMAP?

I really appreciate your help! thanks for your time!

**Comment by MaartenGr** [comment]
That highly depends on the transformer model you actually use for training BERTopic. If you use the standard model (`paraphrase-MiniLM-L6-v2`), you can find more about that [here](https://www.sbert.net/docs/pretrained_models.html). In practice, the dimensions could differ between embedding models as is the same with tokens and vocabulary size.

**Comment by randomrdrand** [comment]
I'm using 'roberta-base-nli-stsb-mean-tokens'

**Comment by randomrdrand** [comment]
Thank you very much i found it!
