### ISSUE TITLE
Incremental learning using model merging

### ISSUE THREAD

**Issue by Neehier** [MaartenGr/BERTopic#1752]
Thank you for your work. I'm trying to implement incremental learning into my BERTopic model. I've opted for models that support `partial_fit()`, instead of the newly released `merge()` feature because of my slow incoming dataflow.

I'd much rather use the merging, as it allows me to be more flexible in model choice in regards to practically every layer of the model outside of the generation of embeddings and topic representation. However, my flow of incoming data is not large enough to fit a model frequently. This seems not to be as much of a problem when using `partial_fit()`, if the base model already has a strong fit.

Some workaround that may work is to fit the incoming data with a random sample of my existing data, large enough for a decent fit, after which I can just merge again with the base model. However, that would only work if duplicate documents do not impact topic size, which I think they would.

My question is whether `partial_fit()` is the best bet I have on incremental learning with a slow incoming dataflow, using BERTopic.

**Comment by MaartenGr** [comment]
I can imagine it also depends on whether those slow incoming dataflow need to be addressed quickly. If the data input is slow, I can imagine there is no need to address those datapoints quickly and you can wait a bit longer to create a new topic model. 

Having said that, if you need to act quickly on that data, you could also do something in-between. Instead of waiting until you have enough data, already predict the new instances and if too many do not fit within existing topics, then notify whoever needs to be notified. That moment would also be great for training and merging a new model.

**Comment by Neehier** [comment]
Thank you for the swift insights Maarten! Noted and solved.
