### ISSUE TITLE
Is there any way to make the BERTopic guided like guidedLDA?

### ISSUE THREAD

**Issue by farshi** [MaartenGr/BERTopic#178]
HDBSSCAN returns new labels each time when you train . For my case  , I would need to have same labels as I use these labels in the second stage in another application business logic, like  if topic_num == 1 then category is "soccer game" .   If later on I add more data and need to train the model again, I will get new labels then my logic will not work.

Guided BERTopic could be a solution for this , like

topic_0 : ['apple' , 'iphone' , 'apple company' ]
topic_1 : [ 'football team' , 'soccer' , .... ]

So guided BERTopic should label all documents  around the predefined keywords to that specific cluster.

Can you please give me an idea how this solution can be implemented ?

**Comment by MaartenGr** [comment]
Interesting use-case! Over the last weeks I have been thinking of developing a GuidedBERTopic but have not had the time to experiment with some ideas. 

There are two things that need to be seperated from your story:

First, I am thinking of some ideas of creating a Guided BERTopic but that would not necessarily mean you would always get the topics you think you should get. In practice, we can merely steer the model towards a direction if it makes sense. So if you would 
add small or non-existing topics, the quality of the model is likely to decrease significantly. 

Second, even if I implement a GuidedBERTopic I am quite sure it would be difficult to implement that the guided topics will have a set position. For example, if you want a specific topic to always be topic 1 then that might prove to be troublesome as many sub-topics might exist that can or should occupy that space. 

Thus, if there would exist a GuidedBERTopic, I would train it only once and not re-train it later on as that can change the distribution of topics and their content such that the business logic might not apply anymore. 

If that would be the case, so having a GuidedBERTopic without the option of adding data later on (due to restrictions in the business logic), would that be something still of interest?

**Comment by farshi** [comment]
That's great that you were thinking of this too! If we can not keep the topic numbers  then I think it would be another semi-supervised training ! does it make sense? the way I am  seeing it is like  you define a class and assign to some documents manually and by this you can alter the normal flow of clustering.  

Can you please let me know what definition of GuidedBERToipc you have in mind ? might I can help with some ideas.

**Comment by MaartenGr** [comment]
I had some time the last few days and implemented an idea that I have been working on [here](https://github.com/MaartenGr/BERTopic/pull/176). You can find the full explanation there but essentially I try to nudge the topics to the seeded topics by leveraging the supervised approach in UMAP and by increasing the IDF values when creating topic representations.

**Comment by YuanyuanLi96** [comment]
I have a similar use-case. We want to map the model generated topics into a set of predefined topics (the set is big enough to capture all possible topics). Right now, I just send every predefined keyword into `model.find_topics("keyword")` function, record the most related topic and similarity score. Then use the keyword which has highest similarity score as the label for each particular topic. Does this make sense? Look forward to using the Guided BERTopic to make this process easier!

**Comment by MaartenGr** [comment]
@YuanyuanLi96 Yes, this would be a nice way of approaching this. Even with a Guided BERTopic, there is no guarantee that a topic will receive the exact same ID. Searching for that topic through `find_topics("you can also specify multiple keywords")` would be a good solution. You could even write down the topic representation from a previous iteration and simply pass that through `find_topics` like this:

`model.find_topics("space launch orbit lunar")`

**Comment by MaartenGr** [comment]
@farshi @YuanyuanLi96 The new release of BERTopic ([v0.9](https://maartengr.github.io/BERTopic/changelog.html#version-09)) now includes Guided Topic Modeling! You can find a guide [here](https://maartengr.github.io/BERTopic/tutorial/guided/guided.html). If you run into any issues, please let me know!
