### ISSUE TITLE
Allow passing all keyword arguments of CountVectorizer to BERTopic constructor

### ISSUE THREAD

**Issue by oterrier** [MaartenGr/BERTopic#18]
Hi
I think it could be great if we can pass all existing keyword arguments of CountVectorizer to BERTopic and not only `n_gram_range` and `stop_words` as of today.
Some of them like `max_df`, `min_df`, `strip_accents` or even `tokenizer` can be of great help when finetuning a model.

It could be done by changing the signature of the `__init__` method from
```
    def __init__(self,
                 bert_model: str = 'distilbert-base-nli-mean-token``s',
                 top_n_words: int = 20,
                 nr_topics: int = None,
                 n_gram_range: Tuple[int, int] = (1, 1),
                 min_topic_size: int = 30,
                 n_neighbors: int = 15,
                 n_components: int = 5,
                 stop_words: Union[str, List[str]] = None,
                 verbose: bool = False)
```
to
```
    def __init__(self,
                 bert_model: str = 'distilbert-base-nli-mean-token``s',
                 top_n_words: int = 20,
                 nr_topics: int = None,
                 min_topic_size: int = 30,
                 n_neighbors: int = 15,
                 n_components: int = 5,
                 verbose: bool = False,
                 **kwargs)
```
Then storing the kwargs dictionary as a class attribute `self.kwargs`
And then in `_c_tf_idf`
```
count = CountVectorizer(**self.kwargs).fit(documents)
```
I can even provide a PR if you want

Thx again for this great package

Olivier Terrier
@kairntech

**Comment by MaartenGr** [comment]
Hi Olivier,

I agree that exposing some more arguments of CountVectorizer would be a nice feature to have. However, I want to prevent using keyword arguments as a solution for a few reasons:

First, I would like to explicitly name the parameters such that we can prevent type error issues, create more informed documentation, and generally improve its useability without the need for external documentation. 

Second, by using keyword arguments and passing them solely into CountVectorizer, I believe we are limiting the use of the keyword arguments to the CountVectorizer. There are many parameters for UMAP and HDBSCAN that are currently not exposed and perhaps could be in the future. Using keyword arguments for CountVectorizer would prevent that. 

Thirdly, the way you are approaching the kwargs is by passing them as a contained dictionary instead of updating the keywords of the class itself. This makes it less intuitive to understand which parameters you have set in the model. You would have to access the keywords by `model.kwargs` and looking through them instead of simply using, for example, `model.min_df`. You could prevent this by updating the internal class variables: `self.__dict__.update(**kwargs)`. 

Perhaps we could add a few parameters like the ones you listed before or give you the ability to pass your own CountVectorizer. That would give you full flexibility whilst preventing many of the issues mentioned above.

**Comment by oterrier** [comment]
Hi Maarteen
Thx for your quick answer
I fully understand your point about the keyword arguments.
As you suggest, maybe offering the possibility to pass our own Vectorizer would be the best way
+1 for this
Best regards
Olivier

**Comment by oterrier** [comment]
I can provide a PR doing that, let me know

Best
Olivier

**Comment by MaartenGr** [comment]
Sorry for the late response. It shouldn't be that much work, so I'll look into it today or this weekend!

**Comment by MaartenGr** [comment]
I have added the option to add a custom CountVectorizer. Please update to the newest pip version.
