### ISSUE TITLE
topic representation : how to change the topic representation of the input of the zeroshot representation model ?

### ISSUE THREAD

**Issue by Batchounet** [MaartenGr/BERTopic#1819]
Hi, 
I am using the representation model zeroshot classification. It is working fine, but it the zeroshot model takes the ctfidf topic representation as an input. It is also the fallback when no label are found by the zeroshot.  I would like to try other representation than ctfidf, such as KeyBERTInspired. How can I do that ?
Thanks for your work, you are great !

**Comment by Batchounet** [comment]
I add a further question : is it possible to return the cosine similarity, or other similarity indicator used, whith the zeroshot topic when it is chosen ?

**Comment by MaartenGr** [comment]
Thank you for your kind words!

> I am using the representation model zeroshot classification. It is working fine, but it the zeroshot model takes the ctfidf topic representation as an input. It is also the fallback when no label are found by the zeroshot. I would like to try other representation than ctfidf, such as KeyBERTInspired. How can I do that ?

You can use this by stacking representation model like is done [here](https://maartengr.github.io/BERTopic/getting_started/multiaspect/multiaspect.html) with `aspect_model2`. 

> I add a further question : is it possible to return the cosine similarity, or other similarity indicator used, whith the zeroshot topic when it is chosen ?

The actual values of similarity or not saved within the model. You could calculate them yourselves since it is nothing more than the cosine similarity between document and label embeddings.
