### ISSUE TITLE
[Possible BUG] Cannot swap away from GPU:0

### ISSUE THREAD

**Issue by CHesketh76** [MaartenGr/BERTopic#1857]
Hello,  I am using BERTopic on a GPU cluster which has multiple GPUs and many users using this cluster. GPU:0 is always full (less than 20mb of free space at anyone time) but all the other GPUs are basically unused. I am unable to use my trained BERTopic model in this GPU cluster because it appears BERTopic cannot switch away from the default GPU.

I could not find anyone with the same issue as me for this and I was wondering if anyone found a solution.

I have tried using this code but I get ```DeferredCudaCallError```
```python
os.environ['CUDA_DEVICE_ORDER'] = 'PCI_BUS_ID'
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
```

**Comment by MaartenGr** [comment]
The GPU can be used at different stages of BERTopic since each stage uses a different algorithm. For instance, multi-GPU is not supported out of the box but potentially could be with cuML. If you want to use a different GPU, and assuming you are using the default pipeline, you would have to instruct `sentence-transformers` to use a different GPU.

**Comment by CHesketh76** [comment]
@MaartenGr Thank you! I believe that resolved my issue.

For others with similar issue. Do not save the model as pickled object, use safetensors or the torch options. This allows you to control the components of what is being loaded in. Code below for reference.
```python
embed_model = SentenceTransformer('path/to/model/', device='cuda:2')
```
