### ISSUE TITLE
CohereAPIError

### ISSUE THREAD

**Issue by jayita13** [MaartenGr/BERTopic#1864]
CohereAPIError: model 'xlarge' not found, make sure the correct model ID was used and that you have access to the model.
class Cohere(
    client: Any,
    model: str = "xlarge",
    prompt: str = None,
    delay_in_seconds: float = None,
    nr_docs: int = 4,
    diversity: float = None,
    doc_length: int = None,
    tokenizer: str | ((...) -> Any) = None
)

**Comment by MaartenGr** [comment]
What happens if you use `"command"`  instead of `"xlarge"`? I believe the latter might be outdated. Also, it seems that cohere has updated parts of their API. So using `co.chat` seems to be the alternative to `co.generate` as mentioned [here](https://docs.cohere.com/docs/migrating-from-cogenerate-to-cochat).

**Comment by MaartenGr** [comment]
What exactly do you mean? Did the suggestions I made work for you?

**Comment by jayita13** [comment]
Yeah it resolved the api call error. But since I'm using cohere free tier the api calls are limited to 5 per minute and hence wasn't able to get through it.
