### ISSUE TITLE
HDBSCAN taking a long time with many (30k) small documents

### ISSUE THREAD

**Issue by d4buss** [MaartenGr/BERTopic#188]
Hello, thanks so much for the excellent library. I have learned a lot using it.

I currently have a dataset of around 30,000 smaller documents. Each document is a sentence or two. 

I've run `topic_model = BERTopic(language="english", calculate_probabilities=True, verbose=True)` and the subsequent `fit_transform` on this dataset and the HDBSCAN clustering did not complete even after >50 mins. (Tried multiple times just in case).

I saw in some other issues it was mentioned that having `calculate_probabilities=False` can help if the dataset is bigger. I did try this and it finished in around 4 mins. Is this dataset likely big enough to cause that slowness with the probabilities on? It seems to handle the `20newsgroups` dataset just fine and that's almost 20k documents. 

Could it be that smaller documents would cause a problem in anyone's experience? Would be nice to use the topic probabilities with this kind of dataset. Thanks.

**Comment by MaartenGr** [comment]
This is a known issue with `HDBSCAN` and unfortunately there isn't a known fix for this. It should not be an issue with the dataset size since 30,000 documents isn't all that big. Like you said, it shows no issues on 20Newsgroups. 

Quick question though, would it be sufficient to have the probability of a single class instead? For example, it not only gives back a list of topics but also a list of probabilities for that specific class. That would prevent the issue with calculating probabilities for all classes since a very large matrix needs to be created.

**Comment by d4buss** [comment]
Hey Maarten, yes I believe that would help. How would I obtain the probability of that single class?

**Comment by MaartenGr** [comment]
If you install [this](https://github.com/MaartenGr/BERTopic/pull/176) pull request and you set `calculate_probabilities` to False (which it is by default) then it will only give you back the probabilities of a single class instead of the probabilities across all classes.

**Comment by d4buss** [comment]
Gotcha, thanks will try that.
