### ISSUE TITLE
Bug with zeroshot_min_similarity parameter? 

### ISSUE THREAD

**Issue by newlandj** [MaartenGr/BERTopic#1881]
I just ran some code that worked a few days ago, and now I'm getting the error: TypeError: BERTopic.__init__() got an unexpected keyword argument 'zeroshot_min_similarity'

You can replicate this by trying to instantiate a new BERTopic object with `topic_model_ = BERTopic(zeroshot_min_similarity=0.7)`

Did something change recently that removed this parameter from the init?

**Comment by newlandj** [comment]
Also, I'm not actually calling that parameter, but it's being called somewhere when I try to load a topic model from a safe tensor format using: self.model = BERTopic.load(tensor_directory_path)

**Comment by MaartenGr** [comment]
> You can replicate this by trying to instantiate a new BERTopic object with topic_model_ = BERTopic(zeroshot_min_similarity=0.7)

Replication is typically a bit more involved than running that line. For instance, if I were to run that line with an early version of BERTopic, like v0.10, then it will indeed give me that error since it was not implemented in that version. However, if I were to use that parameter in the most recent version, v0.16, it works without any problem. 

In other words, a bit more context is needed. Which version of BERTopic are you using? How did you install BERTopic? Was it from the main branch or did you use the pypi package or perhaps using conda? 

> Also, I'm not actually calling that parameter, but it's being called somewhere when I try to load a topic model from a safe tensor format using: model = BERTopic.load(tensor_directory_path)

Ah, in that case. Can you share your **full** code along with the **full** error message? It is not entirely clear to me how you are using BERTopic and what exactly you are running. Make sure to provide a complete example.

**Comment by newlandj** [comment]
Hi @MaartenGr , thanks for the reply, and I apologize for wasting your time on this one. Turns out I trained the model on version 0.16.0, but then was trying to run inference on a machine with 0.15.0. I thought they both had 0.16.0. 

After upgrading the inference machine to 0.16.0, all is working. Thanks for creating this amazing tool!

**Comment by MaartenGr** [comment]
@newlandj Thank you for your kind words! Glad the issue was resolved, let me know if you run into any other issues.
