### ISSUE TITLE
Add support for Python 3.10+

### ISSUE THREAD

**Issue by afuetterer** [MaartenGr/BERTopic#1950]
I tested `BERTopic` on my machine and in my fork using Python 3.12.

May I suggest adding 3.10, 3.11, 3.12 to `setup.py` and the GitHub actions CI job?

**Comment by MaartenGr** [comment]
Although BERTopic does not limit the user to a maximum version of Python (so that's already supported), there are indeed no tests available for those higher versions. So yes, adding them would be great! I believe there might be some specific issues on higher python versions with specific package versions but the tests cannot cover all these cases unfortunately.

**Comment by afuetterer** [comment]
Accidentally closed.

I will add a new PR then, about this in the upcoming days. As I said I tested with Python 3.12 and the tests were passing.
