### ISSUE TITLE
Guided BERTopic Modelling

### ISSUE THREAD

**Issue by goku2130** [MaartenGr/BERTopic#197]
@MaartenGr 

Hi Maarten, 

Thank you for such an amazing work on topic modelling with **BERTopic**. I have read its entire documentation. It is very clean and easy to understand. I am specifically interested to know more about the functionality of **seed_topic_list** in BERTopic. If I understand correctly, BERTopic tries to identify the specific topics (and beyond) based on the keywords given to it as seed list. For my use-case, I have a list of topic keywords and its associated class defined by the business users. Currently, on using **seed_topic_list** in BERTopic, I do not have a definite way of matching the topic classes defined in the seed list to the topics that are eventually generated as the order is not maintained. I can think of overcoming this challenge by computing a cross topic-level cosine similarity score between seed topic and generated topic to assign a topic label. Do you think that it is a good idea to use cosine similarity to get the classes assigned? Thank you once again!

**Comment by MaartenGr** [comment]
Yes, since many (sub-)topics can be created it is difficult to predict which topic relates to one of the seeded topics. This is further complicated when the seeded topics are actually not in the resulting topics. This can happen if the seeded topics are ill-defined. 

I would agree with your approach of using finding the most similar topics between the resulting topics and the seeded topics. However, it is still very much possible that one seeded topic will have several similar resulting topics. 

Also, it is technically possible that a seeded topic will not appear in the resulting topics. This means that the highest cosine similarity might not be high on an absolute-level.

**Comment by goku2130** [comment]
I will try to see if the results are good with the said approach. Thank you for the quick response!

**Comment by takiholadi** [comment]
Is it OK to use for the same purpose: `topic_model.find_topics('  '.join(seed_topic_list[42]), top_n=1)` ?

**Comment by MaartenGr** [comment]
Sure, that should be no problem!
