### ISSUE TITLE
Topics visualization over time only show ascending , descending and inflection plots only

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#214]
Hi,

How would you do to only show line plots that have an ascending , descending or have a single inflexion point (ascend , peak and then descend or the other way around).
Do you think this is even possible ?

Thank you !!!

**Comment by MaartenGr** [comment]
There indeed have been times in my work, and what I have heard from other users, that it would be nice to extract the lines that show behavior that is unlike most other lines/topics. 

I cannot answer this right away since it highly depends on the use case. For example, some might want to extract only ascending whereas others are interested in those that have a single peak. Having said that, I will be looking into this!

**Comment by doubianimehdi** [comment]
Thanks for your answer, if you have at least an idea on how it would be done, I could try it on my side and share with you !

**Comment by MaartenGr** [comment]
This is very very rough code but we can use it to find lines that behave differently from the norm:

```python
from sklearn.preprocessing import normalize
import numpy as np

# Convert the topics over time into a nicer format
df = topics_over_time.groupby(["Topic", "Timestamp"]).sum().reset_index()
df = df.pivot_table(index='Topic', columns='Timestamp', values="Frequency").reset_index()
df = df.loc[df.Topic != -1, :].set_index("Topic").fillna(0)

# Normalize the frequencies and add an average line
df = pd.DataFrame(normalize(df, axis=1))
df.loc[len(df), :] = df.values.mean(axis=0)

# Calculate distance matrix
distance_matrix = np.sqrt(((df.values[:,None,:] - df.values)**2).sum(axis=2))

# Extract the top n topics that differ most from the average
top_n = 10
interesting_topics = np.argsort(distance_matrix[-1])[-top_n:]
```

This is by no means perfect but it should do the trick when you want to find outliers.
