### ISSUE TITLE
Progress bar for fit_transform()

### ISSUE THREAD

**Issue by dingusagar** [MaartenGr/BERTopic#2224]
### Feature request

It would be nice to have a progress_bar or verbose flag for fit_transform(). We can have an optional flag show_progress=False. If set to true, it can show the progress.  

### Motivation

I am trying to process a lot of documents and I don't know how long it is going to take. 

### Your contribution

I can create a PR if this is something that's useful. Let me know.

**Comment by MaartenGr** [comment]
Thank you for the suggestion! There's already a tqdm bar integrated into the embedding step because that is an iterable and can tell you how long something will take. The same cannot be said for most other steps. For instance, if you have finished the embedding step, a progress bar wouldn't tell you how long each subsequent step will take. Keeping that in mind, what would you suggest the main benefit of a progress bar then be?

**Comment by dingusagar** [comment]
@MaartenGr thanks for the reply, sorry I think I missed the tqdm for embedding step. even after the embedding generation, it was taking a long time. Finally, I had to switch to cuML's GPU accelearted modules as described [here](https://maartengr.github.io/BERTopic/faq.html#how-can-i-speed-up-bertopic). That speeded up the things. 

I don't fully understand why some sort of progress bar is is impossible for the subsequent steps. Maybe I should check out the code to understand that. 

But anyways, thanks for the reponse. Feel free to close this issue if anything can be done to see the progress for the subsequent steps.

**Comment by MaartenGr** [comment]
> I don't fully understand why some sort of progress bar is is impossible for the subsequent steps. Maybe I should check out the code to understand that.

Progress bars typically only work if you can predict beforehand how long a procedure is going to take. With an iterable, like the embedding step, we can easily predict that since embedding each document/batch should have similar inference speeds. 

With the other steps, it is quite a bit more involved since these procedures do not always iterate over things. Take the c-TF-IDF step for instance, there is a calculation there that simply takes a certain amount of time but because it cannot be broken down into small iterable steps, predicting how long it will take is going to be very difficult. 

> But anyways, thanks for the reponse. Feel free to close this issue if nothing can be done to see the progress for the subsequent steps.

I don't think it's possible but would love to be proven wrong!
