### ISSUE TITLE
BERTopic visualizations not showing after uploading notebook to GitHub

### ISSUE THREAD

**Issue by JeffreyPrasetio** [MaartenGr/BERTopic#226]
I was working on Jupyter Notebook and all the visualizations are working nicely - visualize_topics, visualize_barchart, visualize_topics_over_time, etc.

However, when I uploaded it to github, nothing is showing, is there a workaround for this?

**Comment by MaartenGr** [comment]
After a bit of research, it seems that this is related to how plotly works. You can find a bit more about your issue [here](https://github.com/plotly/plotly.py/issues/931). BERTopic returns a figure but does not run `fig.show()`. Perhaps running that would already solve your issue. Otherwise, the link I shared above has some solutions that might work.

**Comment by JeffreyPrasetio** [comment]
I did some research as well and found that it's mostly to do with how github works - apparently there is no way to display interactive plots. The only compromise is to change the default renderer such that plotly returns a static image.

**Comment by neon-ninja** [comment]
```python
import plotly.io as pio
pio.renderers.default = "notebook"
```

should work better
