### ISSUE TITLE
Worker Failure

### ISSUE THREAD

**Issue by soumitra9** [MaartenGr/BERTopic#235]
Is there any way I can adjust the batch size of documents. I have large number of docs and even Google colab + is failing due to worker failure.

**Comment by MaartenGr** [comment]
Can you share with me the code you have been using? Also, can you share the exact error you are getting? That way, I can pinpoint where the issue is coming from. 

There are several places in the code where computation might be heavy depending on the documents. How many documents are you currently passing to BERTopic?

**Comment by MaartenGr** [comment]
I am closing this now due to inactivity. However, if you are still experiencing this issue or another, please let me know!
