### ISSUE TITLE
Adding verbose=True to UMAP

### ISSUE THREAD

**Issue by ginward** [MaartenGr/BERTopic#261]
Is it possible to add the verbose=True option for the UMAP call [here](https://github.com/MaartenGr/BERTopic/blob/0b321678ffe4eab0a28484faf76728f584a94ebd/bertopic/_bertopic.py#L150), as discussed on [UMAP's GitHub pages](https://github.com/lmcinnes/umap/issues/763#issuecomment-919160088)?

**Comment by MaartenGr** [comment]
The `verbose` option in BERTopic controls the manual logging in the package itself with specific messages and format. Therefore, the verbose options in dependencies will not be affected by BERTopic's `verbose` parameter as that would create conflicting styling formats. The resulting logging would be difficult to read. 

Having said that, since you can pass in your own UMAP model, you can control its parameters by setting them yourself: 

```python
from bertopic import BERTopic
from umap import UMAP

umap_model = UMAP(n_neighbors=15,
                  n_components=5,
                  min_dist=0.0,
                  metric='cosine',
                  verbose=True)
topic_model = BERTopic(umap_model=umap_model)
```
