### ISSUE TITLE
find_topics returns non-assigned topics (-1) only? 

### ISSUE THREAD

**Issue by ginward** [MaartenGr/BERTopic#281]
I am currently using find_topics with a list of multiple phrases: 

`similar_topics, similarity = model.find_topics(["creativity", "creative", "create"], top_n=5)`

However, it seems that the function only returns `-1` (the only element in `similar_topics`), which means unassigned topics (noise). Any idea why? Should I use something more of a natural sentence structure (rather than list of phrases) in `find_topics`?

**Comment by MaartenGr** [comment]
During the training of BERTopic, topic vectors are created if, and only if, an embedding model is supplied to BERTopic. When you only give BERTopic the document embeddings, no topic vectors will be created since there is no embedding model that can create the topic vectors. 

Thus, it matters whether you convert the embeddings first and then supply it to BERTopic or instead supply the embedding model to BERTopic. The former does not use MMR when optimizing the topic representations as it needs the embeddings of each candidate word. Moreover, no calculations can be done with topic vectors as they are calculated using an embedding model. The latter calculates all of those things and allows for the full experience of BERTopic.

In practice, you can do both to make sure you get faster training and still use all of BERTopic's features:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer

# Load data 
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

# Load embeddings either by calculating them on the fly or simply loading in a .npy file
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(docs, show_progress_bar=True)

# Pass both the embedding model and the embeddings to BERTopic
topic_model = BERTopic(embedding_model=embedding_model )
topics, probs = topic_model.fit_transform(docs, embeddings)
```
