### ISSUE TITLE
Loading datasets

### ISSUE THREAD

**Issue by sdspieg** [MaartenGr/BERTopic#30]
I'm very excited to see that there is now an LDAVis alternative that works with embeddings! Your documentation and colab illustrate how to load the Newsgroup dataset. But could you also add sthg (for us less experienced users) about how to load local json files, using the 'abstract' field for the NLP, but keeping the metadata for other types of analyses - like for dynamic topic modelling (for examples of vizzes, see the also very cool [DETM-tool](https://github.com/adjidieng/DETM) ).

**Comment by MaartenGr** [comment]
Sorry for the late response. I can definitely help out with providing guidelines for local files. I should note, however, that it is simply a matter of passing a list of strings to BERTopic. Let me know what kind of data you have and if it is available to me so that I can create a small example. 

The DETM-tool sounds very interesting! I have not looked at any temporal-based implementation. It would definitely be nice to explore if it is possible to add such a feature to BERTopic.
