### ISSUE TITLE
Using pretrained models without re-fitting

### ISSUE THREAD

**Issue by Andrea-Oliveri** [MaartenGr/BERTopic#312]
Good Afternoon,
I was experimenting with this library and I have observed an unexpected behaviour when trying to use a pretrained model on a new dataset.

It is my understanding, reading the documentation, past issues and the provided link to [sentence_transformers](https://www.sbert.net/docs/pretrained_models.html) that the "all-MiniLM-L6-v2" model is pre-trained and ready to use.
However, when trying to run this sample code:

```
from bertopic import BERTopic

bert_model = BERTopic(embedding_model = "all-MiniLM-L6-v2")
bert_model.transform(list_of_sentences)
```

I get the following error:
`ValueError: This BERTopic instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.`

Thank you in advance for your help and for providing this powerful library.

**Comment by MaartenGr** [comment]
This is actually expected behavior. It is true that the underlying language model is pre-trained and ready to use. That does not mean however that the topic model in itself is pre-trained. UMAP, HDBSCAN, and c-TF-IDF all need to be trained before being able to detect topics. Even if we can represent text as embeddings, that does not mean we know what topics can be found in the data. 

If you do not have any data to train on, I would suggest looking into keyword-extraction-based techniques such as [KeyBERT](https://github.com/MaartenGr/KeyBERT) and [YAKE](https://github.com/LIAAD/yake). Those models can extract important keywords from the documents. Those keywords are typically similar to one another and do not need a training.

**Comment by Andrea-Oliveri** [comment]
I understand now. Thank you
