### ISSUE TITLE
List of documents in a topic cluster

### ISSUE THREAD

**Issue by gimseng** [MaartenGr/BERTopic#32]
Hi, I am wondering if there's a way to query a list of documents (either return ID or actual text) in each topic cluster?

**Comment by MaartenGr** [comment]
Since the documents are only used to create the model, I do not keep track of the documents themselves or their possible ID. However, it would be nice if you could see which groups of documents belong to which document. 

For now, you can try the following code:

```python
grouped_topics = {topic: [] for topic in set(topics)}
for index, topic in enumerate(topics):
    grouped_topics[topic].append(index)
```
It simply takes in the resulting `topics` from creating a BERTopic model and creates a list of document IDs for each topic cluster. I should note that these IDs are then simply the indices of `docs`. 

Thus, a simple groupby based on the documents indices. Let me know if this helps!
