### ISSUE TITLE
Question about Number of topics in BERTopic

### ISSUE THREAD

**Issue by PiyushKyushu** [MaartenGr/BERTopic#320]
Hi Maarten!
Thank you for the help.

If this question have been asked already please provide the link.

I have a dataset of around 10,000 rows. I used BERTopic and it produced 135 topics. Is there a way to check whether this is the right number of topics (other than manual inspection). For example by coherence model or any other similar process? 

Also, as topic representation section mentioned, we can update the model and choose the number of topics by ourself but how should I know which is the best number ? For example in my case BERTopic produced 135 topics and I update the model by `n_gram_range=(1,2)` but then in the next step how do I guess the number of topics `nr_topics=?`

Thank you in advance!

**Comment by MaartenGr** [comment]
Whether a number of topics are the "correct" number of topics is a very difficult question to answer. It starts with the definition of the "correct" number of topics. Is a number of topics better than another when it has tighter clusters or when the topic coherence is improved? Then, what about topic diversity and the predictive power of the clusters? 

In other words, although I can point you towards [Gensim's CoherenceModel](https://radimrehurek.com/gensim/models/coherencemodel.html) which provides coherence evaluation techniques, it is up to you to decide which factors are important when evaluating the topic model. Unfortunately, due to the very subjective nature of topic modeling I cannot provide with a single "correct" evaluation metric. 

As with most things, I would advise actually focusing on sanity checking the output yourself. Do the topics makes sense in the context of my use case? What happens if I increase or decrease the topics? Does it still fit with the domain knowledge of stakeholders? Etc.

**Comment by PiyushKyushu** [comment]
I understand. Thanks for the reply.
