### ISSUE TITLE
Too many clusters and outliers

### ISSUE THREAD

**Issue by paulthemagno** [MaartenGr/BERTopic#334]
I have a list of about 40K documents. I've tried to use default parameters for UMAP and HDBSCAN, so something like this:

```python
topic_model = BERTopic(top_n_words = 10,
                       n_gram_range = (1,1),
                       nr_topics = None,
                       low_memory = True,
                       calculate_probabilities = True,
                       embedding_model = "distiluse-base-multilingual-cased_v2"
topic_model.fit_transform(documents)
```

Then I visualize this topic distribution:
![image](https://user-images.githubusercontent.com/38130299/142250063-e2be9dfe-d0ec-451f-83be-6b01403bee4d.png)
I have 2 problems:

- I have many overlapped clusters. I'd like to have fewer and bigger clusters.
So my intuition is to raise the param `min_topics_size` (is there a way to have a dynamic value given the number of the documents?). Which value do you think it's the best? (50? 100?). Another parameter I think can change is the UMAP parameter `n_neighbors` but I don't know if changing it can improve the results. 

- I have many documents tagged as **outliers** (about 7K on 40K documents), so if I do a `topic_model.transform(new_documents)` almost all the new examples are tagged as outliers (topic = -1). I don't know if 7K documents on 40K are too many outliers or it is a normal number.

Seeing such a distribution, what would you change?

**Comment by MaartenGr** [comment]
> I have many overlapped clusters. I'd like to have fewer and bigger clusters.

There are two things important here. First, it is not necessarily a bad thing that those clusters seem to overlap because many actually do not overlap in reality. The size of the points in `visualize_topics()` merely represents the size of the cluster. Therefore, although it may seem that topics overlap they often do not. Try to imagine the results in `visualize_topics()` as points of equal size, then you will see that many do not overlap. 

Second, if you would like to have fewer and bigger clusters, it is advised to increase `min_topics_size` to suit your use case. In practice, it is difficult to say what value would be best as I am not familiar with your use case, data, etc. Increase the `min_topics_size` parameter until you are satisfied with the resulting clusters. Start with a value of something like 50 and see what the effect is. 

> I don't know if 7K documents on 40K are too many outliers or it is a normal number.

This is typical behavior and should not be surprising. Often, many points do not nicely fit within a specific cluster. To reduce the number of outliers, you can look into [this](https://hdbscan.readthedocs.io/en/latest/faq.html#q-most-of-data-is-classified-as-noise-why) to reduce them. Do note that these documents are outliers for a reason and that forcing too many of them in a cluster may be ill-advised. 

Finally, you can use `probs` after setting `calculate_probabilities=True` in order to assign outliers to topics if you so choose. The same considerations as the above apply here.
