### ISSUE TITLE
'BERTopic' object has no attribute 'visualize_barchart'

### ISSUE THREAD

**Issue by bartmnli** [MaartenGr/BERTopic#357]
Hi,

The plot functionalities of BERTopic doesn't work for me or gives an error.

I have tried installing using :
!pip install bertopic==0.9.3
!pip install bertopic[visualization]
!pip install bertopic[flair]
!pip install bertopic[gensim]
!pip install bertopic[spacy]
!pip install bertopic[use]

When I try: 
from bertopic import BERTopic
dir(BERTopic)

I cant find visualize_barchart in the list.

Another question is: model.visualize_topics_over_time(topics_over_time) returns just a huge blank space but no figure gets displayed. Is there a way to fix this please?

Thanks.

**Comment by MaartenGr** [comment]
Ah, I would advise installing BERTopic with a single pip install. For example, if you want to install BERTopic together with flair, only use `pip install bertopic[flair]` as this will install both Bertopic and flair. 

Also, `pip install bertopic[visualization]` is an older version of BERTopic and is not supported anymore. 

Thus, run it as follows:

```
!pip install bertopic[flair]==0.9.3
```

and then try something like this:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
topic_model.visualize_barchart()
```

Lastly, make sure that the environment in which you work (e.g., Jupyter Lab) supports plotly-based outputs.

**Comment by bartmnli** [comment]
Thanks, when I try: !pip install bertopic[flair]==0.9.3

I get, 

ERROR: Could not find a version that satisfies the requirement numpy>=1.20.0 (from bertopic[flair]) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
ERROR: No matching distribution found for numpy>=1.20.0

Thanks!

**Comment by MaartenGr** [comment]
I would advise starting from a fresh environment and then only running `!pip install bertopic[flair]==0.9.3` and nothing else to make sure there are no issues with conflicting dependencies. For example, I ran the code above in a Google Colab session and a fresh conda environment and had no issues. 

Also, there are versions of numpy > 1.20.0 so it might be an idea to check what is happening there. Perhaps you need to update pip.

**Comment by bartmnli** [comment]
Thanks a lot. It works now. Although I have a small issue with following: https://maartengr.github.io/BERTopic/tutorial/supervised/supervised.html

If I don't have labelled data, how can I force the model to find  topics in specific categories? Thanks!

model = BERTopic(verbose=True).fit(text, y=categories)
ValueError: Length of x = 24990, length of y = 6, while it must be equal.

**Comment by MaartenGr** [comment]
You need to make sure that `categories` has the same length as `text` since you are supplying it with labeled data. If you do not have labeled data but categories for which you have some description, I would advise going with [guided BERTopic](https://maartengr.github.io/BERTopic/tutorial/guided/guided.html) instead. I think it would suit your use case a bit better.

**Comment by bartmnli** [comment]
Great, thanks. I'm trying to fit a large number of text using BERTopic. The code runs for a few hours and stops abruptly after displaying the following  BERTopic - Transformed documents to Embeddings. Any idea Why?

Batches: 100%
362490/362490 [3:50:04<00:00, 26.26it/s]

2021-12-08 19:47:14,063 - BERTopic - Transformed documents to Embeddings

**Comment by MaartenGr** [comment]
Could you indicate what happened during the abrupt abort? Typically, you see some error either in the output or in the environment itself. For example, it might indicate that there were RAM issues. If you are facing memory issues, please see [this](https://maartengr.github.io/BERTopic/faq.html#i-am-facing-memory-issues-help) FAQ page.

**Comment by bartmnli** [comment]
Thanks for your support. Sorry for the late reply, my RAM was freezing and crashing. Any suggestion on how to avoid this?

I have tried to use the low_memory option but still my RAM freezes. I am using 48vCPUs, 192 GB RAM and 4 GPU's. Dataset is more than 100,000 lines of text.

topic_model = BERTopic(min_topic_size=10, verbose=True,low_memory=True,calculate_probabilities=False)

And earlier, you had mentioned that, "Lastly, make sure that the environment in which you work (e.g., Jupyter Lab) supports plotly-based outputs". Sorry that I'm new to this. I've tried a few online fixes but nothing seems to work. Any suggestions on how I could enable plotly based outputs?

Thanks.

**Comment by MaartenGr** [comment]
Could you indicate where the RAM freezes? Since you have set verbose to True, what is the logging output of BERTopic before your RAM freezes? If I know which steps BERTopic has done before freezing up, it is easier to track down the specific issue. 

Assuming you are using BERTopic >= 0.9.3, it might also be related to the value you have for `min_topic_size`. With 100,000 documents you can get many microclusters. So I would advise setting that value to at least 100. Also, as mentioned above, make sure to follow all the steps as indicated [here](https://maartengr.github.io/BERTopic/faq.html#i-am-facing-memory-issues-help). That also means using the CountVectorizer and installing the latest version of HDBSCAN through its master branch. 

With respect to plotly, it is necessary that an environment like Jupyter Lab supports outputting plotly-like visualizations. You can find more information [here](https://plotly.com/python/getting-started/) with respect to supporting plotly in Jupyter Notebook and in Jupyter Lab.

**Comment by bartmnli** [comment]
topic_model.save("my_topicmodel")

> ---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/numba/core/serialize.py in save(self, obj)
    304         try:
--> 305             return super().save(obj)
    306         except _TracedPicklingError:

/opt/conda/lib/python3.6/pickle.py in save(self, obj, save_persistent_id)
    475         if f is not None:
--> 476             f(self, obj) # Call unbound method with explicit self
    477             return

/opt/conda/lib/python3.6/pickle.py in save_bytes(self, obj)
    700         else:
--> 701             self.write(BINBYTES + pack("<I", n) + obj)
    702         self.memoize(obj)

error: 'I' format requires 0 <= number <= 4294967295

During handling of the above exception, another exception occurred:
..........
_TracedPicklingError: Failed to pickle because of
  error: 'I' format requires 0 <= number <= 4294967295
tracing... 
 [0]: <class 'tuple'>: 140189797634376
 [1]: <class 'dict'>: 140187322597240
 [2]: <class 'function'>: 140176136796632
 [3]: <class 'tuple'>: 140188392477360
 [4]: <class 'list'>: 140189796956744
 [5]: <class 'numpy.ndarray'>: 140178074301664
 [6]: <class 'tuple'>: 140190097463696
 [7]: <class 'bytes'>: 140067011919888

**Comment by MaartenGr** [comment]
Let's take a few steps back first. 

With respect to your question about the `freezing` of the model:
* Could you share your code, not just for running BERTopic, but also any preprocessing steps you are taking? 
* Could you share the versions of packages in your environment? 
* How many documents are you exactly passing to BERTopic? 
    * You mentioned it was over 100,000 but if I see the progress bar for extracting embeddings it seems like you are passing 698730 * 32 = 22359360! documents to BERTopic, is that correct? 

With respect to your question about `saving` the model:
* Could you share your entire code up to and including saving the model? 
* As of right now, I do not know how you trained that specific model since you run into freezing issues. I assume then it is a different model? 
   
Lastly, a few things to note. First, I would highly advise starting from a fresh environment and creating a clean install of BERTopic through `pip install --upgrade bertopic`. This makes sure that you install BERTopic v0.9.4 which fixes a few things and is more up to date with respect to the documentation. Second, if you are going to save a model in one environment and want to use it in another, make sure that they contain the same versions of the dependencies that BERTopic relies on. Otherwise, you are bound to get issues.

**Comment by MaartenGr** [comment]
Due to inactivity, I am going to close this issue for now. However, if you are still experiencing this problem, please let me know! I'll make sure to reopen it and see if we can figure this out.
