### ISSUE TITLE
Stop words in corpus of large texts

### ISSUE THREAD

**Issue by DKanarsky** [MaartenGr/BERTopic#377]
1. Should stop words be removed from corpus beforehand? My topic_model generates clusters with most frequent words like "the", "and", "to" and etc.

2. Is there any model to process long text without truncating them to maximum available for transformers?

**Comment by MaartenGr** [comment]
It is typically not necessary to remove stopwords if enough topics are generated (> 40). However, if you want to remove stopwords because they appear for some reason still in the topic representation, I would advise using a CountVectorizer in BERTopic to remove them as described [here](https://maartengr.github.io/BERTopic/getting_started/models/models.html). 

Transformers typically have a token limit which makes it difficult to process long documents. You can, however, either split them into paragraphs or sentences and use those in BERTopic or use an entirely different model, such as TF-IDF to process the documents. You can find more about different models [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html) and [here](https://maartengr.github.io/BERTopic/getting_started/custom_embeddings/embeddings.html).

**Comment by aph61** [comment]
I used an alternative approach that worked quite well. 

The c-tfidf step is to characterize a topic; it does not take part in the clustering. So you can use any method you wish to characterize a sentence. I kept track of what topic a sentence belongs to, and then used tokenization and nouns, pronouns and adjectives for the sentences (in a topic) to use it in the c-tfidf. You can also create a word2vec model of the tokenized/filtered sentences and use those to characterize the cluster (I haven't done that yet=.

But the bottom line is, the c-tfidf is used to characterize a topic. Once your sentences are assigned a cluster you can do anything you wish to characterize the cluster

**Comment by DKanarsky** [comment]
Thanks!!!
