### ISSUE TITLE
Compute Sub-Clusters

### ISSUE THREAD

**Issue by Karol-G** [MaartenGr/BERTopic#38]
Hi,

used BERTopic on the arxiv dataset and extracted the most frequent topics (the biggest clusters).
Now I want to get the sub-clusters of the biggest cluster. What I did was to simply filter the documents and umap_embeddings with the corresponding cluster label and re-run hdbscan and c-TF-IDF on the sub-sets.
However, the results are not really satisfying. Even though my most frequent topic has a cluster size of 6756 I only get two sub-clusters. One with size 5810 and one with 579. If I repeat the process with the 5810 sub-cluster to get the sub-sub-clusters then hdbscan fails to make any clusters and all documents get label -1.

Is there something wrong about my approach? I feel like hdbscan should be able to find more clusters with cluster sizes of 6756  and 5810. For the first clustering I got 2733 clusters/topics.

The parameters are all on default.

Best
Karol

**Comment by Amine-OMRI** [comment]
Hi, I've tested this before and wanted to extract the sub-cluster on the one of noise one (-1), I don't know if you are facing the same thing, any way, you should know that documents that are classified as noise can be considered as not being descriptive of a specific subject. 

HDBSCAN will detect dense areas of document vectors, so each cluster is a dense area, so if you do another time HDBSCAN clustering on a cluster without changing parameters of UMAP and maybe also the min_cluster_size, you won't get sub-clusters.

If you want to extract sub-clusters from a specific cluster, you can modify the UMAP parameters to focus on the local structure of the data rather than its global structure, if you want more targeted small clusters.

You can also split your input data to avoid losing data when generating embeddings due to the limitation of the maximum length of transformer inputs.
I hope this will help you.

**Comment by MaartenGr** [comment]
@Karol-G This is actually expected behavior as you are using significantly less data than you originally used. You will need to lower `min_topic_size` and `n_neighbors` in order to find clusters in your sub cluster. You will need to play around with the actual values but reducing them is likely to help to find subclusters. 

Also, it might be best to run the BERTopic separately for that single cluster without using pre-trained umap embeddings as you want to find subclusters without being restrained by information in other clusters.

**Comment by Karol-G** [comment]
Thanks @Amine-OMRI and @MaartenGr for your replies. Reducing these two parameters helped! The results look pretty good now :)
