### ISSUE TITLE
Setting batch_size parameter for encoding embeddings with Sentence transformers

### ISSUE THREAD

**Issue by yanhong-zhao-ef** [MaartenGr/BERTopic#387]
I am currently using my laptop's GPU to encode embeddings and because I have to pass it externally to the BertTopic class since the default 32 batch size will cause a memory overflow. Don't know if there is a way we can pass batch size straight into the BertTopic class or the fit_transform functions somehow? 

```python
 model = SentenceTransformer("paraphrase-multilingual-mpnet-base-v2", device="cuda")
 embeddings = model.encode(docs, show_progress_bar=True, batch_size=16)
 topic_model = BERTopic(embedding_model=model, calculate_probabilities=True)
```

**Comment by MaartenGr** [comment]
Due to the many different language models that exist out there, there currently is not an option to set the batch size as that would require a custom-made option for every model. Although it is possible to batch the encoding process outside of the package, I believe the batching processes might be best handled within the related language models themselves for optimization. So, unfortunately, it is not possible to pass the batch size to BERTopic right now.
