### ISSUE TITLE
'Duplicate' NGram values in topic list

### ISSUE THREAD

**Issue by drob-xx** [MaartenGr/BERTopic#396]
I've set the CountVectorizer to examine bi and trigrams (ngram_range=(1, 3)) . This seems very useful. However, I'm seeing "duplicate" terms e.g.:

```
defense 0.02016887977427
military	0.016689663896
ndaa	0.01359978768527
national	0.01016988788388
national defense	0.00884664358394
authorization	0.0075166889175
house	0.00746174848713
defense authorization	0.0073734540375
national defense authorization	0.00691283664373
defense authorization act	0.0068058033093
```

The terms that include "defense", "national", "authorization" and "act" seem to clearly overlap. I'm using these vocabularies to select documents for further processing and it seems we have essentially one term "pushing out" other terms that might surface otherwise. In practice I'm doing an initial broad search over all these terms to identify target documents for further processing, so I'm not sure what I might be "missing" otherwise. Am I thinking about this in a way that makes sense? Would it be a "good thing" in this example if "defense authorization", "national defense authorization" and "defense authorization act" were all reduced to a single term?

**Comment by MaartenGr** [comment]
As you mentioned, whether reducing them to a single term depends very much on the use case. Here, I can imagine that you would like them to be reduced to just a few words instead of most of them. Terms like `national defense authorization` and `defense authorization` seem to tell you essentially the same thing. 

There are two ways you can approach this. First, you can simply set the `top_n_words` much higher to see if other words pop up. I would only advise doing this if you feel like the words you have now should not be reduced and you want to explore the topic a bit further. Second, it might be interesting to play around with the `diversity` parameter which ranges from 0 (not diverse topic representation) to 1 (very diverse topic representation). Setting that value higher will force out duplicate terms and try to optimize the diversity of words in the topic representation. Start with setting this value at `0.1` or lower to see what happens. Typically, I would not advise approaching a value of 1 as that would likely degrade the quality of the topic representations. 

Note that there might be some cases where seemingly similar words should not be reduced as the context (larger n-grams) might give you additional information you would otherwise not get.

**Comment by drob-xx** [comment]
Martin, as usual thanks so much for taking the time to respond so precisely. I will play with both `top_n_words` and `diversity` and see what happens. I should have also been clearer in an underlying question I had regarding the ngram generator in the CountVecrtorizer. I'm wondering whether or not the generator is actually generating multiple terms for the same occurrence of a long ngram like `national defense authorization act` where we might see 3 bigrams, and 2 trigrams, all from the same four words (this was my first guess at what was happening). However, I suspect, based on your response, that this isn't the issue. I know that different count vectorizers can be used and since I'm a bit foggy on the role they play in terms of the embeddings I should probably take a closer look there as well.

As a side-note, I am always hesitant to post in the `Issues` section as to me it feels like an escalation of an question to the level of a bug, rather than just a query regarding functionality. I also suspect that others, who may be experiencing similar issues or have come up with solutions, might be more hesitant to respond here rather than in a discussion forum. But I know you have a lot going on and I'm sure have good reasons for doing things this way. I expect to do some more work on this issue in the coming week and will post the results here if this issue is kept open. Thanks for such a great package!

**Comment by MaartenGr** [comment]
Ah yes, that is indeed what is happening. The CountVectorizer differentiates between subsets of a long n-gram as it does not take into account that it may belong to the same long n-gram. In practice, it is very difficult to state when something belongs to the same long n-gram as there are quite a number of exceptions and issues that might pop up if you would approach it like that. 

I can understand where you are coming from. To give you an idea of my reasoning here, I purposefully did not open the discussions page as I am not sure how much time I have to participate in those discussions but I would still like to know what exactly is happening and if people are running into issues. I have a better view of everything if it is all kept within a single place. To me, it is perfectly fine if you want to discuss things on the issues page without having an actual bug. 

Having said that, if there is much demand to open up the discussions page, I have no issues with doing so but with the very large disclaimer that I cannot participate much in the discussions.

**Comment by drob-xx** [comment]
Thanks. I'm going to look at the Vectorizer more closely. Thanks for the response on the discussions. I agree it could be a trade off. I'm of course  a +1 on opening it up :).

**Comment by MaartenGr** [comment]
Closing this issue since the last activity was a while ago. Having said that, if you want to re-open it, please let me know!
