### ISSUE TITLE
How to get all topics of a single document 

### ISSUE THREAD

**Issue by TAsUjxnMIL** [MaartenGr/BERTopic#399]
Hi Maarten, 

I am currently doing a student research and I wondered if there is the possibility to get the topics of a single document. I have a text corpus that consists of 300+ documents. I get all topics which are in those documents but what I need is the mapping:
Document 1 --> Topic 0, Topic 1 
Document 2 --> Topic 2, Topic 7 
...
Is this possible with your implementation? There is a function called get_representative_docs() but this gives me the exactly the required result other way around. 

Thank you for your help.

**Comment by MaartenGr** [comment]
If you set `calculate_probabilities=True` when you initialize BERTopic, then the resulting `probs` variable will be a mxn matrix, where *m* is the number of documents and *n* is the number of topics. This matrix represents the probability of all topics belonging to a specific document. That way, you can get a proxy of the distribution of topics within a single document. 

Do note that you typically want to have quite a bit more than 300 documents in order to get a good topic representation. Typically, I would advise at least 2000 documents. Moreover, if your documents are quite long, then it might be interesting to split them up into sentences. That will result in more data and allow you to more accurately model the distribution of topics within a single document as we then assign topics to each sentence within a document.

**Comment by TAsUjxnMIL** [comment]
Thank you for the answer, it helped me!
