### ISSUE TITLE
Help required in assigning docs to topics manually using argmax of `probs` feature.

### ISSUE THREAD

**Issue by schetudiante** [MaartenGr/BERTopic#404]
Your advice of leveraging the argmax of the `probs` to manually assign a topic for each doc worked like a charm.
Many thanks for the fast response!

_Originally posted by @lighteternal in https://github.com/MaartenGr/BERTopic/issues/329#issuecomment-970316277_

Hey @MaartenGr and @lighteternal

hey, I am also facing the same issue can you share the code snippet you used for "leveraging the argmax of the probs to manually assign a topic for each doc" ?

currently, I rely on :
reduce_topics(docs, topics, probabilities=probs, nr_topics=20) but I still get like 60% of my docs as outliers.

After assigning docs to topics manually, My goal: I just to want to see top 10 topics along with their respective representative docs.

Help would be greatly appreciated!
Thanks

**Comment by MaartenGr** [comment]
Whenever you run the following:

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic(calculate_probabilities=True)
topics, probs = topic_model.fit_transform(docs)
```

the resulting `probs` variable contains the topic-document probability matrix. In other words, it shows you what the probability is that a certain topic belongs to a certain variable. This matrix does not contain the -1 topic. This means that if you take the `np.argmax()` of each document in `probs` you will get the most likely non-outlier topic for each document. That way, it prevents all outliers. Do note though that removing all outliers is typically not advised as it is seldom the case that no outliers exist at all in the data. 

Moreover, if you want to see the top 10 topics and their documents, then you can just use `.get_topic_info()` together with `.get_representative_docs()` regardless of whether outliers exist in the data. 

Lastly, if you want to reduce the outliers while training, I would advise following along with the documentation [here](https://maartengr.github.io/BERTopic/faq.html#how-do-i-reduce-topic-outliers). Make sure though that not all outliers are removed, there is a reason they are found as outliers and including too many outliers in a cluster will reduce the quality of topics.

**Comment by schetudiante** [comment]
Hey Maarten,

Thanks for your reply. This package and you replying and helping us is a hope to many students/researchers in the world!

but my question and what I meant is broken down in parts for better understanding, 

after training the model:
using:
```
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']

topic_model = BERTopic(calculate_probabilities=True)
topics, probs = topic_model.fit_transform(docs)

```
then I view the top 10 topics and view their representative docs, 
using:
 **Code 2:**

```
        topic_freq = topic_model.get_topic_freq()
        outliers = topic_freq['Count'][topic_freq['Topic']==-1].iloc[0]
        freq = topic_model.get_topic_info()

        v = 0
        for topic in range(len(set(topics))-1):
            v +=1
            df = freq.head(11)
            words = [" | ".join([word[0] for word in topic_model.get_topic(topic)[:20]])] #top words for each topic
            print(words)     #prints something like : [election | trump | republicans ...]
            rep_docs = topic_model.get_representative_docs(topic)
            print(rep_docs)  # prints something like: "I knew they would steal election"
            if v == 10:
                break
```

What I need help with, now, is this:
After viewing the "main words" and "representative docs" for the top 10 topics , how can I:

1. Assign topics based on ```np.argmax(probs)``` to assign docs to topics and then
2. Use my **Code 2** (from above) to get new updated topics (assuming they get changed after performing step 1) to print
again 
```
> words = [" | ".join([word[0] for word in topic_model.get_topic(topic)[:20]])] #top words for each topic
   print(words)  #prints something like : [election | trump | republicans ...]
> rep_docs = topic_model.get_representative_docs(topic)
    print(rep_docs)  # prints something like: "I knew they would steal election"
```
-If I could someup , by whole question I would ask:
Please help me to do step 1 for majority of docs so I can goto step 2.

Thank you, 

Awaiting your help.
A Student.

**Comment by MaartenGr** [comment]
From your question, it seems that you want to use `probs` **after** training the model to reduce the number of outliers generated. This is not directly supported in BERTopic as you want to reduce the number of outliers preferably **during** training. You can find a number of tips to reduce the outliers as much as possible in the documentation [here](https://maartengr.github.io/BERTopic/faq.html#how-do-i-reduce-topic-outliers). 

Having said that, if that does not fully work out then there are some hacks to do this after training the model. We can use some of the internal functions to remove the outliers and then update the topic representations. However, since this is not supported directly in BERTopic, I cannot vouch for its stability as errors and bugs may appear. 

To do this, we first train our topic model:

```python
from sklearn.datasets import fetch_20newsgroups
from bertopic import BERTopic

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
topic_model = BERTopic(calculate_probabilities=True)
topics, probs = topic_model.fit_transform(docs)
```

Here, it is important to realize that `calculate_probabilities=True` is necessary to assign outliers to topics. Next, we are going to assign all documents to a topic except for the very first document. That document will be assigned to the outlier cluster. This is necessary due to some structural things in BERTopic:

```python
import numpy as np
import pandas as pd

new_topics = [-1] + list(np.argmax(probs, axis=1)[1:])
documents = pd.DataFrame({"Document": docs, "Topic": new_topics})
```

These `new_topics` are similar to `topics` in that each value corresponds to the document in `docs` but with the main difference that no outliers are present in `new_topics` compared to `topics`. Of course with the exception of the first document. 

Next, we need to update our BERTopic model to represent these updated clusters of topics:

```python
topic_model.update_topics(docs, new_topics)
topic_model._update_topic_size(documents)
```

These two functions are needed to update the topic representations and the topic sizes. Note that we **do not** update the representative documents as we did not update the HDBSCAN model (which would require BERTopic to be re-fitted). 

Now, we can print the top 10 most frequent topics together with their representative documents:

```python
freq_topics = [int(topic) for topic in (topic_model.get_topic_info().sort_values("Count", ascending=False).Topic[:10].values)]

for topic in freq_topics:
    words = " | ".join([word[0] for word in topic_model.get_topic(topic)[:10]])
    rep_docs = topic_model.get_representative_docs(topic)
    
    print(f"\nTopic {topic}")
    print(words)
    print(rep_docs)    
```


Note that if you are now going to be using `.transform()` on new documents, they can still be assigned to outlier clusters as the above steps are merely used to change the representation of the topics and it does not change the training procedure.

**Comment by MaartenGr** [comment]
Closing this for now. However, if you want to discuss this further, let me know and I'll make sure to reopen the issue!
