### ISSUE TITLE
How to exclude the 0-th stop-words topic from the topic_model visualizations?

### ISSUE THREAD

**Issue by fishfree** [MaartenGr/BERTopic#405]
```
from bertopic import BERTopic
topic_model = BERTopic(min_topic_size=35, language="english", calculate_probabilities=True, verbose=True)
topics, probs = topic_model.fit_transform(tweets)
freq = topic_model.get_topic_info(); freq.head(10)
```
![image](https://user-images.githubusercontent.com/1741341/149253076-e1b961c7-bfb5-47e7-8233-960f6288baa8.png)

I want to exclude the red-bordered stop-words topic in the topic_model. Thanks!

**Comment by MaartenGr** [comment]
You can remove stopwords by following along with the documentation [here](https://maartengr.github.io/BERTopic/getting_started/models/models.html). You can focus on only using a custom `CountVectorizer` model instead of the UMAP and HDBSCAN examples. Within the CountVectorizer, you can then set `stop_words='english'` in order to remove stopwords from the topic representation. So it will be something like this:

```python
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(stop_words="english")
topic_model = BERTopic(vectorizer_model=vectorizer_model, min_topic_size=35, language="english", calculate_probabilities=True, verbose=True)
```

One thing to note is that the `min_topic_size` you have set is quite large which typically results in lower quality topics if you have little data available. Setting that to `20` is likely to give you more coherent topics.

**Comment by fishfree** [comment]
@MaartenGr Thank you very much! I will try.

**Comment by MaartenGr** [comment]
@fishfree Out of curiosity, did the proposed solution work for you?

**Comment by fishfree** [comment]
@MaartenGr Yes, it works! Sorry for replying late.
