### ISSUE TITLE
package bertopic[visualization] not found

### ISSUE THREAD

**Issue by sheth7** [MaartenGr/BERTopic#42]
Thank you for developing this implementation.

I am trying to use the bertopic[visualization] based on your blog post -- [Towards Data Science post](https://towardsdatascience.com/interactive-topic-modeling-with-bertopic-1ea55e7d73d8).

My system throws an error :  no matches found: bertopic[visualization]

Could you help?
Thanks,
Anan

**Comment by MaartenGr** [comment]
`pip install bertopic[visualization]` seems to work in Google colab and locally. However, a quick search seems to indicate that the error you are getting might be due to the workings of `zsh`. It has trouble processing the square brackets. Could you try the following instead:

`pip install 'bertopic[visualization]'`

If that does not work, perhaps escaping the brackets might help:

`pip install bertopic\[visualization\]`

**Comment by sheth7** [comment]
Thanks Maarten,
Yes, that was it 🙂.
It worked.

Ananya
________________________________
