### ISSUE TITLE
Error Microsoft visual c++ 14 Or greater is required 

### ISSUE THREAD

**Issue by rajnishrajput12** [MaartenGr/BERTopic#430]
While installing bertopic using pip install bertopic at the step where it installs hdbscan is throwing error Microsoft visual c++ or greater is required. 

When I checked program installed I see all these already installed like visual c++ 13 redistributable and visual c++ 2015-2019 redistributable 
![IMG-20220203-WA0000](https://user-images.githubusercontent.com/43354631/152323682-0e92d661-5da6-453b-9baa-18e303935ffe.jpg)

System windows 64 bit

**Comment by MaartenGr** [comment]
There might be an issue with how you installed C++ and whether it has a PATH or not. Could you share the entire error message? As of right now, it is difficult to understand what exactly is happening without the error message.

**Comment by rajnishrajput12** [comment]
1.yes here is the command which i am executing
![err3](https://user-images.githubusercontent.com/43354631/152672474-2d55d54f-3961-46ca-867b-e42f4f8f91ac.png)
2. error when it is building wheels for HDBSCAN
![err1](https://user-images.githubusercontent.com/43354631/152672496-4a7da186-0226-4be8-b3dd-cca216bea993.png)
3.enivronment variable details which i have .. please check last line of the attached pic
![err2](https://user-images.githubusercontent.com/43354631/152672516-0860db60-8adb-413a-9534-04c334a6a123.png)
4. programs of visual c++ installed in my system.
![err4](https://user-images.githubusercontent.com/43354631/152672628-448c8d48-9265-4fb5-bb68-5441cd8c4f23.PNG)
please let me know if you need more info

**Comment by MaartenGr** [comment]
The pictures are quite difficult to read but I believe you will need to either add them to your PATH or remove and re-install them in order to have the PATH (or anything else that might cause issues) to be updated. If that does not work for you, you can also install BERTopic via conda which might solve the issue.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. However, if you want to discuss this further, let me know and I'll make sure to reopen the issue!

**Comment by plugiery** [comment]
I am interested as I am encoutering the same issue. You suggested using conda instead of pip but I still get the error.
Likewise the error occurs while trying to install hdbscan.

<img width="698" alt="Capture" src="https://user-images.githubusercontent.com/83005444/163158179-b5cb52b3-9a25-4ca2-b58d-8a9d7fd5c156.PNG">

I am not sure what Microsoft visual c++ does but I have it installed (several of them actually, including 14.30... version)


<img width="412" alt="Capture2" src="https://user-images.githubusercontent.com/83005444/163158445-f65b8b78-7511-4523-a9b0-f9d0d4b583f1.PNG">

 

> will need to either add them to your PATH or remove and re-install them in order to have the PATH 

Would you be so kind as to explain what this means? What does "them" refer to? and what "PATH" should it be added to?
Does it have to do with virtual environment?

Thank you very much :)

**Comment by plugiery** [comment]
By environnement variable do you mean this? (obtained via windows shell command: $get-childitem env:$

![image](https://user-images.githubusercontent.com/83005444/163163190-3f3bb061-32ce-4120-a691-30a3ab67ce41.png)

**Comment by MaartenGr** [comment]
I would not suggest doing things with your PATH without a thorough understanding of what it entails. Instead, it might be worthwhile to remove your installations of Microsoft visual c++ and install it using one of the methods listed [here](https://stackoverflow.com/questions/44951456/pip-error-microsoft-visual-c-14-0-is-required), [here](https://stackoverflow.com/questions/29846087/error-microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat), [here](https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst), or for more in-depth instructions, [here](https://github.com/benfred/implicit/issues/76). 

Quite a few people have been struggling with this as you can see from the many links I added, so I cannot say for certain which method works best for you. Having said that, from the links it seems that the way you install it is quite important.

**Comment by selfyguy** [comment]
![2022-04-19 13_22_26-Cmder](https://user-images.githubusercontent.com/34223101/163953858-b936713d-17f5-47c3-9c4a-9f4f521b87a7.jpg)

Am getting the same error and none of the fixes (haven't tried conda or chocolatey approach) in the links seem to work. 
Am attaching a screenshot of the complete console output in image format and as a zipped html format.

Any help is appreciated.

[git2.zip](https://github.com/MaartenGr/BERTopic/files/8511035/git2.zip)
