### ISSUE TITLE
Merge topics from different models

### ISSUE THREAD

**Issue by nilsblessing** [MaartenGr/BERTopic#435]
Hi all,

I'm currently looking for a solution to "merge topics" from two models.

The reason why I thought about merging is because I found that when join both datasets together and create a single model, it leads to "messy" topics (from my perspective). This means that some specific topics from dataset (a) get mixed with topics from dataset (b) which can lead to confusion from a business perspective. What I was thinking about is to accept/merge all topics which intercept from both models and add all specific topics from model (a) and model (b).

Are there any ideas on how to do that or maybe hints why this would be a bad idea?

As a general information I would like to note that I'm working with short texts (max. 50 words/document) using the sentence-transformers for embedding. Dataset (a) includes writings from non-experts (general writing) and dataset (b) includes writings from experts which also use technical and domain-specific terms.

Kind regards,
Nils

**Comment by simonfelding** [comment]
It's not possible, as the two models cannot be combined meaningfully. UMAP (which does the dimension reduction) is a stochastic algorithm and thus generates different (but similar) results every time. This means that two models cannot be combined, as the results will be in a different space each time. Think of it like the dimensions will not be the same. It's like asking if you can plot the trajectory of a rocket and the trajectory of your life in the same plot. It doesn't have the same units and dimensions and cannot be merged meaningfully. 

In conclusion, you need to create a single model to meaningfully join the datasets. Try looking at the [(semi)-supervised topic modeling tutorial ](https://colab.research.google.com/drive/1bxizKzv5vfxJEB29sntU__ZC7PBSIPaQ?usp=sharing) to see an approach that maybe can help you. You can also look at the [advanced customization tutorial](https://colab.research.google.com/drive/1ClTYut039t-LDtlcd-oQAdXWgcsSGTw9?usp=sharing) for help with customizing parameters, if the defaults don't fit your data. I suggest you try increasing UMAP dimensionality, maybe that would help seperating the topics better. It's the ´n_components´ parameter you want to change for that (default is 10).

**Comment by MaartenGr** [comment]
It is indeed difficult to combine the models themselves as they are trained independently from one another. As mentioned before, you can use the supervised topic modeling approach to assign each dataset either a 0 or 1 to indicate that during training these need to be separated. This might be enough to create some separation between datasets during training but I am not entirely convinced it would. 

However, I do not think you need to create a single model to meaningfully join the datasets. When we reduce the number of topics in a single topic model, we calculate the similarities between the c-TF-IDF representations for each topic and merge those that are similar. We can perform the same process for both topic models by comparing their c-TF-IDF representations and mapping topics that are quite similar to each other. 

To do this, we need to make sure that their c-TF-IDF representations have the same vocabulary, otherwise, we are comparing matrices with a different number of features which complicates things quite a bit. Then, we can use cosine similarity to extract which topics in `model_a` are most similar to the topics in `model_b`. The code for this can be found below:

```python
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from bertopic import BERTopic
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# We create two seperate datasets
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
docs_a = docs[:9000]
docs_b = docs[9000:]; len(docs_a), len(docs_b)

# We make sure that the vocabulary between c-TF-IDF is exactly the same 
# such that we can compare c-TF-IDF vectors between topic models
vectorizer = CountVectorizer().fit(docs)
vocab = vectorizer.get_feature_names()
vectorizer = CountVectorizer(vocabulary=vocab)

# I typically create the embeddings before passing them to BERTopic 
# as it is easier to experiment with parameters
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)
embeddings_a = embeddings[:9000]
embeddings_b = embeddings[9000:]

# Then we fit the two BERTopic models with the same vocab
topic_model_a = BERTopic(vectorizer_model=vectorizer)
topics_a, probs_a = topic_model_a.fit_transform(docs_a, embeddings_a)

topic_model_b = BERTopic(vectorizer_model=vectorizer)
topics_b, probs_b = topic_model_b.fit_transform(docs_b, embeddings_b)

# Mapping topics in a with b if they succeed a similarity of 0.5
sim_matrix = cosine_similarity(topic_model_a.c_tf_idf, topic_model_b.c_tf_idf)
mappings = []
for topic_a in set(topics_a):
    if topic_a != -1:
        topic_b = np.argmax(sim_matrix[topic_a + 1]) - 1
        similarity = np.max(sim_matrix[topic_a + 1])
        
        if similarity > 0.5:
            mappings.append((topic_a, topic_b, similarity))
```

The result of the code above is the variable `mappings`, this variable contains the topics from `model_a` and `model_b` that are very similar to each other. You can check it visually by running the following example:

```python
topic_model_a.get_topic(mappings[0][0]), topic_model_b.get_topic(mappings[0][1])
```

In practice, when you will make predictions for a new document, you will have to pass the document to both models. If model_a predicts a topic found in `mappings` then it is the same topic as model_b would predict. However, if the predicted topics differ from one another, you can use `probs_a` and `probs_b` to select the topic with the highest probability. This allows you to choose the topics both models agree on and select the most probable topic when both models disagree. 

I think this would be a nice solution to your problem but am very curious to hear if it actually is!

**Comment by nilsblessing** [comment]
Thanks for your very detailed and helpful answers! I will think about it again and incorporate your comments.
