### ISSUE TITLE
Suggestion - Take two inputs(#topics, #representative_docs) for the get_representative_docs() function

### ISSUE THREAD

**Issue by rasmus-e-christensen** [MaartenGr/BERTopic#438]
I have been working with BERTopic a bit in my spare time, and I really like the library. 
I was looking through the code and stumpled upon this function, that save the representative documents for each topic.
If you want to check it out yourself here is the permalink for the function :) https://github.com/MaartenGr/BERTopic/blob/05a6790b21009d1704e912e0d9ae22290694cfed/bertopic/_bertopic.py#L1465

        condensed_tree = self.hdbscan_model.condensed_tree_
        raw_tree = condensed_tree._raw_tree
        clusters = sorted(condensed_tree._select_clusters())
        cluster_tree = raw_tree[raw_tree['child_size'] > 1]

        # Find the points with maximum lambda value in each leaf
        representative_docs = {}
        for topic in documents['Topic'].unique():
            if topic != -1:
                leaves = hdbscan.plots._recurse_leaf_dfs(cluster_tree, clusters[topic])

                result = np.array([])
                for leaf in leaves:
                    max_lambda = raw_tree['lambda_val'][raw_tree['parent'] == leaf].max()
                    points = raw_tree['child'][(raw_tree['parent'] == leaf) & (raw_tree['lambda_val'] == max_lambda)]
                    result = np.hstack((result, points))

                representative_docs[topic] = list(np.random.choice(result, 3, replace=False).astype(int))

        # Convert indices to documents
        self.representative_docs = {topic: [documents.iloc[doc_id].Document for doc_id in doc_ids]
                                    for topic, doc_ids in
                                    representative_docs.items()}`

I was wondering why, only the top 3 documents are chosen, and is it really the top 3? Since this is the line that assigns the representative documents to the map between <topic, docs>.
`representative_docs[topic] = list(np.random.choice(result, 3, replace=False).astype(int))`

I do not see the reason of accumulating all the results, based on the nested for loop, and only using 3 random results from this list?

Can some explain the reasoning behind this ? :smile: 

Getting **n** representative documents would give much more sense, I would think :smile:

**Comment by MaartenGr** [comment]
Thank you for the kind words and I can definitely understand the confusion here! 

A little bit of background, the documents that are extracted in `result`  are indeed the most representative documents, or "exemplars", according to [HDBSCAN](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html#distance-based-membership). In the link you will find a bit more about its procedure. 

These exemplars together are the most representative points but one is not more representative than the other. Thus, what happens if you have a cluster of thousands of documents, is that perhaps hundreds of documents are extracted as exemplars. As a result, this might lead to a very large portion of the documents being contained in BERTopic, which is something we want to prevent. Moreover, when we merge two topics, their exemplars are simply added together. So to keep a usable overview of the representative documents, we want to fix the number per cluster. To that end, the top 3 should be more than sufficient in generating a global view of what the topic might entail. The value of 3 also helps when merging topics because if we were to merge a topic 5 times and each has 20 representative documents, then we would get 100 representative documents for that topic which is difficult to interpret.

**Comment by slayeren** [comment]
Thanks for the explanation, I can see the reasoning behind, most of it :smiley: 
But I do not see the reason not to have a function that could get `X` amount of representative documents :) Investigating the rest of the documents could be very interesting.

**Comment by slayeren** [comment]
True :) I was working on an implementation and came to the same conclusion. I am currently working on a recommendation engine which uses, the representative documents, as search results, and that was the reason I wanted to be able to generate more documents from the topics.
