### ISSUE TITLE
No random state

### ISSUE THREAD

**Issue by DivJ** [MaartenGr/BERTopic#47]
Hi,
When I run the model with the same data and the same parameters, I get different clusters. Is there a way to fix random state for reproducibility?

Thanks

**Comment by MaartenGr** [comment]
This is, in part, due to the **stochastic** nature of UMAP. When you run UMAP multiple times, you will get slightly different results each time. Even setting a random_state will not result in a purely deterministic solution, unfortunately. I could add `random_state` as a way to make sure you get somewhat similar results, but I am afraid having a random_state would make people think it is a deterministic approach. 

Also, if I read [this](https://umap-learn.readthedocs.io/en/latest/reproducibility.html) correctly, it seems that by setting a random_state in UMAP you are turning off any of the multi-threading that does not support explicit reproducibility. This means that this might hurt its computational efficiency.

**Comment by jonaslandsgesell** [comment]
Please also have a look at https://github.com/rapidsai/cuml/issues/5099 
In my hands `umap = UMAP(n_neighbors=15, random_state=1, init="random") ` is deterministic.
