### ISSUE TITLE
Any Evaluation Idea for DTM?

### ISSUE THREAD

**Issue by mertozlutiras** [MaartenGr/BERTopic#473]
Hi Marteen,

I checked previous closed issues and read a bit about evaluation. However, I couldn't see much about DTM evaluation. Do you have any idea about what metric to use in order to properly evaluate the performance of the BERTopic DTM model?

**Comment by MaartenGr** [comment]
Evaluating performance in topic modeling is in general quite difficult due to the somewhat subjective nature of the field. It does not mean that it is not possible but defining a metric that works for your specific use case is quite important. To give you an idea, [OCTIS](https://github.com/MIND-Lab/OCTIS) has many topic evaluation techniques implemented used for a variety of use cases. 

The same idea applies to DTM. If you are using it for clustering streams or doing semi-supervised modeling, then those types of evaluation metrics might be interesting to you. 

Having said that, topic modeling, in general, is often evaluated through topic coherence. These coherence measures can be applied to DTM where you evaluate a set of topics at each timestep and average the result. The idea here is that we want DTM to also produce coherent topics, regardless of the timestep. 

Good timing though as I just released a write-up of BERTopic [here](http://arxiv.org/abs/2203.05794) where I focus on `npmi` as a measurement. However, do note that there is not really one "correct" way of doing the evaluation. Quite frankly, I am just one person trying his best to evaluate BERTopic knowing the large limitations of evaluation measures in the domain. So take it all with a grain of salt 😅

All in all, whatever evaluation metric you choose, I highly recommended performing some visual inspection of the resulting topics to get a good feeling of the quality, whatever that means to your use case.

**Comment by mertozlutiras** [comment]
Thanks for the information and the paper. 

In the evaluations part of your paper, you talk about averaging 3 runs. I couldn't understand what it exactly means.
What do you mean by 3 runs? Did you run the algorithm 3 times and averaged 3 results? 
> 
> Table 3: The topic coherence (TC) and topic diversity
> (TD) scores were calculated on dynamic topic modeling tasks. The TC and TD scores were calculated for
> each of the 9 timesteps in each dataset. Then, all results
> were averaged across 3 runs for each step. Thus, each
> score represents the average of 27 values.

Thank you again

**Comment by drob-xx** [comment]
If I'm not mistaken the results from the NPMI evaluations are derived from a stochastic algorithm so that any given run will produce different values. By running them three times and averaging the hope is to get a more representative score.

**Comment by MaartenGr** [comment]
Yes, each algorithm was run 3 times and within each run, we get 9 timesteps for which NPMI scores were calculated. That means we get 9*3=27 values for each algorithm. Like @drob-xx mentioned this is, in part, to average out the stochastic nature of the UMAP algorithm. Another reason for doing so is that you can get quite different results when changing random states in the other algorithms. So each run would get a different seed in order to minimize variation in the results.

**Comment by mertozlutiras** [comment]
Thank you for the answer.

Another question is, for DTM I see you used equal binning.

My documents don't have the same volume for each timestamp. I'm thinking of modifying some parts of the Trainer in order to apply non-equal volume binning. That would work fine right?

**Comment by MaartenGr** [comment]
Sure, that should be no problem if that fits your use case. Do note that the purpose of the code there is for the paper only and that it was not meant for anything else. That definitely does not mean that you cannot adapt it for your own purposes but only that I cannot provide that much support. All in all, I would advise using [OCTIS](https://github.com/MIND-Lab/OCTIS) yourself instead of using the code there.

**Comment by MaartenGr** [comment]
Hmmm, you might be correct! I am not entirely sure but it could be leftover code from an earlier version when I was still experimenting with the pipeline. I will have to check this a bit more in-depth. I will put this on my, unfortunately very long, to-do list to update the code in the notebook. Thanks for mentioning this!
