### ISSUE TITLE
Hyperparameter tuning

### ISSUE THREAD

**Issue by DivJ** [MaartenGr/BERTopic#48]
Hi,
Nice work on the package. I had a question.
The model is a lot sensitive to parameters. I was trying to prepare a pipeline to automatically find the best parameters. I am using outlier_count as my metric. Lower the nos of outliers, better the model.

I want to understand, Is this a right approach?

Thanks!

**Comment by MaartenGr** [comment]
This is a difficult question to answer because it also related to what you want to measure. For example, by using outlier_count you are looking for the best cluster generation which does not have to result in better topics to be created. At times, there are outliers for a reason and by minimizing them you risk outliers being classified as clusters when they shouldn't. 

Given the example above, you might also want to optimize a topic evaluation technique instead, such as topic coherence. This can be evaluated with measures such as `u_mass`, `c_v`, and `c_npm`. Mutual information is also an interesting technique to explore. 

Thus, there is no single right approach. It mostly depends on how you define a "good" topic model and the things you want to optimize for.

**Comment by DivJ** [comment]
How can we extract coherence from BERTopic?

**Comment by MaartenGr** [comment]
That would also depend on which type of coherence you want to be using. In general, you can make use of gensim [here](https://radimrehurek.com/gensim/models/coherencemodel.html). Note that there can be a major speed difference between coherence measures, so make sure to keep that in mind.

**Comment by khairiyah98** [comment]
May I know how we can use gensim with BERTopic? I realized that to get the coherence score, we need to first form a model and corpus using gensim?

**Comment by Priyanka144434** [comment]
May I know how we can use gensim with BERTopic? I realized that to get the coherence score, we need to first form a model and corpus using gensim?
Even I have above same question, may i get answer for this
