### ISSUE TITLE
custom dictionary

### ISSUE THREAD

**Issue by EricJoung1997** [MaartenGr/BERTopic#483]
To make topic words more professional, is it possible to add  custom dictionary? For example, topic 1 has word "machine translation" instead of "machine" and "translation".

**Comment by MaartenGr** [comment]
That is something currently not implemented in BERTopic. However, since topic words are returned with `.get_topic()` or `.get_topic_info()` you could create a dictionary or vocabulary yourself to map them together. Second, you could leverage the `CountVectorizer` and its parameter `vocabulary` to only use words that you want to see in the output.

**Comment by EricJoung1997** [comment]
Thank you very much for your speedy reply, I will consider it.
