### ISSUE TITLE
Recommended approach to topic reduction

### ISSUE THREAD

**Issue by kjaksic** [MaartenGr/BERTopic#496]
Hi, 

my model has extracted 300 topics that, by looking at the keywords, could be further clustered.  The dilemma is whether to reduce topics with "reduce_topics" to some specific integer,  to rerun the model, and change UMAP/HDBSCAN parameters (e.g. to increase min_cluster_size) or to set BERTopic nr_topics to an exact integer or "auto".  

What would be the similarities and differences between those approaches from the mathematical point of view, that is, does reduce_topics with nr_topics = 20 should lead to the same solution as BERTopic with nr_topics = 20 (assuming that topics were extracted using default settings)? Are there any reasons to favourize one approach over the other? 

Thank you for the suggestions.

**Comment by MaartenGr** [comment]
Setting `nr_topics` in `.reduce_topics()` or in `BERTopic()` makes no difference as they are the exact same procedure. However, there is indeed a difference between increasing the `min_cluster_size` and setting `nr_topics="auto"`. The former attempts to create bigger clusters directly from the reduced embeddings, which typically works quite well for generating more abstract topics. The latter is essentially using HDBSCAN to cluster the c-TF-IDF matrix (the topic-term matrix) which focuses more directly on the interpretation of the topics and less so than on the document embeddings. 

Typically, I would advise starting out with increasing `min_cluster_size` until you get a decent amount of clusters, for example, 100, and then inspect them to see if you want to reduce them further based on topic descriptions by using `"auto"`.

**Comment by kjaksic** [comment]
Thank you for the clarification. I agree with the recommended approach.
Setting nr_topics in advance could be a bit problematic to justify, so
setting it to "auto" seems to be a better solution.

sri, 6. tra 2022. u 15:06 Maarten Grootendorst ***@***.***>
napisao je:

**Comment by NateTheGreat001** [comment]
Is there also an option to simply delete some topics?

I am working with a very large sample and running the model with default parameters results in roughly 500 great very specific frequent topics and 19500 infrequent topics that are of no interest to me. This model is very large (16 gb.) and runs very slowly (50 documents per second)

I tried running the model with min_topic_size=300. The result was an appropriate number of very unspecific topics. My guess is that 19500 "junk" topics got pushed into the 500 great topics resulting in 500 less usable topics. This model is also large at 16 gb, but runs much faster (120 documents per second)

My question is do I get to simply delete the junk topics from the first model?

**Comment by MaartenGr** [comment]
@NateTheGreat001 Deleting topics is unlikely to help with speeding up the model in `.transform` as it is not possible to do that easily in the underlying models. Instead, I would either advise using the slower model and use `.merge_topics` to merge all unwanted topics into a single topic, so that it is easier to identify those. Or you can adjust the `min_topic_size` a bit lower to get a balance between helpful topics and speed of the transform function. 

Do note that the transform function can be speed up by a number of different ways. For example, if you have an older GPU then embedding the documents can be much slower. In practice, it is helpful to identify which steps of the algorithm are relatively slow for you. By setting `verbose=True`, you have some indication of the time spent at each of those steps. If UMAP is too slow for you, then you can consider using PCA instead.

**Comment by Hari25483** [comment]
Hi @MaartenGr  
Can we specify no. of topics that we want explicitly?

**Comment by MaartenGr** [comment]
@Hari25483 There are a number of ways to approach this:

1. You can approximate the number of topics by setting the `min_topic_size` parameter. Increasing its value creates fewer topics. 
2. You can set `nr_topics` to whatever you like which will reduce the number of topics that were originally created by iteratively merging them. You can find more about that in the documentation [here](https://maartengr.github.io/BERTopic/getting_started/topicreduction/topicreduction.html).
3. You can use k-Means instead of HDBSCAN, which allows you to set the number of clusters/topics that you want. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/clustering/clustering.html#k-means). 

Most importantly, I would advise starting from reading through [the underlying algorithm](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) to get an intuitive feeling about BERTopic and how you can approach fine-tuning it.

**Comment by francyya** [comment]
> Setting `nr_topics` in `.reduce_topics()` or in `BERTopic()` makes no difference as they are the exact same procedure. However, there is indeed a difference between increasing the `min_cluster_size` and setting `nr_topics="auto"`. The former attempts to create bigger clusters directly from the reduced embeddings, which typically works quite well for generating more abstract topics. The latter is essentially using HDBSCAN to cluster the c-TF-IDF matrix (the topic-term matrix) which focuses more directly on the interpretation of the topics and less so than on the document embeddings.
> 
> Typically, I would advise starting out with increasing `min_cluster_size` until you get a decent amount of clusters, for example, 100, and then inspect them to see if you want to reduce them further based on topic descriptions by using `"auto"`.

Hi @MaartenGr From what I understand is that, when using nr_topics = "auto",  another HDBSCAN is used on top of C-TF-IDF matrix for further topic reduction. In this case, two clustering algorithms used in total, one in general BERTopic workflow and the other in topic reduction flow, am I correct?

**Comment by MaartenGr** [comment]
@francyya That is correct! You can find more about that here: 

https://github.com/MaartenGr/BERTopic/blob/8ba36e3b35c2a292ebc4c04a225e44b47d1fe818/bertopic/_bertopic.py#L3662

**Comment by Wannes15** [comment]
Hi @MaartenGr ! I have a question about how the reduce_topics function actually works. In the documentation you state that it iteratively takes the smallest cluster/topic and merges it with the most similar one, just like top2vec's hierarchical_topic_reduction function. However, when inspecting BERTopic's source code I noticed you make use of agglomerative clustering in the _reduce_to_n_topics function which iteratively finds the two most similar clusters to merge without caring about the cluster size if i'm correct?

**Comment by MaartenGr** [comment]
@Wannes15 I'm not familiar with what Top2Vec is doing but I changed it a while ago since it would merge topics together that do not really match. For instance, if you have a very specific and small topic, merging it with the closest (although still very distinct) other topic would result in more messy topics. Thus, I indeed opted for a clustering technique that would focus more on the similarity between clusters rather than reducing the number of micro clusters. 

That said, could you share where you found that piece of documentation? It seems that it should be updated then!

**Comment by VoidTrekker** [comment]
Hi @MaartenGr,

Thank you for developing BERTopic — it's a powerful tool, and I've found it very helpful for analysing open-ended survey data on social representations.

I have a question regarding topic reduction. I understand that you suggest either specifying the number of topics or using HDBSCAN for automatic reduction. However, my use case requires a slightly different approach:

- I would like to retain more granular topics initially (i.e. not increase `min_cluster_size`) to observe how documents are distributed along the topic hierarchy and possibly apply supervised learning later.
- At the same time, I would like to reduce the number of topics in the final stage without predefining an exact number (e.g. I currently get 450 topics from 1,500 respondents, which is too many).

To address this, I’ve tried iteratively applying automatic topic reduction, but this is difficult to justify methodologically.

I am now considering using the topic hierarchy and its associated distance matrix to perform hierarchical clustering with different indices (e.g. silhouette, Davies-Bouldin) and then use majority voting across these indices to determine the "optimal" number of topics.

Does this sound like a reasonable approach? Or is there an existing way in BERTopic to achieve something similar?

Thanks very much in advance for your enlightenment.

**Comment by MaartenGr** [comment]
@VoidTrekker Thank you for the kind words!

If I'm not mistaken, considering you would want to see the granular topics first, you can perform automatic topic reduction **after** training the initial model. This allows you to see topics first after running `.fit` (so without `nr_topics`).

After that, you can always run `.reduce_topics` using automatic topic reduction which should reduce it without having to specify a certain value.

Your suggestion also sounds valid. The topic hierarchy is another way of approaching this automatic reduction and if you have predefined metrics, then that would be preferred.
