### ISSUE TITLE
Tipo in _extract_words_per_topic()

### ISSUE THREAD

**Issue by GriesserP** [MaartenGr/BERTopic#506]
Hello Maarten thank you for your incredible contribution,
I think that there is a typo in the file bertopic/_bertopic.py line 1644:  if word_index and score > 0
If word_index is 0 because we are looking at the first word of the vocabulary we won't consider this word due to the condition. I would replace the line by if word_index is not None and  score > 0
What do you think?

**Comment by MaartenGr** [comment]
Good catch! It seems that I completely missed this. I am currently working on a new release and I'll make sure it gets fixed in that PR, so there is no need to make a new PR but thanks for catching this. Since the resulting vocab is typically quite large, I think the effect was quite small since one word in tens of thousands of words was missing. This also explains why this has not been caught before and I am quite sure I would not have caught this in the future!
