### ISSUE TITLE
Still different results from argmax(probs) to topics

### ISSUE THREAD

**Issue by Hannah-key** [MaartenGr/BERTopic#518]
Hello Maarten,
Thank you for the opportunity of the Bertopic library! It seems to have a lot of potential. 

I was trying to use `calculate_probabilities=True` and found that for many documents in my dataset the following is not true:
`np.argmax(probs[doc_id]) == topics[doc_id]`
meaning that the topic suggested in the `topics` variable is not necessarily the one with the maximum probability in the `probs` variable for each document.
Can you give me a little more information as to why that might be?

I have read about the [issue with the mapping from last year](https://github.com/MaartenGr/BERTopic/issues/146) but I understand that this has been solved by [v0.9](https://github.com/MaartenGr/BERTopic/pull/176). 

It would be great, to read from you.

**Comment by MaartenGr** [comment]
Thank you for the kind words!

> meaning that the topic suggested in the topics variable is not necessarily the one with the maximum probability in the probs variable for each document.
Can you give me a little more information as to why that might be?

Yes! As it turned out, there were actually two issues with respect to the probabilities. One of them was solved with the v0.9 release as there were some issues with mapping the probabilities after reducing the number of topics. 

What remained is possibly the way HDBSCAN generates its probabilities. These probabilities are generated after having generated the labels and, if I understand correctly, do not perfectly emulate the clusters they were assigned to. It has been mentioned in another issue [here](https://github.com/MaartenGr/BERTopic/issues/485#issuecomment-1081424019). 

You can find a bit more about how HDBSCAN handles soft clustering [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering.html) and [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering_explanation.html)

Also, just a quick note `np.argmax(probs[doc_id]) == topics[doc_id]` will not work for outliers and might overestimate the number of incorrect matches.

**Comment by Hannah-key** [comment]
That makes it clear for me. Thanks a lot for the quick and elaborate answer!
(Also thanks for the remark about the outliers. My calculations were taking this into account, already, but it is always good to mention!)

**Comment by LeoPerelli** [comment]
Hello, reopening the issue for small issue related to the computed probabilities when setting `calculate_probabilities=True`.
We can find the new topics with:
`import numpy as np`
`probability_threshold = 0.01`
`new_topics = [np.argmax(prob) if max(prob) >= probability_threshold else -1 for prob in probs]`
 
However, is there a way to update the topic model with the new_topics? That is, recomputing the topic representations etc
Thanks!

**Comment by MaartenGr** [comment]
@LeoPerelli You can use `.update_topics` for updating the topic representations. You can find more information about that [here](https://github.com/MaartenGr/BERTopic/issues/485#issuecomment-1136047148).
