### ISSUE TITLE
Using COVID-Twitter-BERT (CT-BERT) 

### ISSUE THREAD

**Issue by khairiyah98** [MaartenGr/BERTopic#52]
Hi, firstly thank you so much for this library! :)

I am interested in performing topic modelling using tweets related to COVID-19, and I was wondering if it is possible to integrate the CT-BERT model (from [https://github.com/digitalepidemiologylab/covid-twitter-bert](url)) into BERTopic? And if it is indeed possible, how can I go about doing so?

Your help would be very much appreciated! Thank you in advance.

**Comment by MaartenGr** [comment]
Currently, this is only possible by generating the embeddings yourself and then passing them through `model.fit_transform(docs, embeddings)`. Having said that... I am currently working on v0.5 (#46) which allows you to use `Flair` package in order to easily use huggingface transformer embeddings. 

I am aiming to complete this in the coming week 😄

**Comment by khairiyah98** [comment]
I see, alright thanks!

**Comment by MaartenGr** [comment]
@khairiyah98 It took a while but v0.5 is finally here! You can now use both custom `SentenceTransformers` and `Flair` models which allows you to use all 🤗 transformer models. You can find the changelog [here](https://maartengr.github.io/BERTopic/changelog.html) and the tutorial for using custom embedding models [here](https://maartengr.github.io/BERTopic/tutorial/embeddings/embeddings.html). Hopefully this helps you out a bit. If not, please let me know!
