### ISSUE TITLE
Best Strategy for Bootstrapping different parameters

### ISSUE THREAD

**Issue by Minyall** [MaartenGr/BERTopic#520]
Hello! First thank you for creating this package. Up to now I'd been homebrewing my own combinations of vectors, UMAP and HDBSCAN but this makes it far easier to work with them all.

I wanted to ask some advice on using the tool. Currently it takes about 2 hours to complete the embeddings for my corpus with the default sentence transformer. This is fine if done just once, but often I have run the model, got to the end and found that maybe I need to go back and try out tweaking some of the UMAP or HDBSCAN parameters. Is there a canonical way to do this without simply initialising a new model and starting from scratch?

So far I have actually edited the code so that `.fit_transform` also spits out the original embeddings. I've saved those to disk, so that later I can  pass them into the `embeddings` argument of the `.fit_transform` method after initialising a new model with new parameters. This speeds things up immensely as it only takes a few seconds to run UMAP and HDBSCAN. However I realise this may not the intended usage and so might be setting myself up for a bug or two.

So to get to my question: Is there an expected way in which I should be experimenting with parameters whilst avoiding re-generating document embeddings every time?

**Comment by MaartenGr** [comment]
Thank you for your kind words!

If I understand your use case correctly, there is actually no need to edit the `.fit_transform` as it already allows you to pass in embeddings that you have created previously. Fortunately, it is rather straightforward to do: 

```python
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Train our topic model using our pre-trained sentence-transformers embeddings
topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs, embeddings)
```

After generating `embeddings`, you can save them with `np.save` and load them in whenever necessary. Then, you can simply pass those `embeddings` to `.fit_transform()` together with your documents. When doing so, the `embeddings` will not be re-generated and the embedding step will be skipped therefore speeding up training and testing your model. 

Hopefully, this helps a bit!

**Comment by Minyall** [comment]
Yes this is very helpful thanks. Presumably your package is somewhat independent when it comes to what kind of vectorisation procedure is used, so in theory I could use Doc2Vec to generate my document embeddings, pass in the array and everything would work as expected?

**Comment by MaartenGr** [comment]
Yes, since BERTopic separates the process of finding topics and representing topics the choice of embeddings is up to the user. In other words, you can use whatever embedding or vectorization technique as long as it is accurate in representing the corresponding documents. I would typically advise using SBERT embeddings as they work quite well in capturing the semantic and contextual nature of documents. However, each use case is different and other embedding models might work better for you. 

If you want to pass the embedding model to BERTopic in order to also use MMR, you can follow along with the guide [here](https://maartengr.github.io/BERTopic/getting_started/embeddings/embeddings.html) for an overview of possible embeddings models and, if necessary, you can create your own custom embedding model [here](https://maartengr.github.io/BERTopic/getting_started/custom_embeddings/embeddings.html).

**Comment by Minyall** [comment]
Very helpful thanks! Yes I have quite a specialist corpus I'm looking at so I'm uncertain whether pre-trained models are the way to go and would like to experiment with other options. These links look very helpful for doing that. I'm going to close now as my question is more than answered.
