### ISSUE TITLE
Automatically divide topics_over_time into months

### ISSUE THREAD

**Issue by cb-pratibhasaha** [MaartenGr/BERTopic#523]
I have a dataframe with timestamps at seconds/minutes/hour level. I fit BERTopic on the the text(Each row has textual data)and each row is now assigned to one of the topics. I want to visualise the topics over time at a monthly level. How do I use the nr_bins parameter(DTM) in a way that it automatically counts the frequency of topics on a month by month basis without me having to explicitly define it by trial and error. Can pd.Grouper be used for the same? 

Would really appreciate your help on this. Thanks!

**Comment by MaartenGr** [comment]
You would indeed have to transform your timestamps from the seconds/minutes/hour level to a monthly level in order to visualize the topics over time at a monthly level. It does depend on the type of timestamps you have (datetime, timestamp, etc.) on how you can transform them as such but I would not advise you to use `nr_bins` as that would indeed require some trial and error. 

Thus, transforming your timestamps directly to months should work.

**Comment by cb-pratibhasaha** [comment]
I tried to create a dictionary of the dataframe where each key corresponded to each month. Then,I took the length of that dictionary to use as the nr_bins value but that doesn't seem to work either. 
My timestamps are in the dd/mm/yyyy hh/mins/seconds form. 

How do you suggest I proceed? I want to visualise the top 10 topics over time on a monthly level without having to hardcode each topic one by one.

**Comment by MaartenGr** [comment]
> Then,I took the length of that dictionary to use as the nr_bins value but that doesn't seem to work either.

I would advise not using `nr_bins` at all but keeping that value empty. Then, make sure that the timestamps that you pass to `topics_over_time` are months and not `dd/mm/yyyy hh/mins/seconds`. 

In other words, perform the following without using `nr_bins`:

```python
topics_over_time = topic_model.topics_over_time(tweets, topics, timestamps)
```

Here, `timestamps` contains your list of timestamps but instead of the `dd/mm/yyyy hh/mins/seconds` format it is `mm/yyyy`  or `mm` instead.

**Comment by cb-pratibhasaha** [comment]
This was hugely helpful. Thank you!
I wanted to ask why do I get different clusters each time I fit BERTopic on the data? Is there a way to keep the clusters constant for the same data?

**Comment by MaartenGr** [comment]
The underlying dimensionality reduction algorithm, UMAP, is stochastic. This means that each time you run BERTopic, you will get different results. You can find a bit more about that [here](https://maartengr.github.io/BERTopic/faq.html) and how to keep the clusters constant.
