### ISSUE TITLE
Problems with model.visualize_topics()

### ISSUE THREAD

**Issue by mediote** [MaartenGr/BERTopic#533]
Topic number 0 does not appear when using topic model.visualize_topics(), however in model.get_topic_info(), it appears.
I'm using the latest version of BERTopic.

**Comment by MaartenGr** [comment]
Thank you for posting this! It seems that I intended to remove outliers in two places, which instead removes the first actual topic. I'll make sure to fix this in the next release!

**Comment by MaartenGr** [comment]
I just pushed the fix to the master branch, so you can get it already there! The next release might take a while but for now, you can get the most recent version there.

**Comment by mediote** [comment]
In that case, which will  topic number indicate the outlier cluster?

**Comment by MaartenGr** [comment]
Typically, `-1` represents the outlier cluster but the documents contained do not actually represent a topic or cluster. For the sake of simplicity, it was added as a topic but is not something that is easily interpretable. Therefore, it is excluded from the visualizations since it is actually not something that should be compared with the other topics.
