### ISSUE TITLE
Ideal document length and special character handling

### ISSUE THREAD

**Issue by psyronika** [MaartenGr/BERTopic#540]
Hi Maarten,

Thanks so much for this great tool! It is such a huge step-up from LDA topic modeling. 

I am trying to perform topic modeling on about 2 million text messages. The length of the documents varies between a few tokens (e.g., emojies) to 8000 tokens at times. Although I managed to make BERTopic work by first fitting to a random but representative sample of 300K documents and then fit transforming to the complete dataset, the process is slow and cumbersome even though I am working on a dual GPU-base environment with CUDA (Sampling was necessary as I ran into memory issues when I tried running it on the entire dataset). 

I have a few questions:
1.) I was wondering fo there are any other downsides to working with long documents apart from the fact that it is highly computationally expensive? And if so, what would be the ideal length for a document?  
2.) I am concerned that if I split up the longer documents into sentences I will obtain less coherent topics or will lose some meaning. Is this the case?
3.) What about emojis? Does BERTopic consider them or should one 'demojize' the text first (i.e., replace unicodes with their verbal meanings?

Thanks a lot in advance!

**Comment by MaartenGr** [comment]
> Thanks so much for this great tool! It is such a huge step-up from LDA topic modeling.

Thank you for your kind words!

> 1.) I was wondering fo there are any other downsides to working with long documents apart from the fact that it is highly computationally expensive? And if so, what would be the ideal length for a document?

The main downside with working with longer documents is that information will be ignored if the documents are too long. Some models only take in a maximum of 384 tokens and anything longer than that will be cut off. 

The base model, `all-MiniLM-L6-v2` works quite well if either sentences or paragraphs are being fed to the model. So converting long documents to sentences and/or paragraphs is preferred. 

> 2.) I am concerned that if I split up the longer documents into sentences I will obtain less coherent topics or will lose some meaning. Is this the case?

I actually think you will get much more coherent topics by splitting them up into sentences. Imagine that you pass in a long document that you are convinced contains several different topics. Since BERTopic follows essentially a clustering approach, it will assign only a single topic to that document which should contain several topics. By splitting it up into sentences, we can assume that each sentence contains a single topic so a document, containing multiple sentences, may contain multiple topics. As a result, the topic representation is likely to be more accurate. 

> 3.) What about emojis? Does BERTopic consider them or should one 'demojize' the text first (i.e., replace unicodes with their verbal meanings?

Interesting question, the base model, `all-MiniLM-L6-v2`, is trained on Wikipedia data which contains little emojis. So I do not think the model will have encoded much of the semantic meaning. 

You could replace them with their verbal meanings but you will be missing some of the contexts in which the emoji were found. Emojis can also be highly contextual, so you might be encoding them incorrectly by replacing them with their verbal meaning. I would start by not doing anything with the text first and see what the results look like. 

I should note that BERTopic does very slight preprocessing if `language="english"` and if you have not set an `embedding_model`:

https://github.com/MaartenGr/BERTopic/blob/407fd4fdf2e05e80019c1c217972bf3314a41040/bertopic/_bertopic.py#L1887

It might be worthwhile to set `embedding_model=SentenceTransformer("all-MiniLM-L6-v2")` in order to prevent the preprocessing steps above so that emoji will be put in the topic representation.

**Comment by psyronika** [comment]
Thanks a lot @MaartenGr! I will this a go.

**Comment by esettouf** [comment]
Another question regarding splitting documents into sentences. When generating one topic per sentence of a document, how do you get the e.g. three most dominant topics of one document if it is split up into sentences?

**Comment by MaartenGr** [comment]
@esettouf If you split up the document into sentences, it is important that you track the document ID for all sentences. That way, you know which sentences belong to which documents. Then, you will have a list of sentences for each document and a list of topics for each document. Using that list of topics, you can simply count which topics are most frequent.

**Comment by esettouf** [comment]
That's a good idea. I will do that, thanks!

**Comment by esettouf** [comment]
Hi @MaartenGr, I tried to find out how to assign the topics to my documents, but couldn't figure out how to do it.

I have a collection of sentences with the associated document ID. To train the BERTopic model I only selected the sentences.
Using get_topics() you can get all the topics. As the trained model doesn't contain the data, you can use visualize_documents() to plot the topics to the sentences. But I would ideally need a list with sentences and the topic they contain to map them to their documents.
What am I missing? Could you give me another tip?

**Comment by MaartenGr** [comment]
@esettouf I would advise reading through [this](https://github.com/MaartenGr/BERTopic/issues/634#issuecomment-1193351167) post where some guidelines are given on how to combine the input documents with the topics.

**Comment by esettouf** [comment]
Great, that's exactly what I needed to understand. Thanks!
