### ISSUE TITLE
PicklingError: ("Can't pickle <class 'numpy.dtype[float32]'...

### ISSUE THREAD

**Issue by CharlyWargnier** [MaartenGr/BERTopic#55]
Hi Maarteen,

I love BERTopic! 

Yet, I'm facing this error (CPU, local machine)

![image](https://user-images.githubusercontent.com/27242399/107102218-b9733500-6811-11eb-9742-8cbfbda8ea4d.png)

Is this expected?

Thanks,
Charly

**Comment by MaartenGr** [comment]
This is a known issue with the order of install using pypi. You can find more details about this issue [here](https://github.com/scikit-learn-contrib/hdbscan/issues/457).

I would suggest doing one of the following:
* Install the newest version from BERTopic [here](https://github.com/MaartenGr/BERTopic/pull/46). Although this is in development, it is only a few days away from being published to pypi
* You can install hdbscan with `pip install hdbscan --no-cache-dir --no-binary :all: --no-build-isolation` which might resolve the issue
* Use the above step also with numpy as it is part of the issue
* Install BERTopic in a fresh environment using [these](https://github.com/MaartenGr/BERTopic/pull/46#issuecomment-773562889) steps. Doesn't have to be in a fresh environment, as long as the packages are installed in the correct order. 

Hopefully, this solves your issue. The new release should be much more stable and will be released in a few days.

**Comment by MaartenGr** [comment]
@CharlyWargnier I just released BERTopic v0.5 which should make installing the package a bit more stable. It is suggested to create a fresh environment before trying out this new release. If this does not work, please let me know!

**Comment by CharlyWargnier** [comment]
Thanks so much Maarten!
I will try again and feed back here :)
Charly

**Comment by CharlyWargnier** [comment]
Feedback: Re-installed now and working fine. Thanks again! :)

May I just ask, via the default settings, topic clustering seems rather inaccurate with *small* datasets. For instance, I've had very mixed results with a list of 1000 keywords (1 to 3 n grams max per keyword).

Is this expected? Would it only work with larger lists? And if so, is there a way to improve this? Maybe changing the default model to another one, or another setting?

Thanks in advance.

Also, fantastic work on that library, keep it up Maarten! :)




#######################

**Comment by MaartenGr** [comment]
Great to hear that it works now! 

There are several reasons why this happening. First, BERTopic is not meant to take in a list of keywords, but a list of documents. Especially with the c-TF-IDF procedure, it would not make sense to use lists of keywords unless there are several duplicates to be found. c-TF-IDF works great when there is a lot of information about each document, more than just their keywords. Second, when using a very small dataset you'll also need to adjust the hyperparameters of the model. For instance, if you leave the `min_topic_size` as is, then there is a good chance no topics would be found. I would highly suggest lowering this value until you find more interesting topics. Third, as you mentioned yourself, it might be interesting to increase the amount of data. Because I am using HDBSCAN, a significant part of the data will typically not fall into any clusters but are considered to be outliers. In practice, this means that you can cut the number of topics in half which further decreases the amount of data. 

Also, it might be an idea to look through the FAQ and documentation [here](https://maartengr.github.io/BERTopic/faq.html) as it may contain some helpful tips about hyperparameter tuning and use-cases. 

Thanks! Let me know if you run into any issues, I'll make sure to help out where I can.

**Comment by plugiery** [comment]
Hello Marteen.
I am getting a PicklingError which could be somehow related to this thread.
As mentioned in this issue I ran the following command

![image](https://user-images.githubusercontent.com/83005444/165755292-939e6736-ae4c-4a6e-a552-1a3136f12155.png)

 
Corpus bert is a list of string
 

![image](https://user-images.githubusercontent.com/83005444/165755292-939e6736-ae4c-4a6e-a552-1a3136f12155.png)

This is the configuration I used
 
![image003](https://user-images.githubusercontent.com/83005444/165755480-5cce6b73-0c70-44e7-a00c-fd3b25fa204d.png)

The error is
 
![image004](https://user-images.githubusercontent.com/83005444/165755566-12a2ad5e-41a1-4d7b-880e-ba2fd52ebbf9.png)
![image005](https://user-images.githubusercontent.com/83005444/165755570-884106ad-62a2-4ff1-9bae-748d3c840778.png)
![image008](https://user-images.githubusercontent.com/83005444/165755572-5d1bdd36-ab85-42c5-b398-3eeddb333eeb.png)
![image009](https://user-images.githubusercontent.com/83005444/165755574-ce6ed85a-d5a4-45a2-8db9-3f798b6496fd.png)
![image010](https://user-images.githubusercontent.com/83005444/165755577-f7e65507-39cd-4f75-b155-458973e8d17b.png)
![image011](https://user-images.githubusercontent.com/83005444/165755581-b4114dfd-9df7-49d5-972a-13293e47f92b.png)
![image012](https://user-images.githubusercontent.com/83005444/165755582-21cf9f65-ea22-430e-a007-9352faaa092f.png)
![image015](https://user-images.githubusercontent.com/83005444/165755588-66f2e000-e826-40d6-b5e0-69e828427d0f.png)


Is there any chance you understand what is going wrong
Thank you in advance and congrats again for that amazing lib!
Pierre-Louis

**Comment by MaartenGr** [comment]
@plugiery This might be related to the issues that can be found [here](https://github.com/MaartenGr/BERTopic/issues/517) and [here](https://github.com/lmcinnes/umap/issues/477#issuecomment-862017068). Especially the latter has some tips that might be useful in your case.
