### ISSUE TITLE
ngram count when merging topic docs in single doc

### ISSUE THREAD

**Issue by LeoPerelli** [MaartenGr/BERTopic#563]
Hello, I noticed that when I specify n_gram_range=(1,3) some ngrams pop out which are not present in any documents. I believe that this happens when merging documents from the same cluster in one big doc to compute the c-TF-ICF. 

If doc1='Hello world' and doc2='flat table', right now I expect 'world flat' bigram to have count 1, even if it does not appear in any original docs. Is this intended behaviour? Thanks!

**Comment by MaartenGr** [comment]
Yes, since documents are joined together and regarded as a single document there is a chance that some words appear that are not found in the original documents. Having said that, there is another reason this might be happening. When you use the CountVectorizer as is, it cleans the documents and disregards some punctuation which also might result in words being put together that are not directly next to each other in the documents. 

In practice, this should not have a big influence on the topic representations. However, you can use `CountVectorizer(min_df=2)` to remove those infrequent words if you do not want them in the vocabulary at all.

**Comment by LeoPerelli** [comment]
Indeed I noticed this because I was dealing with extremely short documents, but generally I agree it shouldn't influence the topic representations, just wanted to make sure it was a know and documented behaviour.
Thanks for your time!
