### ISSUE TITLE
Use SentenceTransformer through Flair 

### ISSUE THREAD

**Issue by oterrier** [MaartenGr/BERTopic#57]
Hi Maarten
Thx again for this great package and the 0.5 release is just amazing.
Regarding Flair vs SentenceTransformer maybe it could be interesting to always use Flair even for SentenceTransformer:

Flair has a top level class DocumentEmbeddings and several implementation among
``` 
TransformerDocumentEmbeddings
SentenceTransformerDocumentEmbeddings
DocumentTFIDFEmbeddings
DocumentPoolEmbeddings
```
What do you think?

Best regards

Olivier

**Comment by MaartenGr** [comment]
Hi @oterrier, thank you!

This has been something I have been thinking about implementing for a while but decided against it for several reasons. 

First, Flair has a rather long list of dependencies that may overcomplicate the installation and usage of BERTopic. This could quickly result in version conflicts. I wanted to keep the base package as simple as possible with the option of extending it. Using Flair only requires `pip install bertopic[flair]` so that should be no problem. 

Second, overall, sentence-transformers are amazing document embeddings and should work for most use-cases. If you were to be using Flair as a base, then that opens too many options for some users. 

Third, the inference speed of sentence-transformers is much faster than that of Flair since the `Sentence` structure of Flair can quickly lead to memory issues if not handled carefully. That does not mean that Flair is by itself is slow but simply that `sentence-transformers` is a great first place to start with using embeddings. 

Fourth, using Flair requires more knowledge about embeddings than sentence-transformers. Some of the questions that have been asked previously demonstrated that not all users fully understand the inner workings of Flair, which makes sense. Therefore, using sentence-transformers with only a few models makes it easier for users to start with topic modeling. 

In sum, sentence-transformers keep BERTopic simple to use for beginners and those with more in-depth knowledge about transformer models can use Flair instead.

**Comment by oterrier** [comment]
OK Maarten crystal clear !
