### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by brianferrell787** [MaartenGr/BERTopic#588]
Hello I am getting the following error when I run your code from Tutorial - (Custom) Embedding Models in BERTopic

I did not change anything, but got this indexing error

Imported everything with:
%%capture
!pip install bertopic[flair, gensim, spacy, use]

![image](https://user-images.githubusercontent.com/58923369/176687206-794b9101-1f19-4ad1-9e80-e01c36f6921c.png)

**Comment by brianferrell787** [comment]
Martin, I reopened it and ran it again and it seems to be working... maybe I just did something weird with it.

**Comment by Sudo-Truman** [comment]
I have come across this error before as well. Is there some behavior of the model that causes this to occur occasionally?

**Comment by MaartenGr** [comment]
@brianferrell787 Sorry for the late response!

I am not entirely sure but I believe this issue is a result of not re-starting the Google Colab notebook after installing BERTopic. After you install BERTopic in Google Colab, you will need to re-start the notebook in order for the correct versions of the installed packages to be used. What typically happens is that specific versions of packages are already loaded in when you start the notebook. So whenever you upgrade those packages, they need to be re-loaded.
