### ISSUE TITLE
Export data of scatter plots after filtering

### ISSUE THREAD

**Issue by doubianimehdi** [MaartenGr/BERTopic#602]
Hi !

I was wondering if there was a way to export for example in csv files, the data of a scatter plot (for example the documents in a topic) after using the filters of plotly (double click on a topic ?)

Thank you for your insight !

**Comment by MaartenGr** [comment]
I believe that with pure Plotly that is not possible as of this moment. It might be interesting to look at the recently released [bulk](https://github.com/koaning/bulk). It is a package for bulk labeling but does allow you to select a section of the graph and export it to CSV. It uses Bokeh instead of Plotly which allows for those events to be registered.
