### ISSUE TITLE
model.transform does not return probabilities for new documents

### ISSUE THREAD

**Issue by makkasu** [MaartenGr/BERTopic#61]
```
rl_bertopic_model = BERTopic(language="english")
rl_bertopic_model = rl_bertopic_model.load(f'models/{model_name}')

new_doc = [r"some text"]

new_doc_topics, new_doc_probabilities = rl_bertopic_model.transform(new_doc[0])
```
`new_doc_probabilities` is `None` on 0.5.0 but it works fine on 0.4.3. This is the case regardless of whether the model is trained fresh or loaded from file.

I'm assuming this is related to the [`low_memory` option](https://maartengr.github.io/BERTopic/api/bertopic.html#bertopic._bertopic.BERTopic.transform) introduced in 0.5.0. The wording here seems backwards: "If low_memory in BERTopic is set to **False**, then the probabilities are **not calculated** to speed up computation and decrease memory usage." - is this how it works? Seems like it should be the other way around.

Thanks

**Comment by MaartenGr** [comment]
The models are not interchangeable between 0.5.0 and 0.4.3. This means that loading a model from 0.4.3 into 0.5.0 is unlikely to work, especially since parameters differ and the API changes frequently between major updates. 

If you want to calculate the probabilities in v0.5, you should set `calculate_probabilities` to True. It is set to False as a default because it is computationally an inefficient process in HDBSCAN which can result in a significant increase in running times. 

Good catch on the wording in the documentation! That seems to be left-over from 0.4.3 when `low_memory` and `calculate_probabilities`  were still combined. I'll make sure to chance it in v0.6.0 which is currently in the works.

**Comment by makkasu** [comment]
Thanks very much for the swift response! Didn't spot the calculate_probabilities thing, that seems to have done the trick. Cheers
