### ISSUE TITLE
Error when install on windows

### ISSUE THREAD

**Issue by spasaria** [MaartenGr/BERTopic#62]
Hi everyone,
when i try to install bertopic on windows (**pip install bertopic**) i get an error. The problem arises on this line: " Building wheels for collected packages: **hdbscan**".
The next line is:  Building wheel for hdbscan (PEP 517) ... error
...
ERROR: Failed building wheel for hdbscan
Failed to build hdbscan
ERROR: Could not build wheels for hdbscan which use PEP 517 and cannot be installed directly.

I tried to use different python version (3.5 - 3.6 - 3.7) but nothing has changed.
Did someone have the same problem and solved it?
Thank you all,

Andrea.

**Comment by MaartenGr** [comment]
If I am correct, there should be the following error/message prior to the error you encounter, namely:
`"error: command 'gcc' failed with exit status 1"` 

There are several things that you can do to fix this error:
* You do not have a C++ compiler installed which can be fixed by downloading [Installing Visual C++ Build Tools](https://visualstudio.microsoft.com/downloads/)
* Install HDBSCAN via conda/miniconda: `conda install -c conda-forge hdbscan` 
* Finally, there is a thread [here](https://github.com/pydata/bottleneck/issues/281) which discusses similar issues in detail 

Hopefully, the above will help you out a bit!

**Comment by spasaria** [comment]
Thank you @MaartenGr for the precious help. I installed c++ compiler and then installation is successful completed. 
Sincerely,

Andrea.

**Comment by TobiasKlm** [comment]
Just as a sidenote: if you're having troubles installing the visual C++ Build Tools, this did the job for me https://github.com/bycloudai/InstallVSBuildToolsWindows
