### ISSUE TITLE
Get topics After merge_topics() ? 

### ISSUE THREAD

**Issue by yukyunglee** [MaartenGr/BERTopic#636]
Hello! First of all, thank you for releasing a great library 🙂 I have a question about the `merge_topics` function.

The `merge_topics` has been added from version 0.11.0, which is very useful. However, **since the `merge_topics` function does not have a return value**, I think that it is difficult to extract the topic for each document directly after the method is executed.

Is there any way to get topics without `fit_transforms` after `merge_topics`? Since the topic is merged from the original topic data frame, it is not appropriate to obtain the probability, but it would be good if the topic label for each document was returned.

The expected return form is as follows, but before the pull request, I wanted to ask if there is a method I am unaware of, so I left an issue.
```
def merge_topics(
    self,
    docs: List[str],
    topics: List[int],
    topics_to_merge: List[Union[Iterable[int], int]]) -> None:
  
    ...
    
    merged_topics = documents.Topic.to_list()
    
    return merged_topics
```

Thank you !

**Comment by MaartenGr** [comment]
That is indeed something that is not entirely user-friendly right now! What I am actually working on is creating a dedicated function/variable that allows you to easily extract the current state of the topics. That way, we can track the topics within BERTopic instead of having to rely on local variables. Similarly, this will then also improve the way you can access the topics after saving and loading the model. Although the PR is highly appreciated, it might only be a temporary fix. For now, 
you can access the updated topics with:

```python
topics = topic_model._map_predictions(topic_model.hdbscan_model.labels_)
```

**Comment by yukyunglee** [comment]
Thanks! It works well 😇!!
