### ISSUE TITLE
how to customise the topics number?

### ISSUE THREAD

**Issue by Chriszhangmw** [MaartenGr/BERTopic#646]
Hi, my data it has 33 classes, but when I put it into bertopic and results in only one topic or two topics, how should I specify the fixed topic size?

**Comment by MaartenGr** [comment]
If you want to fix the topic size, I would advise using an algorithm like k-Means in BERTopic instead of HDBSCAN. k-Means allows you to select the number of clusters generated, and thereby the number of topics. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/clustering/clustering.html).
