### ISSUE TITLE
Data pre-processing

### ISSUE THREAD

**Issue by MichaelMMeskhi** [MaartenGr/BERTopic#662]
@MaartenGr This might be off topic (pun intended) but I wanted to have a conversation with you about something I noticed. In general, for transformer based models, minimal pre-processing is needed. Based on data I have, I have noticed the following:

1. Removing stop words post embedding helps.
2. Breaking down text actually generates more intuitive topics.
    - For instance given a text `"I love apples but not planes. I don't think this is a good farm."`
    - Broken into `["I love apples", "not planes", "I do not think this is a good farm"]` # Using various methods to achieve this
    - I notice much better results and more coherent topics.
    - One caveat, my data is very short in length. One or two sentences at most.

I wanted to hear your opinion on this and if there is anything similar you have encountered or heard of in NLP?

**Comment by MaartenGr** [comment]
> Removing stop words post embedding helps.

Yes, this might be the case depending on the number of topics that you have. c-TF-IDF works best when you have many topics as that will make it a bit easier to detect stop words. This step is, to a certain extent, independent of generating the embeddings and therefore the transformer-based models. That makes the CountVectorizer often so helpful as it allows you to do processing after training the model. For example, after having trained a topic model you might realize that you would like to have larger n-grams instead of the 1-grams that you have now. Instead of having to re-train the entire model, you could simply re-calculate the c-TF-IDF representation with the updated CountVectorizer. 

> Breaking down text actually generates more intuitive topics.

There can be several reasons for this and it highly depends on the use case but in general it comes down to one of two things. First, if your text is very large, then transformer-based models typically have difficulty handling them and will often ignore any text above a certain threshold. So separating the text into sentences or paragraphs will be helpful. Second, it will also generate more training data which allows the clustering and dimensionality reduction to be more accurate. Better clusters will also result in more accurate c-TF-IDF representations.
