### ISSUE TITLE
Topic -1 in barcharts

### ISSUE THREAD

**Issue by ericchagnon15** [MaartenGr/BERTopic#677]
I have been working with BERTopic for sometime now and have had previous barcharts show topic -1 and my more recent barcharts have not been showing topic -1. After some searching I was unable to find and required conditions or flags that would make topic -1 show up in the barchart and was wondering if you could offer any insight.

**Comment by MaartenGr** [comment]
The -1 topic is an outlier topic and contains documents that are generally unrelated to one another. The documents in that topic are essentially random in nature and therefore do not represent an actual topic. Thus, the -1 topic cannot be interpreted as all other topics. To prevent any misleading insights, it was removed from most visualisations. One option though might be adding to the `topics` variable that you see in most visualisations but I am hesitant in doing so since not all visualisations have that option.
