### ISSUE TITLE
Why is this true? (normalize to simulate cosine distance)

### ISSUE THREAD

**Issue by DeepTitan** [MaartenGr/BERTopic#680]
![image](https://user-images.githubusercontent.com/90869054/185524713-2304cf21-ff08-4070-a46f-75dc06d63912.png)

I trust you guys, I just want to be able to explain it to my team in a better way then "i got it from a FAQ page".  I have pre computed normalized vectors that I want to use cosine sim for. Why does this work?

**Comment by DeepTitan** [comment]
https://maartengr.github.io/BERTopic/faq.html#can-i-use-the-gpu-to-speed-up-the-model

**Comment by MaartenGr** [comment]
Some models do not have a cosine distance metric available. In order to get something very similar, you can normalize the embeddings and then calculate the euclidean distance between them, which together, would represent cosine distance. You can find a bit more about that [here](https://stats.stackexchange.com/questions/146221/is-cosine-similarity-identical-to-l2-normalized-euclidean-distance).

**Comment by DeepTitan** [comment]
Thanks so much for the response, this answers my question perfectly!
