### ISSUE TITLE
program shut down when training the model with large amount of data

### ISSUE THREAD

**Issue by 652994331** [MaartenGr/BERTopic#681]
hi, I have been using bertopic for a while, it has pretty good result on our dataset, good work, thank you. However, when I was trying to train with large amount of data(200000 docs, each doc has tokens between 20 - 100), it took me more than 20 hours and the program seems shut down for some reason. i don't get any model but get some warnings like below:

<img width="549" alt="Screen Shot 2022-08-19 at 15 32 55" src="https://user-images.githubusercontent.com/51428350/185567615-784f4e2c-38eb-40ac-8e2b-18d378b66c2d.png">
<img width="551" alt="Screen Shot 2022-08-19 at 15 33 27" src="https://user-images.githubusercontent.com/51428350/185567698-15f3e958-a39f-473f-b099-2110dc904632.png">
i am  training my model on a p100 gpu with more than 8k mb memory available, my question is, can we train a bertopic mode with this amount of data(200000 docs). and how to handle this memory issue. thank you for your help

**Comment by MaartenGr** [comment]
If I am not mistaken, it seems that the last output from BERTopic was the following message: `Transformed documents to embeddings`. Is that correct? If so, then it is likely due to UMAP needing quite a lot of memory in order to work. You can find a number of tricks of dealing with memory issues [here](https://maartengr.github.io/BERTopic/faq.html) but seeing as it might be related to UMAP it might be worthwhile to set `low_memory=True`. Other than that, you can see if using PCA instead of UMAP solves your issue.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this for now. If you have any questions or want to continue the discussion, I'll make sure to re-open the issue!
