### ISSUE TITLE
Feature request / suggestion for searching by keywords

### ISSUE THREAD

**Issue by bengsoon** [MaartenGr/BERTopic#685]
Hi @MaartenGr -- really loving this package and I love how actively involved you are still with it. I was wondering if it was possible for us to incorporate the `search_documents_by_keywords` feature like the one offered by Top2Vec?

I've found that to be a very useful feature especially when I wanted to look for sub-topic representations other than that was automatically classified by the BERTopic. In fact, I had manually taken the source code implementation in Top2Vec and managed to tweak that for BERTopic with embedding model and that seemed to work great for my use case. But of course, it's hack-y and could be more elegant than some functional implementations. Generally, it was quite a simple implementation: we just have to get word- and phrase-level vector representations and perform similarity search to the embedding vector.

Personally (and I know it's greedy of me), I love all the features in BERTopic (especially the topic representation with c-TFIDF as well as dynamic topic modeling), but I also love the search features available in Top2Vec, but of course it is not practical for me to use two different models at once.

If you do see this as a useful feature, I would be more than happy to help contribute to it under your guidance.

**Comment by MaartenGr** [comment]
The difficulty with something like `search_documents_by_keywords` in BERTopic is that the embeddings of the documents are not saved within BERTopic. This is on purpose, saving these embeddings on a document-level creates a very large model which makes saving and loading the model quite difficult. If there are features dependent on these embeddings, then it might be necessary to keep them within the model and that is something we want to prevent as much as possible. 

Although it would be a nice feature to implement, I am not entirely sure how to do that without saving the embeddings in BERTopic and re-calculating the embeddings. It might be possible to focus on the c-TF-IDF representation instead and create a BoW representation of the documents and search there for words but it does require recalculating stuff. 

Also, and I might be mistaken, I believe such a function, in the context of BERTopic, would not actually require a trained BERTopic model since we are essentially performing a cosine similarity between document and word embeddings, right?

**Comment by bengsoon** [comment]
Thanks so much for the quick response!

Yes I would completely agree the heart behind the design perspective of not keeping the embeddings as that would make the BERTopic model itself too bloated. I actually did it by separately training the embedding model, just like how you had implemented the `visualize_documents` feature. 

In general, I see that the challenges are:
1.  Getting word2vec representation, which Doc2Vec easily provides that. But if we're using Sentence Embedding or other models, we'd need the following:
      -  [Getting Word2Vec dictionary / converter](https://github.com/ddangelov/Top2Vec/blob/d625b507aa18a921b7d0a3710d1a4c176f9b8f84/top2vec/Top2Vec.py#L578)
2.  Mapping embedding - documents  :
     - This one is pretty simple as long as we have embedding vectors and docs list ready.
3.  The rest is just implementing the similarity search, which is mostly implemented here:
     - [`_search_vectors_by_vector`](https://github.com/ddangelov/Top2Vec/blob/d625b507aa18a921b7d0a3710d1a4c176f9b8f84/top2vec/Top2Vec.py#L1062)

As for your feedback on the requirement for BERTopic, I'd agree with that. It's outside the main function of BERTopic, but when I was using BERTopic for my work, my stakeholders were very interested in finding "keywords search" on documents. So my idea is to actually give them that functionality and then also tie that back to the topic representations (by BERTopic) of each of the documents (so we can know which topics would mainly represent these "keywords").

**Comment by MaartenGr** [comment]
> In general, I see that the challenges are:

I actually do not think that the implementation by itself is the difficult part here, I think you can do the `find_documents` part in just a few sentences:

```python

from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Prepare embeddings
docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))['data']
sentence_model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = sentence_model.encode(docs, show_progress_bar=False)

# Train our topic model using our pre-trained sentence-transformers embeddings
topic_model = BERTopic(embedding_model=embedding_model)
topics, probs = topic_model.fit_transform(docs, embeddings)

# find_documents
search_term = "cars"
search_embedding = topic_model._extract_embeddings([search_term], method="word", verbose=False).flatten()
sims = cosine_similarity(search_embedding.reshape(1, -1), embeddings).flatten()
similar_docs = [docs[i] for i in np.argsort(sims)[-5:]]
```

Seeing as the `find_documents` part is only 4 lines long, I wonder whether it is necessary to include it in BERTopic since it can be quickly done outside of it. Although I agree that it is a nice feature to have, seeing as it is not really BERTopic specific and you can do it in a few lines.

**Comment by bengsoon** [comment]
I like your implementation -- you made it look easy! 👍 Yes, I can see your point and totally agree with your point. Thank you so much for your time @MaartenGr !
