### ISSUE TITLE
topics by class + over time

### ISSUE THREAD

**Issue by hyunsikchun** [MaartenGr/BERTopic#701]
Hi MaartenG, 

I have two questions.

1. Is it possible to create topics over time by class? My project examines multiple groups that issued statements for several weeks. I am wondering if I can examine how topics had changed over time by class with BERTopic. 
     Group1, TimeStampe1, topic1, frequency, word1, word2, word3, ...
     Group1, TimeStampe2, topic2, frequency, word1, word2, word3, ...
     Group2, TimeStampe2, topic1, frequency, word1, word2, word3, ...

2.  topics_per_class displays five words per raw (the Words column), but I am wondering if I can increase the number of words, for example. from five to ten. 

Thank you! 

Hyunsik

**Comment by MaartenGr** [comment]
> Is it possible to create topics over time by class? My project examines multiple groups that issued statements for several weeks. I am wondering if I can examine how topics had changed over time by class with BERTopic.

This is currently not implemented within BERTopic but I'll make sure to put it on the list for exploration. I cannot say for certain that it will be implemented in the future as such a feature can be difficult to use. Namely, with such splits, you will need to make sure that each split has sufficient data in order to properly create topic representations. Otherwise, there is a big risk of "overfitting". 

> topics_per_class displays five words per raw (the Words column), but I am wondering if I can increase the number of words, for example. from five to ten.

That is currently not possible as the resulting data can get quite large. Having said that, I'll make sure to similarly look into this to see if additional parameters make sense with the current state of the API.

**Comment by hyunsikchun** [comment]
Thanks for the prompt response! For my project, I run topics over time separately. Hyunsik
