### ISSUE TITLE
topic_model.get_topic_info(0) returns the info for all topics

### ISSUE THREAD

**Issue by Nishant-Gupta-17** [MaartenGr/BERTopic#710]
While running the command topic_model.get_topic_info(0), i expected to see the info about only topic 0, but it returns the info about every topic in dataframe as if i ran the command topic_model.get_topic_info().

Also, not sure whether the command topic_model.get_representative_docs(0), is returning the correct docs of topic 0 or not.

I am using the latest version, i.e. v 0.11.0.

also topic_model.visualize_barchart(20), returns the hgraph for for topic 0 as well

Any help appreciated.

**Comment by MaartenGr** [comment]
Those are known issues that should be fixed with the new release that is scheduled in the upcoming weeks. You can install [this PR](https://github.com/MaartenGr/BERTopic/pull/668)  if you already want to try out the new features.

I believe that `topic_model.get_representative_docs(0)` should be working correctly.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
