### ISSUE TITLE
Any tips how to use GPU to run Bertopic on GCP? 

### ISSUE THREAD

**Issue by jpwavely** [MaartenGr/BERTopic#733]
@MaartenGr  Is there any special tips in the Python code for me to run your Bertopic python code (model fit) on GCP Vertex AI Jupiter notebooks?
I did run on GCP and observed the CPU usage/GPU usage, and did not see clues that GPU was running.   Do I need to put extra codes to enable the usage of GPU? 

-James P.

**Comment by MaartenGr** [comment]
There are different algorithms to BERTopic, some of which support GPU-acceleration and others do not. When embedding the documents, the GPU should automatically be used if you are using SentenceTransformers. As a default, UMAP and HDBSCAN do not support GPU-acceleration. However, you can use [GPU-accelerated versions from cuml](https://maartengr.github.io/BERTopic/getting_started/tips_and_tricks/tips_and_tricks.html#gpu-acceleration) instead.

**Comment by ldsands** [comment]
You may or may not be aware but [beckernick](https://github.com/beckernick) and [cjnolet](https://github.com/cjnolet) have done a lot of work on the cuml GPU version of HDBSCAN ([All points membership vector for HDBSCAN](https://github.com/rapidsai/cuml/pull/4800) and [approximate_predict function for HDBSCAN](https://github.com/rapidsai/cuml/pull/4872)). This should make using a GPU to run BERTopic and access more of its features in the future much easier. There are still some issues ([New joblib breaks hdbscan in GPU jobs](https://github.com/rapidsai/cuml/issues/4892), [Reduce memory pressure in HDBSCAN all_points_membership_vectors](https://github.com/rapidsai/cuml/issues/4879) and [API mismatch](https://github.com/rapidsai/cuml/pull/4872#discussion_r961717464) but some of these should be resolved by the time they release RAPIDS AI 22.10 next month.

I just used the nightly build yesterday, and it took some doing to get it to work on GPU but it isn't as much work as I was expecting. I haven't yet tried some features that I still plan on using/testing (e.g. hierarchical topics, visualizations) but so far it seems to work pretty well.

Side note: I put this here in part so that I have this all in one place and to make [MaartenGr](https://github.com/MaartenGr) aware of it (though I wouldn't be surprised if he is already aware)

**Comment by jpwavely** [comment]
Thank you @MaartenGr  and  @ldsands  for your valuable feedback!

**Comment by MaartenGr** [comment]
@ldsands Thanks for the write-up and for providing several links to interesting features/fixes with respect to what is being done at RAPIDS AI 😄
