### ISSUE TITLE
I cannot import BERTopic since 2 days ago or so

### ISSUE THREAD

**Issue by SynBioExplorer** [MaartenGr/BERTopic#745]

**Comment by SynBioExplorer** [comment]
sorry I just found your fix with...

**Comment by MaartenGr** [comment]
With the new release of HDBSCAN, this issue should be fixed. Since pypi automatically tries to fetch the most recent version of HDBSCAN the fix should be standard. In the next release of BERTopic the HDBSCAN dependencies get upped but for now, it should not give the error anymore if you have the latest version of HDBSCAN. 

If you are still experiencing issues, please let me know and I'll make sure to re-open this issue.
