### ISSUE TITLE
Different result with same parameters in versions of BERTopic?

### ISSUE THREAD

**Issue by nilobarrantes** [MaartenGr/BERTopic#747]
I tested it with bertopic V12.0 and V9.4 (I changed the +1 in C_TF-IDF from V12.0). Whether the code has been updated to add functionality to Bertopic. Why do bertopic 9.4 and bertopic 12.0 versions give such different results?. All graphs, especially the hierarchical clustering and Topics over time, show differences. I used the same database and, I believe, the same parameters in the simulation.

**Comment by MaartenGr** [comment]
It is difficult to say without seeing the entire code that you are using and the extent to which you kept the environment the same (versions of dependencies in BERTopic, operating system, etc.) but it might be due to the stochastic nature of UMAP which you can read a bit more about [here](https://maartengr.github.io/BERTopic/faq.html#why-are-the-results-not-consistent-between-runs).
