### ISSUE TITLE
Getting representative docs with BERTopic DTM

### ISSUE THREAD

**Issue by jacobceles** [MaartenGr/BERTopic#748]
Hi,

I was wondering if there is a way to get the representative documents for the DTM topics. For example, can I get the documents constituting topic 0 for each year separately?

I understand that I can do this when I am using BERTopic to model without any temporal aspect (using `get_representative_docs()` and `visualize_documents()`), but can I do it for BERTopic DTM as well?

I am basically trying to identify these files so I can run some more analysis on them. 

Thanks a lot!

**Comment by MaartenGr** [comment]
The most representative documents for the DTM topics do not get calculated as that is quite a different process from fitting the model. However, you can look in the source code and extract the creation of the bins there:

https://github.com/MaartenGr/BERTopic/blob/09c1732997f838050c263ad00ad3c9474e816863/bertopic/_bertopic.py#L652-L666

Then, you can adjust that to something like this in order to create the documents for each bin:

```python
documents = pd.DataFrame({"Document": docs, "Topic": topic_model.topics_, "Timestamps": timestamps})

all_topics = sorted(list(documents.Topic.unique()))
all_topics_indices = {topic: index for index, topic in enumerate(all_topics)}

if isinstance(timestamps[0], str):
    infer_datetime_format = True if not datetime_format else False
    documents["Timestamps"] = pd.to_datetime(documents["Timestamps"],
                                             infer_datetime_format=infer_datetime_format,
                                             format=datetime_format)

if nr_bins:
    documents["Bins"] = pd.cut(documents.Timestamps, bins=nr_bins)
    documents["Timestamps"] = documents.apply(lambda row: row.Bins.left, 1)
```

Just make sure you define the parameters `nr_bins`, `docs`, and `timestamps`.

**Comment by jacobceles** [comment]
Thank you. I will try this out and let you know in a week!

**Comment by jacobceles** [comment]
@MaartenGr Thanks, this works perfectly! Do you think this is worth adding to the [DTM documentation](https://github.com/MaartenGr/BERTopic/blob/master/docs/getting_started/topicsovertime/topicsovertime.md)?

**Comment by jacobceles** [comment]
@MaartenGr I modified your code like this:
```
documents = pd.DataFrame({"Document": docs, "Topic": topic, "Timestamps": timestamps})

all_topics = sorted(list(documents.Topic.unique()))
all_topics_indices = {topic: index for index, topic in enumerate(all_topics)}

if isinstance(timestamps[0], str):
#     infer_datetime_format = True if not datetime_format else False
    infer_datetime_format = True
    documents["Timestamps"] = pd.to_datetime(documents["Timestamps"],
                                             infer_datetime_format=infer_datetime_format,
                                             format=None)
#                                              format=datetime_format)

if nr_bins:
    documents["Bins"] = pd.cut(documents.Timestamps, bins=nr_bins)
    documents["Timestamps"] = documents.apply(lambda row: row.Bins.left, 1)
```
and my output is:

Document | Topic | Timestamps | Bins
-- | -- | -- | --
science envisions a robot run home head of electrical engineers says at annual rally | 0 | 12/10/1958  2:02:24 AM | (1958-12-10 02:02:24, 1967-07-28 17:08:34.285714272]

This document is from the decade 1950-1959. While creating the model, I initialized this document's timestamp as '1959'. Considering this, could you please explain what the columns 'Timestamps' and 'Bins' hold? I was under the assumption that a document would fall under one and only one bin, but I see it has multiple timestamps associated with it. Could you please clarify?

**Comment by MaartenGr** [comment]
Typically, when you have a list of timestamps they tend to be quite large. It seldom happens that in that large list of timestamps there are only a handful of unique timestamps to be found. So when you have thousands of unique timestamps, it is advised to bin them in order to have a sufficient amount of documents in each bin. 

Thus, there are two scenario's. First, you have a list of timestamps and you want a representation for each unique timestamp. In that case, we assume you only have a handful of timestamps. The related code is as follows:

```python
if isinstance(timestamps[0], str):
    infer_datetime_format = True if not datetime_format else False
    documents["Timestamps"] = pd.to_datetime(documents["Timestamps"],
                                             infer_datetime_format=infer_datetime_format,
                                             format=datetime_format)
```

As you can see, the `Timestamps` column refers to the exact timestamp. 

Second, if you have a list of timestamps but thousand of unique items, then you want to bin them in order to have a sufficient amount of documents for each representation. The related code is as follows:

```python
if nr_bins:
    documents["Bins"] = pd.cut(documents.Timestamps, bins=nr_bins)
    documents["Timestamps"] = documents.apply(lambda row: row.Bins.left, 1)
```

Here, `Bins` refers to the bins that we created from the previously generated timestamps. Then, we make sure that each timestamp in a bin is the same by taking the very first value of the created bin. This value then represents `Timestamps`.

**Comment by jacobceles** [comment]
@MaartenGr Wow, thanks for that awesome explanation! 

Just one thing still confuses me. How is the value for `Timestamps` field generated? In my code, I have defined 7 bins, and the timestamps field has values `[1959, 1969, 1979, 1989, 1999, 2009, 2019]`. So how did it get a specific timestamp like `1958-12-10 02:02:24` or `1967-07-28 17:08:34.285714272` when my timestamps field just had a year in it?

**Comment by MaartenGr** [comment]
@jacobceles That is because of the `pd.cut` function combined with `row.Bins.left`. It first converts the integer timestamps to actual timestamps and then creates bins of equal width. In order to do so, it needs to average out the timestamps thereby creating those specific timestamps. In your case, I would not set `nr_bins` at all since you only have 7 unique timestamps. So there is no need to bin them.

**Comment by jacobceles** [comment]
@MaartenGr Thank you, my output looks better now, but I noticed some of the documents(104 out of 13191) do not have any timestamps/bins associated with them. What might be the reason for this?

**Comment by MaartenGr** [comment]
Could you show how you found out that some of the documents do not have any timestamps/bins associated with them? Do you see that in the resulting dataframe or anywhere else? Also, which timestamps belong to those 104 documents originally?

**Comment by MaartenGr** [comment]
Glad to hear that it worked out well! I'll have to think about the best approach for implementing and sharing that. As you rightly so mention, they can find it here but it would require some searching on the users' part.
