### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cachedir'

### ISSUE THREAD

**Issue by VinayChaudhari1996** [MaartenGr/BERTopic#767]
Hello Guys,
I am getting the following issue after installing the given packages on google-colab,

1) ![image](https://user-images.githubusercontent.com/42869040/194558647-6f207dc2-ae80-4a3a-8b88-b841bd662ad1.png)

2) ![image](https://user-images.githubusercontent.com/42869040/194558310-3349d5fb-407c-45fb-a86f-cb096f425097.png)

how to fix the above issue on google-colab ? 
Thank you

**Comment by VinayChaudhari1996** [comment]
It worked for me on google colab
```
!pip install --upgrade joblib==1.1.0
```

**Comment by opop999** [comment]
Hi, I encountered the same problem. 
It seems to be caused by the incompatibility of the **hdbscan** dependency with its own sub-dependency  **joblib**. 
As you suggest, downgrading the joblib to v 1.1.0 and lower helps, but according to [to this opened issue](https://github.com/scikit-learn-contrib/hdbscan/issues/565), using older joblib is a[ security vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2022-21797), so I would be careful in using this solution in a production code.
