### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by Hurry-LJ** [MaartenGr/BERTopic#77]
numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
numpy-1.20.1

**Comment by MaartenGr** [comment]
I need a bit more context to understand where the problem is coming from. Which version of BERTopic do you have? Did you install it in a fresh environment? How did you install BERTopic? Which python version are you using? 

Having said that, it may be related to an issue we had a while back [here](https://github.com/MaartenGr/BERTopic/pull/46#pullrequestreview-580137083) but I cannot be sure without the answers to the above questions. 

I would suggest starting from a fresh environment and install BERTopic there with the newest version.
