### ISSUE TITLE
Guided Topic Modeling using seed_topics

### ISSUE THREAD

**Issue by msharara1998** [MaartenGr/BERTopic#777]
https://github.com/MaartenGr/BERTopic/blob/09c1732997f838050c263ad00ad3c9474e816863/bertopic/_bertopic.py#L2341-L2377
The above function behavior needs to be checked. For instance, y will be a list containing -1 except for a very low number of indices that will be other than -1. Hence, the effect of seeding is much limited.

**Comment by MaartenGr** [comment]
The seeding depends very much on the quality of the seeded topics. For example, if you only input a single-seeded topic, then it is indeed highly likely that only a small subset of documents will be found that relate to that seeded topic. Moreover, if the seeded topic does not relate in general to any of the documents, for example, because they might not be about the same domains, then it will also generate a low number of non-negative indices. The -1 labeling is necessary as it prevents forcing documents to topics where they do not belong. 

Could you provide an example where you feel that the effect of seeding is too limited?

**Comment by msharara1998** [comment]
I guess you're right. I was deciphering the code of the above function and tracing the dimensions of the matrices. At first, I was wrong about the dimension of the returned similarity matrix. Now I realized what its true dimension is. As you've said, I tried it using only a list of words that are poorly related to the cluster. A list of lists of words that are more relatable to the clusters would be better. Thank you, Maarten!
