### ISSUE TITLE
probabilities and predictions in fit_transform do not coincide

### ISSUE THREAD

**Issue by aholovenko** [MaartenGr/BERTopic#784]
For some reason when I compare the `np.argmax(probabilities, axis=1)` and `predictions`, these don't coincide (not taking into account the -1 topic, where present). I am referring to this function: https://github.com/MaartenGr/BERTopic/blob/09c1732997f838050c263ad00ad3c9474e816863/bertopic/_bertopic.py#L365
Do you know why there is such strange behavior? Is the document's topic not chosen based on the highest probability?
Thanks.

**Comment by MaartenGr** [comment]
The probabilities that are being generated are not the ones on which HDBSCAN bases its assignment. They are probabilities that are approximated after having created their assignments. Therefore, they might not hold the same output since they are generated differently. You can find more about that [here](https://hdbscan.readthedocs.io/en/latest/soft_clustering.html). 

Also, there is currently an issue open about that [here](https://github.com/MaartenGr/BERTopic/issues/769).
