### ISSUE TITLE
Mandatory dependency: sentence-transformers?

### ISSUE THREAD

**Issue by tea-de-kay** [MaartenGr/BERTopic#786]
Since it is possible to provide externally computed embeddings, is there a reason why BERTopic has sentence-transformers as a mandatory dependency? The large secondary dependencies (especially torch) keep me from using this great library in a lightweight setup.

If I understood the code correctly, the only mandatory use is here
```
# Hugging Face embeddings
if isinstance(embedding_model, Pipeline):
    return HFTransformerBackend(embedding_model)
```

Would it be okay, to wrap the import statement and instance check in a try block and make sentence-transformers an extra dependency like, e.g., gensim? Would you accept a corresponding pull request?

**Comment by MaartenGr** [comment]
The most used piece of code in BERTopic is typically the following:

```python
from bertopic import BERTopic
topic_model = BERTopic()
topics, probs = topics_model.fit_transform(docs)
```

This means that as a default, an embedding model needs to be selected in order to convert the documents to embeddings. In other words, if I were to remove sentence-transformers as a dependency, then most users would still need to install it as keeping externally computed embeddings is not something that happens in most use cases. This would greatly inhibit the out-of-the-box experience that BERTopic gives. 

Having said that, I can imagine that it would be nice to have a lightweight solution! There are a few things to consider though when using a try-expect block. There might be users that simply forgot to install sentence-transformers (if you ignored dependencies when installing) and that would lead to errors. Moreover, the SentenceTransformer model is given back as a default if it is installed, a replacement might be necessary (perhaps [this](https://github.com/MaartenGr/BERTopic/issues/768)). Also, it would need to be tracked whether the "gpu-dependencies" are actually tracked such that it would be easier to account for the above. Lastly, there would also need to be instructions on how to install BERTopic without sentence-transformers, which would be something like this: 

```python
pip install --no-deps bertopic
pip install numpy
pip install hdbscan>=0.8.2
pip install umap-learn>=0.5.0
pip install pandas>=1.1.5
pip install scikit-learn>=0.22.2.post1
pip install tqdm>=4.41.1
pip install sentence-transformers>=0.4.1
pip install plotly>=4.7.0
pip install pyyaml<6.0
```

Unfortunately, I believe it is not possible to skip specific requirements so all dependencies except sentence-transformers would need to be manually installed. Also, it is not possible to do something like this: `pip install bertopic[lightweight]` since pypi does not allow `extras_require` to have a different set of base packages compared to `install_requires`. Another solution would be to create a light-weight `requirements.txt` from which you can install BERTopic instead. The tricky thing there is that downloads are not tracked through pypi, which makes it difficult to track download statistics. 

There might be a few things that I am missing here but I am afraid this is not solved with a quick-fix unfortunately. 

Quick note, I think most of the tracking should be done here: 

https://github.com/MaartenGr/BERTopic/blob/09c1732997f838050c263ad00ad3c9474e816863/bertopic/backend/_utils.py#L2-L4

**Comment by tea-de-kay** [comment]
Thanks a lot for you detailed answer! I understand that the out-of-the-box experience is important. I have to reconsider how to handle this without having to install torch.

**Comment by MaartenGr** [comment]
@tea-de-kay I am currently working on the [v0.13 release](https://github.com/MaartenGr/BERTopic/pull/840) which allows you to bypass the mandatory sentence-transformers as follows:

```bash
pip install --no-deps bertopic
pip install --upgrade numpy hdbscan umap-learn pandas scikit-learn tqdm plotly pyyaml
```

Now, it defaults back to a TF-IDF backend instead of sentence-transformers if it is not installed. Hence, I believe there is no need to install pytorch now to be able to use BERTopic which should result in a more lightweight setup. It should work and if you want you can already install it from the [PR](https://github.com/MaartenGr/BERTopic/pull/840).

**Comment by tea-de-kay** [comment]
Thank you very much Maarten for your update on this issue. This really comes as a big help for my use case.

**Comment by MaartenGr** [comment]
No problem, glad I can be of help. If you ever run into any issues, please let me know!

**Comment by MaartenGr** [comment]
With he release of v0.13, I'll be closing this issue for now. Feel free to reach out if you want to continue this discussion or re-open the issue!
