### ISSUE TITLE
Allow precomputed embeddings in bertopic.find_topics()

### ISSUE THREAD

**Issue by DennisCraandijk** [MaartenGr/BERTopic#79]
Hi Maarten,

First, thanks a lot for this great library. I´m using BERTopic with precomputed embeddings to reduce the computational cost of modeling topics. It would be nice to be able to use the `find_topics()` function while using precomputed/custom embeddings. This is currently not possible since the `search_term` also has to be embedded.
https://github.com/MaartenGr/BERTopic/blob/1ffc4569a40bf845d2083bfd63c30c8d648a3772/bertopic/_bertopic.py#L534-L535

I see two options to make the `find_topics()` function usable with custom embeddings

- Allow an embedding as `search_term` 
- Do not raise the exception when `bertopic.embedding_model` is set and compute the embedding on demand

What do you think?

**Comment by MaartenGr** [comment]
Thanks! I can definitely understand that having the possibility to use `find_topics()` with precomputed embeddings would be a helpful feature. 

The issue here is that BERTopic only creates topic embeddings if precomputed embeddings are [not used](https://github.com/MaartenGr/BERTopic/blob/1ffc4569a40bf845d2083bfd63c30c8d648a3772/bertopic/_bertopic.py#L1152). These topic embeddings are created by a weighted average of the embeddings in a topic. For example, if a topic consists of the words "car", "boat", and "bicycle" then it would generate the embeddings of those words and take the weighted average based on their c-TF-IDF scores. 

Thus, when you supply BERTopic with precomputed document embeddings, then it cannot generate the topic embeddings since it needs word embeddings (from the topic representations) to do so. So even if we were to allow an embedding as `search_term` then it has nothing to compare it to since no topic embeddings were created. 

The solution, I think, would be to calculate topic embeddings if both the embedding model and the custom embeddings are supplied to BERTopic. That way, you can still use an embedding as `search_term`. Moreover, this might improve the topic representation since [additional similarity measures](https://github.com/MaartenGr/BERTopic/blob/1ffc4569a40bf845d2083bfd63c30c8d648a3772/bertopic/_bertopic.py#L1262) can be used to improve its coherence. 

This would mean the following implementation:
```python
model = BERTopic(embedding_model=my_embedding_model)
model.fit_transform(docs, my_precomputed_embeddings)
```

What do you think?

**Comment by DennisCraandijk** [comment]
Ok ik get the issue and that sounds like a good approach. 
Are you planning to work on this issue? Currently I don't have time to submit a PR, but I could give it a try in the coming weeks.

**Comment by MaartenGr** [comment]
I think I will fix this issue in the next large release. For now, I am gathering non-immediate issues and feature requests and combine them into v0.7. So it is likely I will be working on it in the coming weeks.

**Comment by MaartenGr** [comment]
@DennisCraandijk It took some time but with the new release (v0.7 #87) the search_term should now work if you use pre-computed embeddings. However, it is important that you still pass your embedding model to BERTopic so that it can create the necessary embeddings to search topics. 

Update bertopic with `pip install --upgrade bertopic` and you should be good to go!
