### ISSUE TITLE
visualize_topics() & 'topics_over_time'

### ISSUE THREAD

**Issue by rollator3000** [MaartenGr/BERTopic#80]
Hi,

Really love the repository & it works quite smooth - installing it via `pip install bertopic[all] `
Two issues came up, when using the examples from the repo:

**1)** I've copied the example from the _Google-Colab_ & run it from _Spyder_ (on a subset of the data, as my machine is not too powerful). Everything works fine except for:
`topic_model.visualize_topics()`
No error is coming up, but neither a plot. 

**2)** I've run the 'Dynamic Topic Modeling' with the Donald Trump Tweets  on _Spyder_ (again on a subset of the data, as my machine is not too powerful). Everything worked out fine, except for:
`topics_over_time = model.topics_over_time(tweets, topics, timestamps)`
which resulted in the error:
`AttributeError: 'BERTopic' object has no attribute 'topics_over_time'`

Thanks in advance! 
Cheers Frederik

**Comment by MaartenGr** [comment]
**1)** I do not work with *Spyder* but I think this has to do with how that IDE processes the visualization. A quick google search shows me that you will have to use something like the following in order to visualize the topics:

```python
fig = topic_model.visualize_topics()
fig.show()
```

If that does not work I would refer you to [this](https://stackoverflow.com/questions/35315726/plotly-how-to-display-charts-in-spyder) stackoverflow post where a few solutions are discussed. 

**2)** Although I am not sure what exactly is installed on your machine, I am quite certain you do not have the newest version of BERTopic installed. `topics_over_time` is a function introduced in v0.6 and cannot be found in earlier versions. I think that upgrading to v0.6 with `pip install --upgrade bertopic` would solve this issue. 

Let me know if it does (not) work out!
