### ISSUE TITLE
Removal of stopwords after embedding step

### ISSUE THREAD

**Issue by chewbm** [MaartenGr/BERTopic#808]
Can I check if its possible to remove stopwords after forming the embeddings?
The ideas is to allow these stopwords to provide context to the word intent, but removal of these stopwords in order to not affect how the clusters are formed.

**Comment by MaartenGr** [comment]
Yep! That is what the CountVectorizer model is for. In order to remove the stopwords after forming the embeddings, you would only need to run the following:

```python
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(stop_words="english")
topic_model = BERTopic(vectorizer_model=vectorizer_model)
```

**Comment by chewbm** [comment]
Hi MaartenGr, understand that CountVectorizer works **after** the documents are clustered, hence the stopwords would have impacted how the documents are clustered. (Quote: "Instead, we can use the CountVectorizer to preprocess our documents after having generated embeddings and clustered our documents.")
 
What I meant was whether the stopwords to be removed after the embeddings and generated and before clustering. Thanks!

**Comment by MaartenGr** [comment]
Ah, so you mean something like this:

> embedding generation -> removal of stopwords -> clustering

What you suggest actually does not affect the clustering at all. The general pipeline of BERTopic is as follows:

> embedding generation -> dimensionality reduction -> clustering -> c-TF-IDF

Keeping that in mind, the clustering is done on the embeddings that were generated in the very first step. You indeed want to prevent removing stop words there in order to provide context to the context-based models. So when you perform the clustering, it is done on the embeddings and the documents themselves are not being used in that step. In other words, since we are not directly using the documents when clustering, removing stopwords after embedding generation and before clustering does not affect the clustering at all. 

You can find more information about how the pipeline works [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html).

**Comment by chewbm** [comment]
embedding generation -> removal of stopwords -> clustering

Is there any way we can do the stopwords removal in this way?

**Comment by MaartenGr** [comment]
> embedding generation -> removal of stopwords -> clustering
> 
> Is there any way we can do the stopwords removal in this way?

Just to be sure, why would you want to remove stopwords in that way if it does not influence the clustering? 

To be more specific, there is no difference between:

> embedding generation -> removal of stopwords -> clustering

and this:

> embedding generation -> clustering -> removal of stopwords 

When we perform the clustering step, we are actually **not** clustering on words but on n-dimensional vectors instead.

**Comment by chewbm** [comment]
Thanks I understand now.

**Comment by carobs9** [comment]
> > embedding generation -> removal of stopwords -> clustering
> > Is there any way we can do the stopwords removal in this way?
> 
> Just to be sure, why would you want to remove stopwords in that way if it does not influence the clustering?
> 
> To be more specific, there is no difference between:
> 
> > embedding generation -> removal of stopwords -> clustering
> 
> and this:
> 
> > embedding generation -> clustering -> removal of stopwords
> 
> When we perform the clustering step, we are actually **not** clustering on words but on n-dimensional vectors instead.

Hi @MaartenGr and @chewbm. Sorry for bringing back such an old issue, but I run into a similar problem and the solution provided does not work so well in my case. It seems like the short texts I am working with contain certain very common words, which of course are captured in the embeddings. I suspect that due to having such common words, the dimensionality reduction and clustering output one big cluster, hence topics end up being very similar to each other.

Following this issue, I wanted to ask if it is possible to account for these common words before the dimensionality reduction or clustering steps to be able to obtain more clusters, hence more topics, beforehand, instead of fixing the representation a posteriori.

**Comment by MaartenGr** [comment]
@carobs9 That depends on your full configuration of BERTopic. There is so many things that you can change there, it is difficult to say which one thing you could change. It can be due to the embedding model but also the min cluster size parameter of HDBSCAN for instance. You could also use k-Means instead to have more control over the clusters.
