### ISSUE TITLE
only 2 topics 0 and 1 are returnt. not even 0

### ISSUE THREAD

**Issue by leminhds** [MaartenGr/BERTopic#818]
Hello, I have some 3400 documents. Not large, but not too small. However the model seems to fail to retrieve any topics at all from my data. I have re-run the model multiple time, and at like the 5th try, then 44 different topics were finally returned like in the image below.
However, when I run the model again, I end up again with only 2 topics. What might have caused such drastic changes?

![image](https://user-images.githubusercontent.com/66391734/199534875-e585f0f2-868d-4f91-8746-e6a399858979.png)

**Comment by MaartenGr** [comment]
The amount of topics that are returned in the default BERTopic depends on the `min_topic_size` parameter. This parameter directly relates to the `min_cluster_size` parameter in HDBSCAN which essentially tells you the minimum size a cluster can take. Setting this value too large can result in no clusters being created due to issues with the separation of the data. The default value might be, for your data, on the border of finding a good separation. 

When you use the default settings of BERTopic you will additionally use UMAP, a stochastic algorithm that gives a different output each time you run it. As a result, since you have a value for `min_topic_size` that is just on the border of finding many clusters, there is a good chance that when you re-run BERTopic, UMAP will give slightly different results that make it difficult for HDBCSAN to then find a good separation. 

The solution is rather straightforward, lower the value of `min_topic_size` until you consistently find a bunch of topics.

**Comment by leminhds** [comment]
thanks! decreasing min_topic_size down to 8 helped

**Comment by MaartenGr** [comment]
Great! Glad to hear that it worked.
