### ISSUE TITLE
Is possible to have a functionality like top2vec to search documents by Topic?

### ISSUE THREAD

**Issue by nadiafelix** [MaartenGr/BERTopic#83]
Is possible to have a functionality like top2vec to search documents by Topic?

We are going to search by topic 48.

documents, document_scores, document_ids = model.search_documents_by_topic(topic_num=48, num_docs=5)

Returns:

documents: The documents in a list, the most similar are first.

doc_scores: Semantic similarity of document to topic. The cosine similarity of the document and topic vector.

doc_ids: Unique ids of documents. If ids were not given, the index of document in the original corpus.

Thanks a lot,

**Comment by MaartenGr** [comment]
This is unlikely to be a feature in BERTopic. The documents on which you train the model are not stored within BERTopic. The reasoning for this is that when you have millions of documents, your model will explode in size. Since no documents are saved within the model there is no option to search documents by topic. 

Having said that, you can use the topics and probabilities that were returned to access the documents that are most likely to belong to the topic you are searching for.
