### ISSUE TITLE
Most docunments are assigned to Topic 0

### ISSUE THREAD

**Issue by caiyishu** [MaartenGr/BERTopic#833]
Thank you for the very helpful package!

To handle the serious outlier issue, I use K-Mean to cluster the topics:

```
umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=888999,
)

n_clusters = 200
cluster_model = KMeans(n_clusters=n_clusters, random_state=888999)

vectorizer_model=CountVectorizer(stop_words=list_stopwords_after)

topic_model = BERTopic(
    language="chinese (simplified)",
    embedding_model=model_pertrain,
    umap_model=umap_model,
    hdbscan_model=cluster_model, # hdbscan_model https://github.com/MaartenGr/BERTopic/issues/556
    calculate_probabilities=True,
    vectorizer_model=vectorizer_model,
    verbose=True,
    nr_topics="auto",
)
```

However, I found most of my documents are assigned to topic 0

Could you give me some suggestions to handle this issue? For example, do you think I need to remove high-frequency words before fitting?

![image](https://user-images.githubusercontent.com/65852643/201049542-e4a75fcf-1dba-4cd9-9525-94bd3c2e7d5c.png)

**Comment by MaartenGr** [comment]
> However, I found most of my documents are assigned to topic 0

> Could you give me some suggestions to handle this issue? For example, do you think I need to remove high-frequency words before fitting?

It is difficult to say without saying the data but this can be due to several reasons. First, it may be that most documents actually fit best within that first topic and to a lesser extent with all others. k-Means does not try to make sure there are an equal amount of documents in each cluster but merely tries to find the best split. If that split happens to be such that most documents fall into a single cluster, then that would be possible. Second, when you use k-Means with a relatively low number of clusters, then it might try to merge many clusters together since it is forced to find rather global clusters. Third, when you use `nr_topics="auto"` the number of topics gets reduced after being created by the cluster model by clustering the topics. As a result, it might merge several topics together. So it might be worthwhile to skip `nr_topics="auto"` since you already specify the number of topics with k-Means. Fourth, I am not entirely sure since you did not share the model but if `model_pertrain` is not a good model for representing documents, then that might hurt the performance of the model. 

Also, and this does not relate necessarily to the topic distributions, it seems you are using a model for Chinese texts but are using the default `CountVectorizer`. It might be worthwhile to use [jieba](https://maartengr.github.io/BERTopic/faq.html#how-can-i-use-bertopic-with-chinese-documents) for the tokenization of the documents since it handles Chinese texts much better.

**Comment by caiyishu** [comment]
Thank you for the suggestions. They are very helpful.

> Third, when you use `nr_topics="auto"` the number of topics gets reduced after being created by the cluster model by clustering the topics. As a result, it might merge several topics together.

I followed this suggestion, and the distribution of document topics has become much more even now. However, the overlap between them also heavily increased.
![newplot](https://user-images.githubusercontent.com/65852643/201089644-34f3d881-fa2d-41fd-bd25-bdcf1b0d31b1.png)

> I also tried `"hierarchical_topics": hierarchical_topics` with `nr_topics="auto"` removed. The situation is similar, that is the distribution became even, but the overlap increased.

My documents consist of political disclosures, which are more likely to concentrate on the topics of political issues.

**1. In this case, would you think I need to remove nr_topics="auto"?**

**2. If I use K-mean with nr_topics="auto", how could I evaluate the performance of each n_cluster and decide an optimal n_cluster?**

> I am not entirely sure since you did not share the model, but if `model_pertrain` is not a good model for representing documents, then that might hurt the performance of the model.

I generated the `model_pertrain` by:
```
model_pertrain = SentenceTransformer(
    "paraphrase-multilingual-mpnet-base-v2"
)
```

As you recommended in the project document, it works quite well. By with I can get the embeddings via:
```
embeddings = model_pertrain.encode(list_docs, show_progress_bar=True)
```

When I try another model:
```
model_pertrain = KeyedVectors.load_word2vec_format(
    "E:/OneDrive - The Chinese University of Hong Kong/data/词向量/nlp语料库/sgns.merge.word.bz2", unicode_errors="ignore"
)
```
I can no longer get `embeddings` as KeyedVectors does not has a feature of `encode.`

**3. I was wondering whether you have any idea about how to get the `embeddings` from `KeyedVectors`?**

I appreciate your patience. If you do not have time to answer my question, it will also be okay to close my issue. You have given me a lot of help; I am happy to make more exploration on BERTopic.

**Comment by MaartenGr** [comment]
> I followed this suggestion, and the distribution of document topics has become much more even now. However, the overlap between them also heavily increased.

That is because there are simply many topics/clusters being created. Also, the visualization that you use shows smaller/larger points based on the size of the topic, so it does not necessarily mean that they actually overlap. To lower the amount of topics and thereby decreasing overlap, you can set a lower `n_clusters` in k-Means. 

> 1. In this case, would you think I need to remove nr_topics="auto"?

When you use k-Means, you can specify the number of topics yourself. So I would advise playing around with the number of clusters until you find something that fits best instead of using `nr_topics="auto"`. 

> 2. If I use K-mean with nr_topics="auto", how could I evaluate the performance of each n_cluster and decide an optimal n_cluster?

An optimal number of clusters depends on your definition of optimal. For some, that might be things like topic coherence, quality of the cluster generation (e.g, Rand index), topic diversity, or something entirely different. So it is difficult to say what optimal means in this context. 

> 3. I was wondering whether you have any idea about how to get the embeddings from KeyedVectors?

You can find more about that in the [Gensim documentation](https://radimrehurek.com/gensim/models/keyedvectors.html#how-to-obtain-word-vectors).

**Comment by caiyishu** [comment]
Thank you so much!
