### ISSUE TITLE
Top n words of a topic model

### ISSUE THREAD

**Issue by Hari25483** [MaartenGr/BERTopic#838]
We can get the top b words for a topic in BERTopic. 
How do we get the top n words for a particular topic model? 
@MaartenGr

**Comment by MaartenGr** [comment]
I am not entirely sure if I understand you correctly. The top b words in a topic are retrieved by setting `BERTopic(top_n_words=b)` but what exactly do you mean with `the top n words for a particular topic model`? A topic model by itself does not really have a `top n words` since it models several topics and not just one.

**Comment by Hari25483** [comment]
Yeah, it has several topics, with top b words. I wanted to know whether we can filter out the top n words from all the top words from all the topics?

**Comment by MaartenGr** [comment]
You can use `topic_model.get_topic()` to get the top `n` words from a topic as defined by `top_n_words`  when instantiation BERTopic. You can make a smaller selection from those. If you want more words, then you can leverage the internal CountVectorizer (`topic_model.vectorizer_model`) and c-TF-IDF matrix (`topic_model.c_tf_idf_`) to manually extract more words if needed.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue for now. If, however, you want to continue the discussion or re-open the issue, feel free to reach out!

**Comment by blozano-newtral** [comment]
Is there any reason why the parameter `top_n_words` is set in the `BERTopic` constructor instead of as an extra parameter in `topic_model.get_topic(...,top_n_words=n)`?

**Comment by MaartenGr** [comment]
@blozano-newtral There are several reasons for this. First, we need to know how many words to extract for usage in representation models. Second, extracting any top n from a sparse matrix can be costly, so it is helpful to do that during training. Third, since it can be computationally costly, we do not want to compute them during `.get_topic` as that would slow things down. 
Lastly, and most importantly, the top n words are used throughout many functions other than `.get_topic`. For instance, you get frequent keywords in `.get_document_info`. 

There are more reasons for this, but the above is a small selection. You can always update the `top_n_words` using `.update_topics` after training your model.
