### ISSUE TITLE
cuml HDBSCAN inference error

### ISSUE THREAD

**Issue by sademakn** [MaartenGr/BERTopic#858]
Hi, Thank you for great effort on building this useful library. I trained a Bertopic model using cuml HDBSCAN and UMAP, it trained so fast. But after loading the model again, I tried to transform the documents and I got the bellow error. How can I fix it ?
```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [4], line 40
     38 else:
     39     topic_model = BERTopic.load(output_model_path)
---> 40     topics, probs = topic_model.transform(
     41         documents=texts_corpus, embeddings=vectors_corpus
     42     )

File ~/miniconda3/envs/rapids-22.10/lib/python3.9/site-packages/bertopic/_bertopic.py:436, in BERTopic.transform(self, documents, embeddings)
    433         logger.info("Calculated probabilities with HDBSCAN")
    435 else:
--> 436     predictions = self.hdbscan_model.predict(umap_embeddings)
    437     probabilities = None
    438 logger.info("Predicted clusters")

File base.pyx:269, in cuml.common.base.Base.__getattr__()

AttributeError: predict
```

Another problem is that when I am using GPU with cuml in the bellow code the `probs` will be None and when I am using cpu I am getting the `probs` as a  numpy array with values :
```
topics, probs = topic_model.fit_transform(
    documents=texts_corpus, embeddings=vectors_corpus
)
```
my code is :
```
from bertopic import BERTopic
from cuml.cluster import HDBSCAN
from cuml.manifold import UMAP

min_topic_size = 5
umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
)

hdbscan_model = HDBSCAN(
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True,
    gen_min_span_tree=True,
)
topic_model = BERTopic(
    min_topic_size=min_topic_size,
    calculate_probabilities=True,
    verbose=True,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
)
topics, probs = topic_model.fit_transform(
    documents=texts_corpus, embeddings=vectors_corpus
)
topic_model.save("output_model_path")
```

**Comment by MaartenGr** [comment]
When you run any other cluster model aside from the default HDBSCAN model, it will need a `predict` method in order to predict new instances. As a result, this currently does not work for cuML's HDBSCAN since it does not have a `predict` method. However, you can do the following to support it:

```python
from cuml.cluster import HDBSCAN, approximate_predict
        
class GPUHDBSCAN(HDBSCAN):
    def predict(self, umap_embeddings):
        predictions, probabilities = approximate_predict(self, umap_embeddings)
        return predictions
```

Having said that, there will be much more native support for cuML's HDBSCAN in the [v0.13 release of BERTopic](https://github.com/MaartenGr/BERTopic/pull/840) including the option to calculate probabilities.

**Comment by slice-aditi** [comment]
Hi MaartenGr ,

where do we need put the code below in the package for transform function to work ? :

```
from cuml.cluster import HDBSCAN, approximate_predict
        
class GPUHDBSCAN(HDBSCAN):
    def predict(self, umap_embeddings):
        predictions, probabilities = approximate_predict(self, umap_embeddings)
        return predictions
```

**Comment by MaartenGr** [comment]
@slice-aditi You need to pass that to the `hdbscan_model` parameter. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/clustering/clustering.html). Do note that in a few weeks the v0.13 version of BERTopic will be released which contains more native support for cuML's HDBSCAN implementation.

**Comment by ravinani** [comment]
> @slice-aditi You need to pass that to the `hdbscan_model` parameter. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/clustering/clustering.html). Do note that in a few weeks the v0.13 version of BERTopic will be released which contains more native support for cuML's HDBSCAN implementation.

Hi MaarteenGr, 

Thanks for the wonderful library. Training the BERTopic using using cuml HDBSCAN and UMAP is quite fast. But when I am trying to transform for new document or getting the probability distribution for each topic for a document its getting crashed due to memory issues even for GPU with 40GB.

Below is my training code on 1M dataset.


<img width="770" alt="Screenshot 2023-01-07 at 1 30 09 PM" src="https://user-images.githubusercontent.com/11882740/211140487-73e04832-50c9-4f8f-b25a-2776f97d8168.png">

After training I am trying to get the probabilities of every document in each topic

s = cuml.cluster.hdbscan.all_points_membership_vectors(model_colab.hdbscan_model)

Is there any way to get the probabilities in batches?

**Comment by MaartenGr** [comment]
@ravinani I do not think that it is possible at the moment since cuML's version does not yet support a `membership_vector` function allowing for the probabilities of unseen documents. It might be worthwhile to dive a little deeper into their code to see if you can batch them yourselves.

**Comment by beckernick** [comment]
It's not possible to batch to cuML's `all_points_membership_vectors` manually as Python user. We're exploring batching under the hood to reduce memory requirements. [This cuML issue and discussion](https://github.com/rapidsai/cuml/issues/4879#issuecomment-1370311449) captures the current status as well as potential workarounds you may be able to try to reduce memory required.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
