### ISSUE TITLE
Cannot import 'HFTransformerBackend' from 'bertopic.backend'

### ISSUE THREAD

**Issue by elashrry** [MaartenGr/BERTopic#877]
Thank you for this neat library! 

I followed the example in the docstring of `HFTransformerBackend()`:
https://github.com/MaartenGr/BERTopic/blob/d63566ac1c2cf0a63a085b3bfa7049f4d9b280c2/bertopic/backend/_hftransformers.py#L26-L31

but I got the error 
```
ImportError: cannot import name 'HFTransformerBackend' from 'bertopic.backend' 
(/usr/local/lib/python3.7/dist-packages/bertopic/backend/init.py)
```

but I can import it normally with 
```
from bertopic.backend._hftransformers import HFTransformerBackend
```

so, we can change the docstring or the add `from ._hftransformers import HFTransformerBackend` to `backend.__init__.py`. 

I think this applies to other backends as well.

**Comment by MaartenGr** [comment]
The docstring is indeed here a bit misleading. The backends are purposefully not directly accessible since many require additional dependencies which can result in import errors. Instead, there is an automatic selection of backends that you can find here: https://github.com/MaartenGr/BERTopic/blob/master/bertopic/backend/_utils.py

**Comment by elashrry** [comment]
Thank you for your reply. I agree, it is not how the library is intended to be used, I just saw it while looking for something.
