### ISSUE TITLE
How exactly would top_n_words affect topic embeddings and coherence ??

### ISSUE THREAD

**Issue by johnsonice** [MaartenGr/BERTopic#910]
Sorry, I have been digging everywhere trying to understand how exactly  would top_n_words affect topic embeddings and coherence. 

From my understanding, the top_n_words is only used in the very last step when trying to get a topic representation.  in that sense, it shouldn't really have an impact on topic assignment, # of topics fund etc (should be based on HDBSCANE and a merging step using c_tfidf matrix ). 

I did went though some experiment with setting a fix random seed for umap, set nr_topics to be 'auto', and only changing top_n_words, it does change the results (including # of topics, distribution of topic assignments, and also the coherence score - by running CoherenceModel from gensim )

Can someone help explain where I got it wrong? (unless top_n_words affects c_tfidf matrix ?)

Thanks !!

**Comment by MaartenGr** [comment]
It depends on how you intialized the model but the `top_n_words` actually influence the topic embeddings that are created. These topic embeddings are the weighted average of the top n words based on their c-TF-IDF values and since these embeddings are then used for automatically reducing the topics, it is expected that they will influence the number of topics and coherence score. For the next release, I am already working on updating the topic embeddings on a technique that combines KeyBERT with c-TF-IDF which is already looking quite accurate but that will take a bit more time.

**Comment by johnsonice** [comment]
> 

Thank you very much ! I was assuming the merging step with c_tfidf matrix is much larger than just just the top n words. Now it all make sense. 

I guess it makes hyper parameter a bit more complicated.
