### ISSUE TITLE
visualize_documents() can't hide axis

### ISSUE THREAD

**Issue by xiaohou1112** [MaartenGr/BERTopic#924]
Hi Maarten!
Thank you for making Bertopic such a useful tool!
I used bertopic in writing my thesis.
The graph drawn by 'visualize_documents() '  is very beautiful.
![image](https://user-images.githubusercontent.com/62997063/211860745-871fa99a-cb21-465b-a8eb-00905cbff145.png)
Because my data points are concentrated in this small area, I want to take a screenshot of this part and put it in the thesis.
![f3b8c2de932c2b3371beea7dad4e0b2](https://user-images.githubusercontent.com/62997063/211861294-5cadd2cc-38cd-432b-bb25-4656ba72b097.png)
I want to hide the coordinate axis, so I changed the code of this function
![565a084c89e4ff3502445e2bc0f3396](https://user-images.githubusercontent.com/62997063/211863437-418d973a-2dea-4fd1-a93f-ef6ca58e3347.png)

But I failed.

Could you tell me how to hide the coordinate axis? Thank you very much!

**Comment by MaartenGr** [comment]
These lines are actually not drawn as axis but as individual line plots. In other words, you will have to remove those lines from the plot itself in order to remove the drawn axis. You can find more about how it was done here: 

https://github.com/MaartenGr/BERTopic/blob/06dcd47a019854185a39146ed693d16dc3a27651/bertopic/plotting/_documents.py#L190-L200

**Comment by xiaohou1112** [comment]
Thank you very much !!!
