### ISSUE TITLE
assign new topics from reduce_outliers to the model

### ISSUE THREAD

**Issue by DiegoKoz** [MaartenGr/BERTopic#938]
Hi, 

Thanks for implementing the new `reduce_outliers` function, it looks great. 

I see that the new topics for the outliers are not automatically saved on the `topic_model` object. Is it the following pipeline correct to have the new topic assignment on my topic_model?

```
new_topics = topic_model.reduce_outliers(texts, topics)
topic_model.update_topics(texts, new_topics)
```

If that's correct, it would be nice to have that on the documentation. Please let me know if that pipeline is not advisable

Kind regards

**Comment by MaartenGr** [comment]
There is actually a piece about this in the documentation about reducing outliers [here](https://maartengr.github.io/BERTopic/getting_started/outlier_reduction/outlier_reduction.html#update-topics). In short, you can decide to add the new topics to the model directly and update the topic representations or merely update the topic sizes as outliers can negatively impact the topic representations. It all depends on our specific use case but it may be worth to try out both.

**Comment by drob-xx** [comment]
@DiegoKoz Another way to reduce outliers is to tune HDBSCAN to get the fewest possible - which is why I wrote [TopicTuner](https://github.com/drob-xx/TopicTuner). Cheers.

**Comment by MaartenGr** [comment]
Note that you can find an overview of suggested ways to reduce outliers in BERTopic [here](https://maartengr.github.io/BERTopic/faq.html#how-do-i-reduce-topic-outliers). I would advise looking for something that best fits your use case, whether that is optimizing a model, replacing it with a different model, doing post-hoc filtering, or something else. Also, it seems I forgot to put this in the documentation, but you can combine different strategies in `.reduce_outliers` to create layered outlier reduction strategies that might work well together. It follows the modular and model-agnostic nature of BERTopic in that sense.

**Comment by DiegoKoz** [comment]
thanks! sorry I missed it in the documentation. 

I work with documents that are abstracts + titles of some specific field, between 500K and 2M observations. And in all cases, with a lot of exploration of hyperparameters for HDBSCAN, I cannot get below the 30% outliers. So this new `reduce_outliers` functionality is really a game-changer. The changes I can see on the topics representation seem to make a lot of sense too

cheers.

**Comment by DiegoKoz** [comment]
I'll take the opportunity to ask something else. When I do `update_topics`, the new `get_topic_info` gives topics that appear to be the same, but with shifted positions. 

here's an example (old in red, new in green)
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/28060531/213137521-8ef0ce34-d032-418a-97c1-1d538b29998c.png">

Old topics 40,41 is now really similar to topic 41,42. Old topic 42 is now topic 46; 43 --> 44, but 44-->43 and 45==45. 

I thought it could be because topics were realigned by their topic size, but it doesn't seem to be the case (new topics are not aligned by size). 

Having the same old and new topics aligned would be very helpful for comparison, especially to check how much the inclusion of the ex outliers changes the topic representation.

**Comment by MaartenGr** [comment]
The tricky thing here with `.update_topics` is that it depends on the use case whether we want the topics to have the same numerical values as they had before. For example, when you perform `.update_topics` by manually merging them, their respective IDs will change. Perhaps I will add a parameter that allows you to align the old and new topics. It would, however, requires careful selection of the topics by the user as missing topics in a sorted range of IDs can break the model.

**Comment by DiegoKoz** [comment]
I think such parameter would make a lot of sense in the pipeline:

```
new_topics = topic_model.reduce_outliers(texts, topics)
topic_model.update_topics(texts, new_topics, keep_ids=True)
```

as the the `new_topics` should be well aligned, right? So then the comparison of old and new topics (and the effect of outliers) would be easier.

**Comment by MaartenGr** [comment]
There is some difficulty here. There are use cases where `new_topics` do not align with the `topics` or where `new_topics` contain fewer topics than `topics`. As a result, keeping `new_topics` as is would result in a list of topics that skip values. For example, `new_topics` might then contain topics 1, 2, and 4 and will skip topic 3. Since many operation of BERTopic assume no skipping topics, slicing matrices would get troublesome here. 

Having said that, it would be nice to keep the topics IDs as they are and such a parameter would definitely help. The main thing here is that I will need to think carefully about how to approach that.

**Comment by DiegoKoz** [comment]
dropping topics can occur with `reduce_outliers`? Of course this alignment would be impossible on other operations that reduces outliers. But for the case of the new `reduce_outliers` it could be a parameter like

```
topic_model.reduce_outliers(texts, topics, update_model = True)
```

But maybe I'm missing something and there are cases where `reduce_outliers` indeed drops topics

**Comment by MaartenGr** [comment]
No, but dropping can be done with `.update_topics` which is where I want to keep track of any updates to the model. I think it becomes too complex to have a parameter like `update_model=True` as there are quite a number of functions that would then need to have such a function. Instead, I think `.reduce_outliers` should be used as a quick iteration to reduce outliers but also to stack different outlier reduction approaches. For example, you can stack strategies:

```python
# Use the "distribution" strategy with a threshold
new_topics = topic_model.reduce_outliers(docs, topics, strategy="distributions", threshold=0.1)

# Use the "c-TF-IDF" strategy with a threshold
new_topics = topic_model.reduce_outliers(docs, new_topics , strategy="c-tf-idf", threshold=0.1)

# Reduce all outliers that are left with the "embeddings" strategy
new_topics = topic_model.reduce_outliers(docs, new_topics , strategy="embeddings")
```

As such, separating the reduction of outliers with updating the model allows for some modularity and quick testing. Similarly, this makes it so that there is a single function for updating topics internally as there are quite some different ways one can update their topics.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
