### ISSUE TITLE
Further clustering one of the resulting topics of a model

### ISSUE THREAD

**Issue by GSJSussex** [MaartenGr/BERTopic#943]
Hi Maarten,

Thanks for having developed this fantastic model. It's been very useful for my project.

I have a question about further clustering the resulting topics of a model. I'm using BERTopic to analyse tweets (about 65,000 tweets) published by politicians. I noticed that 3-4 of the resulting topics of my model are a bit too broad when I looked at some of the documents assigned to them. In the light of this, I wondered whether there would be a way to divide those topics into smaller ones. 

I hope this makes sense to you.

Thanks!

**Comment by MaartenGr** [comment]
Thank you for your kind words!

There currently is not a single method for further reducing those topics. However, you could take the topics that were a bit too broad and train a separate model on them. The idea here is that the separate model should then find more of the micro-clusters that you might be looking for. 

Then, merging those topic models can be a bit tricky since they were trained quite differently. Fortunately, we can do a little trick to create a third model that includes those topics. 

Let's say you have a dataset `docs` of 65,000 documents, you can then train your initial model like so:

```python
from bertopic import BERTopic

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(docs)
```

However, the resulting `topics` will then contain those 3-4 topics that might be a bit too broad. We subset the documents that contain these topics and pass that to another model:

```python
# Note that `1, 2, 3, 4` should be the topic IDs of your broad topics
selected_indices = [index for index, topic in enumerate(topics) if topic in [1, 2, 3, 4]]
selected_docs = [docs[index] for index in selected_indices]

# Train on the topics that were too broad
topic_model1 = BERTopic()
topics1, probs1 = topic_model1.fit_transform(selected_docs)
```

Then, we can combine the topics from `topics` with `topics1` to create a new set of topics:

```python
iter_topics1 = iter(topics1)
updated_topics = [topic if topic not in [1, 2, 3, 4] else next(iter_topics1 ) for topic in topics]
```

Finally, we can pass those `updated_topics` to BERTopic in a supervised manner in order to get their topic representation:

```python
from bertopic import BERTopic
from bertopic.backend import BaseEmbedder
from bertopic.cluster import BaseCluster
from bertopic.vectorizers import ClassTfidfTransformer
from bertopic.dimensionality import BaseDimensionalityReduction

# Prepare our empty sub-models and reduce frequent words while we are at it.
empty_embedding_model = BaseEmbedder()
empty_dimensionality_model = BaseDimensionalityReduction()
empty_cluster_model = BaseCluster()
ctfidf_model = ClassTfidfTransformer(reduce_frequent_words=True)

# Fit BERTopic without actually performing any clustering
topic_model= BERTopic(
        embedding_model=empty_embedding_model,
        umap_model=empty_dimensionality_model,
        hdbscan_model=empty_cluster_model,
        ctfidf_model=ctfidf_model
)
final_topic_model.fit(docs, y=updated_topics )

```

**Comment by GSJSussex** [comment]
Thanks a lot for your answer. It's been of great help to further developing my model.
