### ISSUE TITLE
Semantic versioning, changelog and breaking changes

### ISSUE THREAD

**Issue by taract** [MaartenGr/BERTopic#957]
Thank you for a great library. It's really useful.

Could you possibly use [semantic versioning](https://semver.org/) for releases? It's a helpful way to know if a new version has breaking changes to the API.

I have had some problems because I wrote a pipeline with BERTopic ~0.9.0 and recently updated to 0.13.0. There were an unexpected number of breaking changes for a minor version change. For example, `BERTopic.topics`  (and a few other attributes) disappeared and `BERTopic.topics_over_time` lost `topics` as an argument. It would also be useful if these kinds of things are noted in the changelog.

**Comment by MaartenGr** [comment]
Thank you for the feedback! I have been hesitant to use semantic versioning for BERTopic since the API actually changes quite often in order to keep up with the current developments in the field. As a result, we might have been at major version v14 by now if I were to adhere to the semantic versioning. Having said that, it would indeed be much nicer if the changelog would contain a section about API changes such that it becomes a bit easier to use newer versions. I'll put it on the to-do list to update the previous changelogs and will make sure to add breaking changes to upcoming releases!

**Comment by taract** [comment]
Thank you for explaining.

For me, I think the problem is that by having versions identified with "x.x.x", semantic versioning is implied (maybe I am alone in this). So I think it would be less confusing to follow semantic versioning and have the consequent high major version numbers. It is unclear to me what would constitute a major version change with the current scheme.

**Comment by MaartenGr** [comment]
High major version numbers would actually communicate quite some instability with the package. Often with semantic versioning, initial development stays at 0.x.y as there are quite some changes possible to the API between each successive version until the first major version (1.0.0) to indicate stability. I might go to the first major version in one of the upcoming releases but only if there is sufficient stability with respect to the API for the foreseeable future in order to prevent high major versions.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
