### ISSUE TITLE
How do I calculate the probabilities of all topics in a document after reducing outliers or merging topics?

### ISSUE THREAD

**Issue by jiannan-xu** [MaartenGr/BERTopic#959]
Hello!
I've been using BERTopic for a research project and I have a question. How can I calculate the probabilities of all topics in a document after reducing outliers or merging topics? After I completed the operations below, I still get the "topics" and "probs" for the original model before I reduce the outliers.

from hdbscan import all_points_membership_vectors

topics = topic_model._map_predictions(topic_model.hdbscan_model.labels_)
probs = all_points_membership_vectors(topic_model.hdbscan_model)
probs = topic_model._map_probabilities(probs, original_topics=False)

**Comment by MaartenGr** [comment]
When you run `.merge_topics` the internal probabilities get updated in order to match with the newly merged topics. Note that this is only the case if you have set `calculate_probabilities=True`. Then, you can access the topics and probabilities with `topic_model.topics_` and `topic_model.probabilities_` respectively. 

The example code that you are showing is not advised since you are accessing private functions in BERTopic which are not meant to be accessed by the user directly.

**Comment by jiannan-xu** [comment]
Thanks! I have a further question about the probabilities. Does reducing outliers influence the probabilities of topics? I received the exact same probabilities. However, when I merged topics, the internal probabilities get updated.

**Comment by MaartenGr** [comment]
It depends on the probabilities, whether `calculate_probabilities=True` is used or not but it should not influence the probabilities if `calculate_probabilities=False`. The probabilities will indeed be less accurate and you might need a different statistic, such as distance depending on the strategy used for reducing outliers. 

It is generally not advised to further merge the topics after reducing outliers. You can find more about that [here](https://maartengr.github.io/BERTopic/getting_started/outlier_reduction/outlier_reduction.html#update-topics).

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
