### ISSUE TITLE
Combining custom vectorizer_model with BERT's embedding_model

### ISSUE THREAD

**Issue by aleksandar-devedzic** [MaartenGr/BERTopic#961]
Is there any logic between combining custom vectorising model with BERT's embedding_model?
For example:

```
bert_topic_model = BERTopic(vectorizer_model = CUSTOM_transformerVectoriser,  embedding_model = "paraphrase-multilingual-MiniLM-L12-v2" )
```
Can that lead to increasing or decreasing performance of the model? 
Can I use both of them, or should I choose only one?

**Comment by MaartenGr** [comment]
The vectorizer and the embedding model are mostly independent of one another. This is because, in BERTopic, we want to separate the process of clustering the documents from the process of representing the topics. This allows for a lot of modularity and flexibility with respect to the underlying algorithms that you can choose. I would advise reading through the [algorithm](https://maartengr.github.io/BERTopic/algorithm/algorithm.html) page of BERTopic to get a more intuitive understanding of what it means to use those sub-models.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
