### ISSUE TITLE
in BERTopic v0.13, what's the best way to clean the topics names?

### ISSUE THREAD

**Issue by Alla-Abdella** [MaartenGr/BERTopic#963]
If topic0 is fight_figthing_fighter_guns
can we eliminate the first three words into only fighting? I tried diversity = 0.8 and I still see the same results.

I found this answer, but I'm not sure about the interpretation of topics and how that will affect the embedding.

from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from nltk import word_tokenize          
from nltk.stem import WordNetLemmatizer 

class LemmaTokenizer:
    def __init__(self):
        self.wnl = WordNetLemmatizer()
    def __call__(self, doc):
        return [self.wnl.lemmatize(t) for t in word_tokenize(doc)]

vectorizer_model= CountVectorizer(tokenizer=LemmaTokenizer()) 

topic_model = BERTopic(vectorizer_model=vectorizer_model)

**Comment by MaartenGr** [comment]
`diversity=0.8` should change the output. If it does not, then that likely means that you either did not pass an `embedding_model` or that you trained BERTopic with pre-calculated embeddings. Could you share your entire code for training BERTopic, including potential preprocessing steps and the fitting process itself? 

With respect to the code that you shared, the `CountVectorizer` **will not** affect the embeddings itself since they are generated before the `CountVectorizer` is actually used. You can find more about the pipeline in BERTopic [here](https://maartengr.github.io/BERTopic/algorithm/algorithm.html).

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
