### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by christa27** [MaartenGr/BERTopic#99]
Hi! Thanks so much for developing this, awesome :) 

I've noticed that running the model again with the same settings, can give (sometimes very) different results. I set a random seed on the UMAP model, but this didn't work. 
Does this occur because of the sentence transformer or because of HDBSCAN? (Or perhaps something else) And is there a way to fix it?

I've also got some questions about the parameter settings of UMAP: 

* I see that UMAP is set on n_neighbours = 15 and n_components = 5. Is there a specific reason for this?

Thanks, regards Christa

**Comment by MaartenGr** [comment]
Thank you for your kind words!

Due to the stochastic nature of UMAP, the results from BERTopic might differ even if you run the same code multiple times. Although there are options to set a seed in UMAP [here](https://umap-learn.readthedocs.io/en/latest/reproducibility.html) this might actually hinder performance and is typically not advised. 

The value for `n_neighbours` is the default value in UMAP. In order to stay as close as possible to their implementation, this was kept. The value for `n_components` was chosen for its interaction with HDBSCAN. We want to reduce the dimensionality as much as possible for HDBSCAN as it has difficulties with high-dimensional data. On the other hand, going too small will mean that information will be lost that could have been vital. For that reason, and after experimentation, 5 was chosen to maximize HDBSCAN's performance. 

Fortunately, you can use any UMAP or HDBSCAN model you like! So you can play around with settings that you might be better suited to your use case.

**Comment by christa27** [comment]
Thanks! That's helpful. 
I'm indeed trying out my own UMAP and HDBSCAN versions. 

One more question 🐵  Why the 'cosine' metric for UMAP? I see there are many options available.

**Comment by MaartenGr** [comment]
There are indeed many options available! The main reason for choosing 'cosine' is that it allows for quick computation whilst still being able to perform well on higher-dimensional data. With euclidean-based measures, distances mean very little on high-dimensional data. To cope with that, we need a technique that is less sensitive to the data's dimensionality.

**Comment by volhakatebi** [comment]
Hi @MaartenGr, I reran my BERTopic script on Google Collab (T4 GPU) and I also get different results even though I set random seed in UMAP. Is that expected to observe different results on Google collab?

**Comment by MaartenGr** [comment]
@volhakatebi I can't say since I am not familiar with your script, installations, data,  underlying models, etc. In general, if you are using the latest versions of all dependencies (including cuML UMAP or the default UMAP) it should be reproducible. But again, can't say without knowing more.
