### ISSUE TITLE
incremental topic modelling using standard version of BERTopic

### ISSUE THREAD

**Issue by mjavedgohar** [MaartenGr/BERTopic#990]
Hi @MaartenGr 
I tried the BERTopic for incremental topic modeling  (https://maartengr.github.io/BERTopic/getting_started/online/online.html)  but the results were not satisfactory as compared to standard version of BERtopic. Can we use the default version of BERTopic for incremental topic modelling?

Thanks

**Comment by MaartenGr** [comment]
Unfortunately, that is not possible. In the online version of BERTopic, we need dimensionality reduction and clustering models that natively support a `.partial_fit` like function. This is not the case for HDBSCAN and, to some extent, also for UMAP. Instead, you will need to use submodels that support that functionality in order to scale BERTopic that way.

**Comment by MaartenGr** [comment]
Due to inactivity, I'll be closing this issue. Let me know if you want me to re-open the issue!
