### ISSUE TITLE
keywords vectors

### ISSUE THREAD

**Issue by kimkyulim** [MaartenGr/BERTopic#995]
I want to ask about keywords vectors.

Previously, I asked you about the value of the keywords vectors to get the keywords similarity.

The way you taught me is...

"word_embeddings = topic_model._extract_embeddings(my_list_of_words, method="word", verbose=True)" 

I just did it, and I have a question here.

For example, in the model I saved, keyword1 in topic 1 and keyword100 in topic 10 are both words toy. And the word vectors is the same. However, when checked using find_topics (search_term='toy', top_n=10), it does not come out as similar topics within the top 10.

Q1. Why do keyword1 and keyword100 vectors come out the same?
Q 2. Another question, does class in the Bertopic algorithm mean topic? Can I think of one class as one topic?

Please give me an answer me.

**Comment by MaartenGr** [comment]
> Q1. Why do keyword1 and keyword100 vectors come out the same?

During the training of BERTopic, topic embeddings are created. These topic embeddings are currently a weighted average of the top 10 keywords in a topic. We only take the top 10 keywords as we assume that keyword 100 gives much less information than the first 10. 

The `.find_topics` function then embeds your search term and compares that with the topic embedding. Since the topic embedding focuses only on the top 10 keywords it will find the topics that close matches it. 

Moreover, because we generate a topic-term matrix, each word technically appears in every single topic their weights are just quite different. 

> keyword1 in topic 1 and keyword100 in topic 10 are both words toy

Another thing to note here is that just because keyword 100 is toy, that does not mean that the entire topic is about toy. There is a reason it is the 100th keyword and not the 1st and that is likely because it is not the best representative keyword for that topic. 

> Q 2. Another question, does class in the Bertopic algorithm mean topic? Can I think of one class as one topic?

Generally, yes. BERTopic is essentially a clustering task and the resulting clusters can be called clusters, topics, or classes. Whatever you prefer.

**Comment by kimkyulim** [comment]
Hi. @MaartenGr 

I don't think my question number 1 was delivered to you exactly.
Keyword1 and keyword100 I said were just examples.
The keyword_number I said doesn't mean anything. Let me explain it again.

All I wanted to ask is, right below.

Q1.

When I used "word_embedings = topic_model._extract_embedings(my_list_of_words, method="word", verbose=True)" you told me last time, I asked you because the keyword of topic1 and the keyword of topic7 are the same word, but the embedding back were abnormal. Why do the same keywords in different topics have the same embedding vector? I understand that the keywords are the same, but I don't understand that the embedding vector is the same.

because,
Bertopic's order of progress is (1) embedded document-> (2) dimensional reduction-> (3) document clustering-> (4) bag of words-> (5) topic presentation.

If so, (3) In the process of clustering documents, the clustered clusters can be viewed as topic, and the topic1 and topic7 I mentioned in the example mean that the clustered locations are different because the topic is different.

Then shouldn't the embedding vector come out differently even if the words in each topic are the same? (Because the positions of each clustered topic are different)


Question 2. (It follows question 1).

"word_embedings = topic_model._extract_embedings(my_list_of_words, method="word", verbose=True)" that you told me is the result of which stage between the order of progress (1) and (5) of the vertical?


Q3.

What I want to do is to find the similarity between the keywords that make up the topics.

For example, I want to get similarity between words in topic1 and between words in topic2 as well as similarity between words in topic1 and words in topic2.
So I can find the similarity between word_embedding using the "word_embedding = topic_model._extract_embedding(my_list_of_words, method="word" method you told me, right?

---------------------------------------


Thank you for always answering kindly.
Thanks to you, it is very helpful to understand and use Bertopic.
I hope you have a good day.
